### ISSUE TITLE
Crash in debug mode and Close the app

### ISSUE THREAD

**Issue by JeanLuisJimenez** [transistorsoft/react-native-background-geolocation#1023]
I have this code in useEfect function:
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.onLocation(
      response => onLocation(response, setState),
      onError,
    );

    // This handler fires when movement states changes (stationary->moving; moving->stationary)
    BackgroundGeolocation.onMotionChange(onMotionChange);

    // This event fires when a change in motion activity is detected
    BackgroundGeolocation.onActivityChange(onActivityChange);

    // This event fires when the user toggles location-services authorization
    BackgroundGeolocation.onProviderChange(onProviderChange);

    ////
    // 2.  Execute #ready method (required)
    //
    await BackgroundGeolocation.ready(
      {
        // Geolocation Config
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
        distanceFilter: 100,
        // Application config
        debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true, // <-- Auto start tracking when device is powered-up.
      },
      state => {
        console.log(
          '- BackgroundGeolocation is configured and ready: ',
          state.enabled,
        );

        if (!state.enabled) {
          ////
          // 3. Start tracking!
          //
          BackgroundGeolocation.start(function() {
            console.log('- Start success');
          });
        }
      },
    );

    return () => {
      BackgroundGeolocation.removeListeners();
    };
```

So, when I launch the app in release mode it crash without tell me what going bad

## Your Environment
* Plugin version: 3.4.2
* Platform: Android 
* Device manufacturer / model: Huawei p30 lite
* React Native version (`react-native -v`): 3.2.1 && 0.60.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->

 {
        // Geolocation Config
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
        distanceFilter: 100,
        // Application config
        debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true, // <-- Auto start tracking when device is powered-up.
      },
      state => {
        console.log(
          '- BackgroundGeolocation is configured and ready: ',
          state.enabled,
        );

        if (!state.enabled) {
          ////
          // 3. Start tracking!
          //
          BackgroundGeolocation.start(function() {
            console.log('- Start success');
          });
        }
      },
```

## Expected Behavior

I think it have to get the location or at least not crash the app

## Actual Behavior

The app crash cause of the plugin

## Steps to Reproduce

1. Install the plugin and setup it
2. Connect the testing device with adb
3. run `npm start && npm run android --appIdSuffix dev --variant devDebug`
4. It will open the app in the device, after launch it close

## Context

I'm trying to get current location to save it in a DB but it not works

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
--------- beginning of crash
--------- beginning of system
--------- beginning of main
04-09 17:48:18.786 26573 26668 E TSLocationManager: 
04-09 17:48:18.786 26573 26668 E TSLocationManager: ╔═════════════════════════════════════════════
04-09 17:48:18.786 26573 26668 E TSLocationManager: ║ LICENSE VALIDATION FAILURE: com.optic.covdr
04-09 17:48:18.786 26573 26668 E TSLocationManager: ╠═════════════════════════════════════════════
04-09 17:48:18.786 26573 26668 E TSLocationManager: ╟─ Invalid license 
key: YOUR_LICENCE_KEY_HERE
04-09 17:48:18.786 26573 26668 E TSLocationManager: ╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.
04-09 17:48:18.786 26573 26668 E TSLocationManager: ╚═════════════════════════════════════════════
04-09 17:48:18.815 26573 26668 I TSLocationManager: [c.t.l.adapter.TSConfig print]
04-09 17:48:18.815 26573 26668 I TSLocationManager: ╔═════════════════════════════════════════════
04-09 17:48:18.815 26573 26668 I TSLocationManager: ║ TSLocationManager version: 3.0.44 (344)
04-09 17:48:18.815 26573 26668 I TSLocationManager: ╠═════════════════════════════════════════════
04-09 17:48:18.815 26573 26668 I TSLocationManager: {
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "activityRecognitionInterval": 10000,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "allowIdenticalLocations": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "authorization": 
{},
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "autoSync": true,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "autoSyncThreshold": 0,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "batchSync": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "configUrl": "", 
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "debug": true,   
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "deferTime": 0,  
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "desiredAccuracy": 10,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "desiredOdometerAccuracy": 100,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "disableAutoSyncOnCellular": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "disableElasticity": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "disableLocationAuthorizationAlert": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "disableMotionActivityUpdates": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "disableStopDetection": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "distanceFilter": 100,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "elasticityMultiplier": 1,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "enableHeadless": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "enableTimestampMeta": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "encrypt": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "extras": {},    
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "fastestLocationUpdateInterval": -1,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "forceReloadOnBoot": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "forceReloadOnGeofence": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "forceReloadOnHeartbeat": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "forceReloadOnLocationChange": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "forceReloadOnMotionChange": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "forceReloadOnSchedule": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "foregroundService": true,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "geofenceInitialTriggerEntry": true,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "geofenceModeHighAccuracy": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "geofenceProximityRadius": 1000,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "geofenceTemplate": "",
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "headers": {},   
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessTask",        
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "heartbeatInterval": -1,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "httpRootProperty": "location",
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "httpTimeout": 60000,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "isMoving": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "locationAuthorizationRequest": "Always",
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "locationTemplate": "",
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "locationTimeout": 60,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "locationUpdateInterval": 1000,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "locationsOrderDirection": "ASC",
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "logLevel": 5,   
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "logMaxDays": 3, 
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "maxBatchSize": -1,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "maxDaysToPersist": 1,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "maxRecordsToPersist": -1,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "method": "POST",
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "minimumActivityRecognitionConfidence": 75,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "notification": {
04-09 17:48:18.815 26573 26668 I TSLocationManager:     "layout": "",  
04-09 17:48:18.815 26573 26668 I TSLocationManager:     "title": "",   
04-09 17:48:18.815 26573 26668 I TSLocationManager:     "text": "Location Service activated",
04-09 17:48:18.815 26573 26668 I TSLocationManager:     "color": "",   
04-09 17:48:18.815 26573 26668 I TSLocationManager:     "channelName": 
"TSLocationManager",
04-09 17:48:18.815 26573 26668 I TSLocationManager:     "smallIcon": "",
04-09 17:48:18.815 26573 26668 I TSLocationManager:     "largeIcon": "",
04-09 17:48:18.815 26573 26668 I TSLocationManager:     "priority": 0, 
04-09 17:48:18.815 26573 26668 I TSLocationManager:     "strings": {}, 
04-09 17:48:18.815 26573 26668 I TSLocationManager:     "actions": []  
04-09 17:48:18.815 26573 26668 I TSLocationManager:   },
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "params": {},    
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "persist": true, 
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "persistMode": 2,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "schedule": [],  
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "scheduleUseAlarmManager": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "speedJumpFilter": 300,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "startOnBoot": true,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "stationaryRadius": 25,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "stopAfterElapsedMinutes": 0,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "stopOnStationary": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "stopOnTerminate": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "stopTimeout": 5,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking",
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "url": "",       
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "useSignificantChangesOnly": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "enabled": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "schedulerEnabled": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "trackingMode": 1,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "odometer": 0,   
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "isFirstBoot": false,
04-09 17:48:18.815 26573 26668 I TSLocationManager:   "didLaunchInBackground": false
04-09 17:48:18.815 26573 26668 I TSLocationManager: }
04-09 17:48:18.815 26573 26668 I TSLocationManager: ╔═════════════════════════════════════════════
04-09 17:48:18.815 26573 26668 I TSLocationManager: ║ DEVICE SENSORS   
04-09 17:48:18.815 26573 26668 I TSLocationManager: ╠═════════════════════════════════════════════
04-09 17:48:18.815 26573 26668 I TSLocationManager: ╟─ ✅  ACCELEROMETER: {Sensor name="accelerometer-bmi160", vendor="bosch", version=1, type=1, maxRange=78.4532, resolution=9.576806E-6, power=0.23, minDelay=4000}
04-09 17:48:18.815 26573 26668 I TSLocationManager: ╟─ ✅  GYROSCOPE: {Sensor name="bosch-bmi160", vendor="bosch", version=1, type=4, maxRange=34.906586, resolution=1.7453292E-5, power=6.1, minDelay=4000}
04-09 17:48:18.815 26573 26668 I TSLocationManager: ╟─ ✅  MAGNETOMETER: {Sensor name="mag-akm09918", vendor="akm", version=1001, type=2, maxRange=2000.0, resolution=0.0625, power=6.8, minDelay=10000}
04-09 17:48:18.815 26573 26668 I TSLocationManager: ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="significant Motion", vendor="huawei", version=1, 
type=17, maxRange=2.14748365E9, resolution=1.0, power=0.23, minDelay=-1}
04-09 17:48:18.815 26573 26668 I TSLocationManager: ╚═════════════════════════════════════════════
04-09 17:48:18.847 26573 26638 I TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>]
04-09 17:48:18.847 26573 26638 I TSLocationManager:   ✅  Google Play Services: connected (version code:12451000)
04-09 17:48:18.869 26573 26674 D TSLocationManager: [c.t.l.data.sqlite.b prune]
04-09 17:48:18.869 26573 26674 D TSLocationManager:   ℹ️  PRUNE -1 days

04-09 17:48:18.883 26573 26638 I TSLocationManager: [c.t.l.a.BackgroundGeolocation e]
04-09 17:48:18.883 26573 26638 I TSLocationManager:   �🎾  Start monit
ing location-provider changes
04-09 17:48:20.580 26573 26673 D TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config, dirty: [debug, desiredAccuracy, distanceFi
lter, headlessJobService, logLevel, startOnBoot, stopOnTerminate]      
04-09 17:48:20.593 26573 26673 D TSLocationManager: [c.t.l.a.BackgroundGeolocation ready] LocationPermission :false
04-09 17:48:20.716 26573 26673 I TSLocationManager: [c.t.locationmanager.util.b a]
04-09 17:48:20.716 26573 26673 I TSLocationManager:   �🔵  LocationAut
rization: Requesting Background permission
04-09 17:48:20.823 26573 26573 E TSLocationManager: [c.t.l.a.BackgroundGeolocation$e uncaughtException]
04-09 17:48:20.823 26573 26573 E TSLocationManager:   ‼️  Uncaught Exce
ption: Failed resolution of: Landroidx/localbroadcastmanager/content/LocalBroadcastManager;
04-09 17:48:20.823 26573 26573 E TSLocationManager: {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":0,"batchSync":false,"configUrl":"","debug":true,"deferTime":0,"desiredAccuracy":10,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableStopDetection":false,"distanceFilter":100,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"encrypt":false,"extras":{},"fastestLocationUpdateInterval":-1,"forceReloadOnBoot":false,"forceReloadOnGeofence":false,"forceReloadOnHeartbeat":false,"forceReloadOnLocationChange":false,"forceReloadOnMotionChange":false,"forceReloadOnSchedule":false,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.rnbackgroundgeolocation.HeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":5,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"notification":{"layout":"","title":"","text":"Location Service 
activated","color":"","channelName":"TSLocationManager","smallIcon":"","largeIcon":"","priority":0,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":true,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":5,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"","useSignificantChangesOnly":false,"enabled":false,"schedulerEnabled":false,"trackingMode":1,"odometer":0,"isFirstBoot":false,"didLaunchInBackground":false}
04-09 17:48:20.823 26573 26573 E TSLocationManager: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/localbroadcastmanager/content/LocalBroadcastManager;
04-09 17:48:20.823 26573 26573 E TSLocationManager:     at com.intentfilter.androidpermissions.PermissionManager.registerBroadcastReceiver(PermissionManager.java:87)
04-09 17:48:20.823 26573 26573 E TSLocationManager:     at com.intentfilter.androidpermissions.PermissionHandler.registerForBroadcastIfNeeded(PermissionHandler.java:124)
04-09 17:48:20.823 26573 26573 E TSLocationManager:     at com.intentfilter.androidpermissions.PermissionHandler.checkPermissions(PermissionHandler.java:44)
04-09 17:48:20.823 26573 26573 E TSLocationManager:     at com.intentfilter.androidpermissions.PermissionManager.checkPermissions(PermissionManager.java:50)
04-09 17:48:20.823 26573 26573 E TSLocationManager:     at com.transistorsoft.locationmanager.util.b$5.run(Unknown Source:31)
04-09 17:48:20.823 26573 26573 E TSLocationManager:     at android.os.Handler.handleCallback(Handler.java:907)
04-09 17:48:20.823 26573 26573 E TSLocationManager:     at android.os.Handler.dispatchMessage(Handler.java:105)
04-09 17:48:20.823 26573 26573 E TSLocationManager:     at android.os.Looper.loop(Looper.java:216)
04-09 17:48:20.823 26573 26573 E TSLocationManager:     at android.app.ActivityThread.main(ActivityThread.java:7625)
04-09 17:48:20.823 26573 26573 E TSLocationManager:     at java.lang.reflect.Method.invoke(Native Method)
04-09 17:48:20.823 26573 26573 E TSLocationManager:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)  
04-09 17:48:20.823 26573 26573 E TSLocationManager:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
04-09 17:48:20.823 26573 26573 E TSLocationManager: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.localbroadcastmanager.content.LocalBroadcastManager" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.optic.covdr-LzgO45EQ_7WMeG9gfkubNw==/base.apk"],nativeLibraryDirectories=[/data/app/com.optic.covdr-LzgO45EQ_7WMeG9gfkubNw==/lib/arm64, /data/app/com.optic.covdr-LzgO45EQ_7WMeG9gfkubNw==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
04-09 17:48:20.823 26573 26573 E TSLocationManager:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
04-09 17:48:20.823 26573 26573 E TSLocationManager:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
04-09 17:48:20.823 26573 26573 E TSLocationManager:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-09 17:48:20.823 26573 26573 E TSLocationManager:     ... 12 common frames omitted
```

</details>

**Comment by christocracy** [comment]
Duplicate #1017.  This dependency has been added to latest `2.6.2`
