### ISSUE TITLE
Warning in Play store deployment

### ISSUE THREAD

**Issue by billnbell** [transistorsoft/react-native-background-geolocation#1253]
Android

API (unsupported)

Warning
API
Landroid/app/AppGlobals;->getInitialApplication()Landroid/app/Application;
Stack trace #1
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/app/AppGlobals;->getInitialApplication()Landroid/app/Application;
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/app/AppGlobals;->getInitialApplication()Landroid/app/Application;
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getMethod(Class.java:2064)
	at java.lang.Class.getDeclaredMethod(Class.java:2047)
	at ch.qos.logback.core.android.AndroidContextUtil.getContext(Unknown Source:11)
	at ch.qos.logback.core.android.AndroidContextUtil.<init>(Unknown Source:0)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(Unknown Source:7)
	at org.slf4j.impl.StaticLoggerBinder.init(Unknown Source:7)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(Unknown Source:16)
	at org.slf4j.impl.StaticLoggerBinder.getSingleton(Unknown Source:0)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at com.transistorsoft.locationmanager.logger.TSLog.getRootLogger(Unknown Source:6)
	at com.transistorsoft.locationmanager.logger.TSLog.initialize(Unknown Source:0)
	at com.transistorsoft.locationmanager.logger.TSLog.<clinit>(Unknown Source:320)
	at com.transistorsoft.locationmanager.logger.TSLog.setLogLevel(Unknown Source:0)
	at com.transistorsoft.locationmanager.adapter.TSConfig.load(Unknown Source:43)
	at com.transistorsoft.locationmanager.adapter.TSConfig.<init>(Unknown Source:59)
	at com.transistorsoft.locationmanager.adapter.TSConfig.a(Unknown Source:9)
	at com.transistorsoft.locationmanager.adapter.TSConfig.getInstance(Unknown Source:14)
	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.<init>(RNBackgroundGeolocationModule.java:94)
	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocation.createNativeModules(RNBackgroundGeolocation.java:19)
	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225)
	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
	at java.lang.Thread.run(Thread.java:764)

**Comment by christocracy** [comment]
`at ch.qos.logback.core.android.`

This comes from the plugin's logger sdk `log back-Android`.

You'll not be using the logger in a release app (LOG_LEVEL_NONE).  I will see if there are reported issues at this repo / check for version update.

**Comment by mikehardy** [comment]
CocoaLumberjack has an update, while you're at it. Always shows up in my pod update scans ;-)

**Comment by christocracy** [comment]
Yea, it was on my mind after the big xcframework migration.
