### ISSUE TITLE
Location updates not received in Android

### ISSUE THREAD

**Issue by ma2kutty** [transistorsoft/react-native-background-geolocation#1290]
## Your Environment
* Plugin version: 4.0.3
* Platform:  Android 
* OS version: 
* Device manufacturer / model: One plus 6t
* React Native version (`react-native -v`): 0.62.2
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->

		BackgroundGeolocation.ready({
			logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
			desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
			distanceFilter: 1000,
			stopOnTerminate: false,
			debug: true,
			startOnBoot: true,
			locationAuthorizationRequest: 'Always',
			disableMotionActivityUpdates: false,
		  }, (state) => {
			Controller.log('LocMgr:: BGL BackgroundGeolocation is configured and ready state.enabled: ' + state.enabled)
			if (!state.enabled) {
			  ////
			  // 3. Start tracking!
			  //
			  BackgroundGeolocation.start(function () {
				Controller.log('BackgroundGeolocation:: start is success ' + JSON.stringify(state))
				console.log('BackgroundGeolocation:: start is success ' + JSON.stringify(state))
				callback(null, true)
			  });
			} else {
				Controller.log('LocMgr:: BGL BackgroundGeolocation is already configured and ready state.enabled: ' + state.enabled)
				callback(null, false)
			}
		  }, (error) => {
			console.log('BackgroundGeolocation:: start is failed ' + JSON.stringify(error))
			Controller.log('BackgroundGeolocation:: start is failed ' + JSON.stringify(error))
			callback(error)
		  });
```

## Expected Behavior

Tested the application in real time, when the application is background 'BackgroundGeolocation.onLocation' should be triggered and the app processes the same.

## Actual Behavior

When the application is background the 'BackgroundGeolocation.onLocation' is not triggered at expected distance intervals. Instead we also observed when we cover a much longer distance 'BackgroundGeolocation.onLocation' getting triggered continuously (3-4 times with one second gap). When 'BackgroundGeolocation.onLocation' is triggered, we are calling an API to send the locations to the backend. We can see the logs for calling our API, but the API success / failure logs were missing (our internal logs). 
Note: The same code base is tested fine for IOS in real time in the same distance track. In IOS we are getting location updates at expected distance intervals. Also we have bought the license for android build.
## Steps to Reproduce

1. Integrate the library
2. Put the app in background
3. Test in real time by travelling
4. Location updates not received on phone

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
04-19 20:52:21.187 DEBUG [TSConfig d] ℹ️   Persist config, dirty: [debug, desiredAccuracy, distanceFilter, logLevel, startOnBoot, stopOnTerminate]
04-19 20:52:21.518 INFO [c e] 
  🔵  LocationAuthorization: Requesting Background permission
04-19 20:52:23.032 INFO [c$i onPermissionGranted] 
  ✅  LocationAuthorization: Permission granted
04-19 20:52:23.052 INFO [ActivityRecognitionService b] 
  🎾  Start motion-activity updates
04-19 20:52:23.059 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
04-19 20:52:23.059 DEBUG [HttpService startMonitoringConnectivityChanges] 
  🎾  Start monitoring connectivity changes
04-19 20:52:23.064 DEBUG [a c] 
  🎾  Start monitoring powersave changes
04-19 20:52:23.066 DEBUG [HttpService a] 
╔═════════════════════════════════════════════
║ 📶  Connectivity change: connected? true
╠═════════════════════════════════════════════

04-19 20:52:23.081 INFO [HeartbeatService c] 
  🔴  Stop heartbeat
04-19 20:52:23.084 DEBUG [c f] 
  ℹ️  LocationAuthorization: Permission granted
04-19 20:52:23.084 INFO [TrackingService a] 
  🔵  setPace: false → false
04-19 20:52:23.090 DEBUG [TSLocationManagerActivity execute] locationsettings
04-19 20:52:23.092 DEBUG [TSConfig translateDesiredAccuracy] translateDesiredAccuracy (true): -1
04-19 20:52:23.126 DEBUG [TSLocationManagerActivity stop] eventCount: 0
04-19 20:52:23.151 DEBUG [TSLocationManagerActivity onDestroy] 
04-19 20:52:23.268 DEBUG [AbstractService a] 
  🎾  LocationRequestService [eventCount: 1]
04-19 20:52:23.269 INFO [LocationRequestService a] 
  ℹ️  Location availability: true
04-19 20:52:23.269 DEBUG [AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
04-19 20:52:23.521 DEBUG [AbstractService onDestroy] 
  🔴  LocationRequestService destroyed
04-19 20:52:24.829 DEBUG [AbstractService a] 
  🎾  LocationRequestService [eventCount: 1]
04-19 20:52:24.830 INFO [LocationRequestService b] 
╔═════════════════════════════════════════════
║ motionchange LocationResult: 1
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 9.568388,76.841238 hAcc=2254 et=+5d8h1m48s604ms alt=-12.839865598449204 vAcc=3 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 1560ms, time: 1618845743270

04-19 20:52:24.835 DEBUG [TSMediaPlayer play] ‼️   Unknown sound key: TSLOCATIONMANAGER_CLICK_TAP_DONE_CHECKBOX5_FULL_VOL
04-19 20:52:24.836 DEBUG [TSLocationManager calculateMedianAccuracy] Median accuracy: 2254.0
04-19 20:52:24.842 DEBUG [LocationRequestService b] SingleLocationRequest 1 isFinished? false
04-19 20:52:24.842 DEBUG [AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
04-19 20:52:26.480 INFO [TSScheduleManager oneShot] 
  ⏰ Oneshot TERMINATE_EVENT is already pending
04-19 20:52:26.707 DEBUG [AbstractService a] 
  🎾  LocationRequestService [eventCount: 1]
04-19 20:52:26.709 INFO [LocationRequestService b] 
╔═════════════════════════════════════════════
║ motionchange LocationResult: 1
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 9.569779,76.838646 hAcc=19 et=+5d8h1m52s18ms alt=-38.64908188034425 vel=0.52 bear=301.0 vAcc=24 sAcc=1 bAcc=82 {Bundle[mParcelledData.dataSize=52]}], age: 24ms, time: 1618845748000

04-19 20:52:26.711 DEBUG [TSLocationManager calculateMedianAccuracy] Median accuracy: 1136.648
04-19 20:52:26.711 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired motionchange position, isMoving: false
04-19 20:52:26.724 DEBUG [LocationRequestService b] SingleLocationRequest 1 isFinished? true
04-19 20:52:26.724 DEBUG [AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
04-19 20:52:26.727 INFO [b persist] 
  ✅  INSERT: 32353959-5476-4eba-adfa-70aad5d44af6
04-19 20:52:26.736 DEBUG [AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
04-19 20:52:26.740 INFO [ActivityRecognitionService b] 
  🎾  Start motion-activity updates
04-19 20:52:26.741 DEBUG [TSGeofenceManager startMonitoringStationaryRegion] 
  🎾  Start monitoring stationary region (radius: 150.0m 9.5697788,76.8386464 hAcc=19.296)
04-19 20:52:26.767 DEBUG [AbstractService a] 
  🎾  TrackingService [eventCount: 1]
04-19 20:52:26.767 DEBUG [AbstractService a] ⚙️︎  finish TrackingService [eventCount: 0, sticky: false]
04-19 20:52:26.767 INFO [TrackingService h] 
╔═════════════════════════════════════════════
║ TrackingService motionchange: false
╠═════════════════════════════════════════════

04-19 20:52:26.977 DEBUG [AbstractService onDestroy] 
  🔴  LocationRequestService destroyed
04-19 20:52:27.020 DEBUG [AbstractService onDestroy] 
  🔴  TrackingService destroyed
04-19 20:52:30.090 DEBUG [AbstractService a] 
  🎾  ActivityRecognitionService [eventCount: 1]
04-19 20:52:30.092 DEBUG [ActivityRecognitionService a] 
  🚘 ️DetectedActivity [type=UNKNOWN, confidence=40]
04-19 20:52:30.094 DEBUG [AbstractService a] ⚙️︎  finish ActivityRecognitionService [eventCount: 0, sticky: false]
04-19 20:52:31.103 DEBUG [AbstractService onDestroy] 
  🔴  ActivityRecognitionService destroyed
04-19 20:52:33.116 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

04-19 20:52:33.120 DEBUG [TerminateEvent <init>] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
04-19 20:52:47.115 WARN [RNBackgroundGeolocationModule ready] 
  ⚠️  #ready already called.  Redirecting to #setConfig
04-19 20:52:52.123 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
04-19 20:53:02.208 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

04-19 20:53:02.211 DEBUG [TerminateEvent <init>] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
04-19 20:59:42.982 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
04-19 20:59:53.075 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

04-19 20:59:53.078 DEBUG [TerminateEvent <init>] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
04-19 20:59:59.452 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
04-19 21:00:09.542 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

04-19 21:00:09.544 DEBUG [TerminateEvent <init>] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
04-19 21:00:13.737 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
04-19 21:00:23.798 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

04-19 21:00:23.800 DEBUG [TerminateEvent <init>] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).
04-19 21:12:33.035 DEBUG [AbstractService a] 
  🎾  ActivityRecognitionService [eventCount: 1]
04-19 21:12:33.045 DEBUG [TSConfig d] ℹ️   Persist config, dirty: [isMoving]
04-19 21:12:33.049 INFO [HeartbeatService c] 
  🔴  Stop heartbeat
04-19 21:12:33.052 DEBUG [TSGeofenceManager stopMonitoringStationaryRegion] 
  🔴  Stop monitoring stationary region
04-19 21:12:33.057 DEBUG [c f] 
  ℹ️  LocationAuthorization: Permission granted
04-19 21:12:33.058 INFO [TrackingService a] 
  🔵  setPace: false → true
04-19 21:12:33.058 INFO [ActivityRecognitionService a] 
╔═════════════════════════════════════════════
║ Motion Transition Result
╠═════════════════════════════════════════════
╟─ 🔴  EXIT: in_vehicle
╟─ 🎾  ENTER: walking
╚═════════════════════════════════════════════
04-19 21:12:33.058 DEBUG [AbstractService a] ⚙️︎  finish ActivityRecognitionService [eventCount: 0, sticky: false]
04-19 21:12:33.090 DEBUG [AbstractService a] 
  🎾  TrackingService [eventCount: 1]
04-19 21:12:33.091 INFO [TrackingService h] 
╔═════════════════════════════════════════════
║ TrackingService motionchange: true
╠═════════════════════════════════════════════

04-19 21:12:33.092 DEBUG [AbstractService a] ⚙️︎  finish TrackingService [eventCount: 0, sticky: true]
04-19 21:12:33.161 DEBUG [AbstractService a] 
  🎾  LocationRequestService [eventCount: 1]
04-19 21:12:33.162 INFO [LocationRequestService a] 
  ℹ️  Location availability: true
04-19 21:12:33.162 DEBUG [AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
04-19 21:12:33.199 DEBUG [AbstractService a] 
  🎾  LocationRequestService [eventCount: 1]
04-19 21:12:33.201 INFO [LocationRequestService b] 
╔═════════════════════════════════════════════
║ motionchange LocationResult: 2
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 9.568879,76.842228 hAcc=164 et=+5d8h21m54s863ms alt=-6.469201662315493 vel=0.0 bear=90.0 vAcc=3 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 3671ms, time: 1618846949529

04-19 21:12:33.201 DEBUG [TSLocationManager calculateMedianAccuracy] Median accuracy: 163.852
04-19 21:12:33.203 DEBUG [LocationRequestService b] SingleLocationRequest 2 isFinished? false
04-19 21:12:33.204 DEBUG [AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
04-19 21:12:33.314 DEBUG [AbstractService onDestroy] 
  🔴  ActivityRecognitionService destroyed
04-19 21:12:33.420 DEBUG [AbstractService onDestroy] 
  🔴  LocationRequestService destroyed
04-19 21:12:34.762 DEBUG [AbstractService a] 
  🎾  LocationRequestService [eventCount: 1]
04-19 21:12:34.763 INFO [LocationRequestService b] 
╔═════════════════════════════════════════════
║ motionchange LocationResult: 2
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 9.568880,76.842229 hAcc=98 et=+5d8h21m58s659ms alt=-5.801941909278394 vel=9.0270914E-4 bear=62.263046 vAcc=3 sAcc=??? bAcc=??? {Bundle[mParcelledData.dataSize=52]}], age: 1437ms, time: 1618846953326

04-19 21:12:34.763 DEBUG [TSLocationManager calculateMedianAccuracy] Median accuracy: 131.126
04-19 21:12:34.764 DEBUG [TSLocationManager incrementOdometer] Odometer: 405.69348
04-19 21:12:34.767 DEBUG [LocationRequestService b] SingleLocationRequest 2 isFinished? false
04-19 21:12:34.767 DEBUG [AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: true]
04-19 21:12:35.813 DEBUG [AbstractService a] 
  🎾  LocationRequestService [eventCount: 1]
04-19 21:12:35.814 INFO [LocationRequestService b] 
╔═════════════════════════════════════════════
║ motionchange LocationResult: 2
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 9.568571,76.842642 hAcc=41 et=+5d8h22m1s25ms alt=-5.7475449012419215 vel=1.7979885 bear=67.990776 vAcc=3 sAcc=4 bAcc=67 {Bundle[mParcelledData.dataSize=52]}], age: 122ms, time: 1618846957000

04-19 21:12:35.815 INFO [TSLocationManager onSingleLocationResult] 
  🔵  Acquired motionchange position, isMoving: true
04-19 21:12:35.815 DEBUG [TSLocationManager calculateMedianAccuracy] Median accuracy: 98.4
04-19 21:12:35.819 INFO [TSLocationManager requestLocationUpdates] 
  🎾  Location-services: ON
04-19 21:12:35.820 INFO [TSLocationManager requestLocationUpdates] 
  🎾  Location-services: ON
04-19 21:12:35.825 DEBUG [TSConfig translateDesiredAccuracy] translateDesiredAccuracy (true): -1
04-19 21:12:35.834 DEBUG [LocationRequestService b] SingleLocationRequest 2 isFinished? true
04-19 21:12:35.835 DEBUG [AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
04-19 21:12:35.836 INFO [b persist] 
  ✅  INSERT: 092bbe12-e7fd-4994-8446-070e3048a107
04-19 21:12:35.847 DEBUG [AbstractService a] ⚙️︎  finish LocationRequestService [eventCount: 0, sticky: false]
04-19 21:12:35.848 INFO [ActivityRecognitionService b] 
  🎾  Start motion-activity updates
04-19 21:12:35.862 INFO [TSLocationManager removeLocationUpdates] 
  🔴  Location-services: OFF
04-19 21:12:35.864 INFO [TSLocationManager requestLocationUpdates] 
  🎾  Location-services: ON
04-19 21:12:35.865 DEBUG [TSConfig translateDesiredAccuracy] translateDesiredAccuracy (true): -1
04-19 21:12:35.887 DEBUG [AbstractService a] 
  🎾  TrackingService [eventCount: 1]
04-19 21:12:35.890 DEBUG [TrackingService b] 
╔═════════════════════════════════════════════
║ TrackingService: LocationResult
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 9.568571,76.842642 hAcc=41 et=+5d8h22m1s25ms alt=-5.7475449012419215 vel=1.7979885 bear=67.990776 vAcc=3 sAcc=4 bAcc=67 {Bundle[mParcelledData.dataSize=52]}], age: 197ms, time: 1618846957000

04-19 21:12:35.893 DEBUG [AbstractService a] ⚙️︎  finish TrackingService [eventCount: 0, sticky: true]
04-19 21:12:35.898 DEBUG [TSLocationManager onLocationResult] 
╔═════════════════════════════════════════════
║ Process LocationResult
╠═════════════════════════════════════════════

04-19 21:12:35.899 DEBUG [TSLocationManager onLocationResult] 
  ℹ️  IGNORED: same as last location
04-19 21:12:35.909 DEBUG [AbstractService a] 
  🎾  TrackingService [eventCount: 1]
04-19 21:12:35.910 INFO [TrackingService a] 
  ℹ️  Location availability: true
04-19 21:12:35.910 DEBUG [AbstractService a] ⚙️︎  finish TrackingService [eventCount: 0, sticky: true]
04-19 21:12:36.091 DEBUG [AbstractService a] 
  🎾  TrackingService [eventCount: 1]
04-19 21:12:36.092 DEBUG [TrackingService b] 
╔═════════════════════════════════════════════
║ TrackingService: LocationResult
╠═════════════════════════════════════════════
╟─ 📍  Location[fused 9.568571,76.842642 hAcc=41 et=+5d8h22m1s25ms alt=-5.7475449012419215 vel=1.7979885 bear=67.990776 vAcc=3 sAcc=4 bAcc=67 {Bundle[mParcelledData.dataSize=52]}], age: 401ms, time: 1618846957000

04-19 21:12:36.093 DEBUG [TSLocationManager onLocationResult] 
╔═════════════════════════════════════════════
║ Process LocationResult
╠═════════════════════════════════════════════

04-19 21:12:36.093 DEBUG [TSLocationManager onLocationResult] 
  ℹ️  IGNORED: same as last location
04-19 21:12:36.096 DEBUG [AbstractService a] ⚙️︎  finish TrackingService [eventCount: 0, sticky: true]
04-19 21:12:36.110 DEBUG [AbstractService a] 
  🎾  TrackingService [eventCount: 1]
04-19 21:12:36.110 DEBUG [AbstractService a] ⚙️︎  finish TrackingService [eventCount: 0, sticky: true]
04-19 21:12:36.110 DEBUG [AbstractService onDestroy] 
  🔴  LocationRequestService destroyed
04-19 21:12:46.755 DEBUG [AbstractService a] 
  🎾  ActivityRecognitionService [eventCount: 1]
04-19 21:12:46.756 DEBUG [ActivityRecognitionService a] 
  🚘 ️DetectedActivity [type=TILTING, confidence=100]
04-19 21:12:46.758 DEBUG [AbstractService a] ⚙️︎  finish ActivityRecognitionService [eventCount: 0, sticky: false]
04-19 21:12:46.783 DEBUG [AbstractService a] 
  🎾  ActivityRecognitionService [eventCount: 1]
04-19 21:12:46.784 DEBUG [ActivityRecognitionService a] 
  🚘 ️DetectedActivity [type=UNKNOWN, confidence=40]
04-19 21:12:46.785 DEBUG [AbstractService a] ⚙️︎  finish ActivityRecognitionService [eventCount: 0, sticky: false]
04-19 21:12:46.842 DEBUG [AbstractService a] 
  🎾  ActivityRecognitionService [eventCount: 1]
04-19 21:12:46.844 INFO [ActivityRecognitionService a] 
╔═════════════════════════════════════════════
║ Motion Transition Result
╠═════════════════════════════════════════════
╟─ 🎾  ENTER: walking
╚═════════════════════════════════════════════
04-19 21:12:46.844 DEBUG [AbstractService a] ⚙️︎  finish ActivityRecognitionService [eventCount: 0, sticky: false]
04-19 21:12:46.890 DEBUG [AbstractService a] 
  🎾  ActivityRecognitionService [eventCount: 1]
04-19 21:12:46.891 INFO [ActivityRecognitionService a] 
╔═════════════════════════════════════════════
║ Motion Transition Result
╠═════════════════════════════════════════════
╟─ 🎾  ENTER: walking
╚═════════════════════════════════════════════
04-19 21:12:46.891 DEBUG [AbstractService a] ⚙️︎  finish ActivityRecognitionService [eventCount: 0, sticky: false]
04-19 21:12:47.149 DEBUG [AbstractService onDestroy] 
  🔴  ActivityRecognitionService destroyed
04-19 21:12:57.308 INFO [TSScheduleManager oneShot] 
  ⏰ Scheduled OneShot: TERMINATE_EVENT in 10000ms (jobID: -1708771588)
04-19 21:12:58.723 INFO [TSScheduleManager oneShot] 
  ⏰ Oneshot TERMINATE_EVENT is already pending
04-19 21:13:07.347 INFO [ScheduleEvent onOneShot] 
╔═════════════════════════════════════════════
║ ⏰ OneShot event fired: TERMINATE_EVENT
╠═════════════════════════════════════════════

04-19 21:13:07.348 DEBUG [TerminateEvent <init>] 
  ℹ️  TERMINATE_EVENT ignored (MainActivity is still active).

```

</details>

**Comment by christocracy** [comment]
How far did you travel?

**Comment by ma2kutty** [comment]
Thanks for your response. I have travelled 5 - 6  kilometers, I covered the same distance for IOS testing also.

**Comment by christocracy** [comment]
have you first adjusted your device settings according to http://dontkillmyapp.com?

**Comment by ma2kutty** [comment]
I have not done that, but after covering the distance. The app was still in background, I re-launched the app from background only.

Please see the app internal logs (in case it helps to the issue) corresponding to the library logs I pasted  in the issue. 

Context: the first API call is success because app logic takes current location and send to the backend. And from next update onwards it relies on  'BackgroundGeolocation.onLocation'. But as mentioned in the issue, we are getting location updates are not expected intervals and once 'BackgroundGeolocation.onLocation' is reached, we can see the logs for calling the API but response (error/failure) logs are not present. Instead immediately next 'onLocation' trigger logs are coming 

April 19th 2021, 8:52:21 pm : checkLocationTracks
April 19th 2021, 8:52:21 pm : initLocMgr::BackgroundGeolocation: initiating Version 37
April 19th 2021, 8:52:21 pm : LocMgr:: BGL BackgroundGeolocation is configured and ready
April 19th 2021, 8:52:23 pm : BackgroundGeolocation:: start is success
April 19th 2021, 8:52:24 pm : Got location update
April 19th 2021, 8:52:26 pm : Got location update
April 19th 2021, 8:52:38 pm : USER_AUTH_LOGIN_SUCCESS
April 19th 2021, 8:52:47 pm : startSendingLocationV1, calling checkLocationTracks
April 19th 2021, 8:52:47 pm : checkLocationTracks
April 19th 2021, 8:52:47 pm : initLocMgr::BackgroundGeolocation: initiating Version 37
April 19th 2021, 8:52:47 pm : LocMgr:: BGL BackgroundGeolocation is already configured and ready
April 19th 2021, 8:52:47 pm : calling getCurrentLocationV1
April 19th 2021, 8:52:47 pm : getCurrentLocationV1-calling API acceptedLoadLocationTrackingRequest
April 19th 2021, 8:52:48 pm : API call success
April 19th 2021, 9:12:33 pm : Got location update
April 19th 2021, 9:12:33 pm : calling API acceptedLoadLocationTrackingRequest
April 19th 2021, 9:12:34 pm : Got location update
April 19th 2021, 9:12:34 pm : calling API acceptedLoadLocationTrackingRequest
April 19th 2021, 9:12:35 pm : Got location update
April 19th 2021, 9:12:35 pm : calling API acceptedLoadLocationTrackingRequest

**Comment by christocracy** [comment]
The plugin is responsible for firing events, such as onLocation.  What happens there regarding http requests isn't the plugin's responsibility.

The plugin has an optional built-in http service.

**Comment by christocracy** [comment]
That being said, I'd certainly be using async/await with http requests in JavaScript, if I were you.

**Comment by ma2kutty** [comment]
Yes API part is our code base. But I pasted the same since the timestamps may help you to debug / verify the library logs. You can see the time stamps, onLocation is triggered back to back.

**Comment by christocracy** [comment]
Are you aware of `location.sample`.  See the api docs `onLocation`.

**Comment by RozumSystems** [comment]
We have the same problem. Application stop sending location when the screen is blocked. Sometime it is working for 2-3 hours, then wake up once an hour.

Plugin version: 4.0.3
Platform: Android
OS version: 11
Device manufacturer / model: Nokia 
RN: 0.64.0

.ready({
                desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
                distanceFilter: 1,
                stopTimeout: 1,
                stopOnTerminate: false,
                startOnBoot: true,
                heartbeatInterval: 60,
                foregroundService: true,
                allowIdenticalLocations: true,
                enableHeadless: true,
                locationTimeout: 30000,
                httpTimeout: 30000,

                url: `${server}/api/guard/tracking-duty/track-position`,
                headers: {[AUTHORIZATION_HEADER]: `${AUTHORIZATION_PREFIX}${auth.token!.access}`},
                autoSync: true,
                batchSync: false,
                method: 'PUT',
                httpRootProperty: '.',
                locationTemplate: '{"clientActionTime":"<%= timestamp %>","latitude":<%= latitude %>,"longitude":<%= longitude %>,"altitude":<%= altitude %>,"accuracy":<%= accuracy %>,"isMock":<%= mock %>}',

                maxRecordsToPersist: 1,

                reset: true,
                isMoving: true,
            }

**Comment by RozumSystems** [comment]
> 
> 
> Are you aware of `location.sample`? See the api docs `onLocation`.

We use it this way
```
private onLocation = async (location: any) => {
        const newLocation = JSON.stringify(location);
        //console.log('onLocation', location);
        this.props.updateLocation(newLocation);
    };
```

```
private onHeartbeat = async (event: HeartbeatEvent) => {
        await BackgroundGeolocation.changePace(true, () => {
            console.log("is tracking")
        });
        console.log('*!onHeartbeat!*');
        await BackgroundGeolocation.getCurrentPosition({
                samples: 1,
                persist: true
            },
            () => {},
            () => {}
        );
    };


```

It doesn't help, in 1-2 hours server stop receiving information, mostly in the night. 


Is there any technical problem that we would not receive any information and we need to re-write the whole application in pure java, not using react native?

**Comment by christocracy** [comment]
@RozumSystems this is not a react-native vs native problem.  The plugin *is* essentially a headless native app.

Have you applied http://dontkillmyapp.com?  One of my 12 test devices is a *Nokia TA-27* and it wouldn't work until I applied *dontkillmyapp*.

**Comment by RozumSystems** [comment]
@christocracy thanls for answer. We will try to do smth like this.

But, probably you can give an idea what device should work from box? We'd like to test it as prototype for our application.

**Comment by christocracy** [comment]
I always develop primarily on Nexus / Pixel devices.  These devices operate exactly as documented in the Android API.

I regularly field test on the following Android devices:

- Nexus 4 @ 4.4.4
- Nexus 5 @ 6.0.1
- Motorola Moto G @ 6.0.0
- Google Pixel @ 10
- Google Pixel 3a @ 11
- Samsung Galaxy S20 FE @ 11.0.0
- Samsung J @ 6.0.1
- Samsung A510 @ 8.0.0
- Huawei P20 Lite (ANE-LX3) @ 8.0.0
- XIAOMI MI A2 Lite @ 10.0.0
- Nokia TA-1027 @ 8.0.0
- OnePlus A5010 @ 9.0.0

**Comment by RozumSystems** [comment]
@christocracy Thanks for answer. We have test Nokia 4.2 - it is with Android One firmware.
We will try to check what processes we could kill.

`
255|PAN_sprout:/ $  pm disable-user com.evenwell.powersaving.g3

Exception occurred while executing 'disable-user':
java.lang.IllegalArgumentException: Unknown package: com.evenwell.powersaving.g3
        at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:21179)
        at com.android.server.pm.PackageManagerService.setApplicationEnabledSetting(PackageManagerService.java:21043)
        at com.android.server.pm.PackageManagerShellCommand.runSetEnabledSetting(PackageManagerShellCommand.java:2166)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:233)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21864)
        at android.os.Binder.shellCommand(Binder.java:929)
        at android.os.Binder.onTransact(Binder.java:813)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4637)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4370)
        at android.os.Binder.execTransactInternal(Binder.java:1159)
        at android.os.Binder.execTransact(Binder.java:1123)`
