### ISSUE TITLE
java.lang.ExceptionInInitializerError com.transistorsoft.locationmanager.http.HttpService.<init> (Play Store)

### ISSUE THREAD

**Issue by omerkok** [transistorsoft/react-native-background-geolocation#1389]
## Your Environment
* Plugin version: 3.10.0
* Platform: Android
* OS version: 11
* Device manufacturer / model: samsung note 10
* React Native version (`react-native -v`): 0.62.2
* Plugin config
export function courierLiveLocation() {
  return async (dispatch, getState) => {
    const { courierChangePace } = getState().CourierReducer;
    var BrandId = await getAsyncFunc('BrandId');
    var UserId = await getAsyncFunc('UserId');
    var NameSurname = await getAsyncFunc('NameSurname');

    BackgroundGeolocation.onLocation(
      (location) => {
        dispatch({
          type: COURIER_LAT_LNG_ISUPDATE,
          latitude: location.coords.latitude,
          longitude: location.coords.longitude,
        });
      },
      (error) => {},
    );

    BackgroundGeolocation.onHttp((response) => {});

    BackgroundGeolocation.onProviderChange((event) => {});

    BackgroundGeolocation.onEnabledChange((isEnabled) => {});

    await BackgroundGeolocation.ready(
      {
        // Geolocation Config
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        distanceFilter: 10,
        stopTimeout: 5,
        //showsBackgroundLocationIndicator: true,
        //preventSuspend: true,
        //heartbeatInterval: 60,
        //locationUpdateInterval: 6000,
        //Activity Recognition
        notification: {
          title: 'Konum',
          text: 'JaviPos konum izleme aktif.',
        },
        // Application config
        debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true, // <-- Auto start tracking when device is powered-up.
        autoSync: true,
        batchSync: false,
        httpTimeout: 5000,
        maxRecordsToPersist: 1,
        maxDaysToPersist: 1,
        enableHeadless: true,
        url: '******',
        httpRootProperty: 'data',
        extras: {
          PackageUserId: UserId,
          PackageUserName: NameSurname,
          BrandId: BrandId,
        },
        locationTemplate:
          '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"accuracy":<%= accuracy %>,"altitude":<%= altitude %>,"altitude_accuracy":<%= altitude_accuracy %>,"heading":<%= heading %>,"speed":<%= speed %>,"is_charging":<%= battery.is_charging %>,"level":<%= battery.level %>,"type":"<%= activity.type %>","uuid":"<%= uuid %>"}',
      },
      (state) => {
        console.log(
          '- BackgroundGeolocation is configured and ready: ',
          state.enabled,
        );
        if (!state.enabled) {
          BackgroundGeolocation.start(function() {
            console.log('- Start success');
            BackgroundGeolocation.changePace(courierChangePace);
          });
        }
      },
      (error) => {
        console.warn('BackgroundGeolocation error: ', error);
      },
    );
  };
}

## Expected Behavior
No crashes when downloading from Play Store. 

## Actual Behavior
The application started to crash for some users after the update I exited the play store. Looking at the Play Store, the reason for the crash looks like this: java.lang.ExceptionInInitializerError
com.transistorsoft.locationmanager.http.HttpService.<init>

Note: the only difference from my previous update is my pull from 29 to 30 target api below
  buildToolsVersion = "30.0.3"
         minSdkVersion = 17
         compileSdkVersion = 30
         targetSdkVersion = 30 

## Steps to Reproduce

1.
2.
3.
4.

## Context
I was trying to install new update from play store.

## Debug logs
There doesn't seem to be any problem with the simulator and on my physical device. I am writing to you because I cannot encounter the error on my own phone. 

I would be glad if you help. This is a big problem for users.

**Comment by christocracy** [comment]
Where's the stacktrace?

**Comment by omerkok** [comment]
I don't understand what you mean by stack trace.

**Comment by omerkok** [comment]
Can you explain what you want a little more clearly?

**Comment by omerkok** [comment]
The update I published under api level 30 works without any problems. Application does not open in api level 31 and 32.

**Comment by christocracy** [comment]
When an app crashes, there is stacktrace written to `$ adb logcat`.

The *first* thing you do when an app crashes is fetch the stacktrace.  Always.'

My primary development device is a *Pixel 3a* running *Android 12 beta* (ie: API 31).

**Comment by omerkok** [comment]
2021-09-16 17:02:01.199 476-476/? E/wifi_forwarder: qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:wififorward' service: Invalid argument
2021-09-16 17:02:01.199 476-476/? E/wifi_forwarder: RemoteConnection failed to initialize: RemoteConnection failed to open pipe
2021-09-16 17:02:06.947 220-224/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup4: Permission denied
2021-09-16 17:02:06.947 220-224/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup2: Permission denied
2021-09-16 17:02:06.947 220-224/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup0: Permission denied
2021-09-16 17:02:06.947 220-224/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup5: Permission denied
2021-09-16 17:02:06.947 220-224/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup3: Permission denied
2021-09-16 17:02:06.947 220-224/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup1: Permission denied
2021-09-16 17:02:07.260 16789-16789/com.javipos E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.javipos, PID: 16789
    java.lang.RuntimeException: Unable to create application com.javipos.MainApplication: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:90)
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238)
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281)
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
        at com.javipos.MainApplication.onCreate(MainApplication.java:90)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:80)
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238) 
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281) 
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87) 
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39) 
        at com.javipos.MainApplication.onCreate(MainApplication.java:90) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.lang.ExceptionInInitializerError
        at okhttp3.internal.platform.Platform.get(Platform.java:85)
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015)
        at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:132)
        at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:183)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:80) 
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238) 
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281) 
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87) 
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39) 
        at com.javipos.MainApplication.onCreate(MainApplication.java:90) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
        at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
        at okhttp3.internal.platform.Platform.get(Platform.java:85) 
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229) 
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015) 
        at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:132) 
        at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:183) 
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:80) 
        at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:238) 
        at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:281) 
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87) 
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39) 
        at com.javipos.MainApplication.onCreate(MainApplication.java:90) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2021-09-16 17:02:07.515 334-334/? E/Layer: [Surface(name=Task=63)/@0xf8045b2 - animation-leash#0] No local sync point found
2021-09-16 17:02:07.515 334-334/? E/Layer: [Surface(name=Task=1)/@0xcbdb3a4 - animation-leash#0] No local sync point found
2021-09-16 17:02:09.480 16824-16824/? E/d.process.acor: Not starting debugger since process cannot load the jdwp agent.

**Comment by omerkok** [comment]
Here are the errors logcat presents. I just brought the errors, is it necessary for the others?

**Comment by christocracy** [comment]
≥Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created

Googling, I find [this](https://stackoverflow.com/questions/60926425/java-lang-runtimeexception-requested-enabled-devsupportmanager-but-devsupportm)

>Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 30
at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)

This shows an invalid version for `okhttp`.  Post the following files:
- `android/build.gradle`
- `android/app/build.gradle`

**Comment by omerkok** [comment]
android/build.gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        googlePlayServicesLocationVersion = "17.0.0"  // Or higher.
        buildToolsVersion = "30.0.3"
        minSdkVersion = 17
        compileSdkVersion = 30
        targetSdkVersion = 30
        supportLibVersion = "29.0.3"
        appCompatVersion = "1.1.0"      // Or higher.  Required for new AndroidX compatibility.
    }
    repositories {
        google()
        jcenter()
         //maven {url 'http://developer.huawei.com/repo/'}
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.0.1')
        //classpath 'com.huawei.agconnect:agcp:1.3.1.300'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
        //maven {url 'http://developer.huawei.com/repo/'}
            maven {
                // Required for react-native-background-geolocation
                url("${project(':react-native-background-geolocation').projectDir}/libs")}
             maven {
                      // Required for react-native-background-fetch
                 url("${project(':react-native-background-fetch').projectDir}/libs")
             }
        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

**Comment by omerkok** [comment]
android/app/build.gradle
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation. If none specified and
 *   // "index.android.js" exists, it will be used. Otherwise "index.js" is
 *   // default. Can be overridden with ENTRY_FILE environment variable.
 *   entryFile: "index.android.js",
 *
 *   // https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
 *   bundleCommand: "ram-bundle",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"

Project background_geolocation = project(':react-native-background-geolocation')
apply from: "${background_geolocation.projectDir}/app.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.javipos"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        multiDexEnabled true
        missingDimensionStrategy 'react-native-camera', 'general'
        versionCode 20
        versionName "1.20"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            storeFile file(MYAPP_RELEASE_STORE_FILE)
            keyAlias MYAPP_RELEASE_KEY_ALIAS
            storePassword MYAPP_RELEASE_STORE_PASSWORD
            keyPassword MYAPP_RELEASE_KEY_PASSWORD
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }

    packagingOptions {
        pickFirst "lib/armeabi-v7a/libc++_shared.so"
        pickFirst "lib/arm64-v8a/libc++_shared.so"
        pickFirst "lib/x86/libc++_shared.so"
        pickFirst "lib/x86_64/libc++_shared.so"
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }

        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
    //implementation 'com.huawei.agconnect:agconnect-core:1.3.1.300'
    implementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    implementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    implementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        implementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
//apply plugin: 'com.huawei.agconnect'

**Comment by omerkok** [comment]
Hello, you asked me to share the build.gradle related to the problem, but you haven't answered yet. I would be grateful if you could help.

**Comment by christocracy** [comment]
Have you googled any of the errors I noted above?

**Comment by christocracy** [comment]
Also, background-geolocation uses `okhttp` as a dependency.  I would check what other plugins you're using that also might use `okhttp`.

**Comment by mikehardy** [comment]
`cd android && ./gradlew :app:dependencies` will chuck out the full list of who's using what at what version and why.
