### ISSUE TITLE
Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference

### ISSUE THREAD

**Issue by daanielcruz** [transistorsoft/react-native-background-geolocation#1449]
## Your Environment
* Plugin version:
* Platform: Android
* OS version: 
* Device manufacturer / model: AVD
* React Native version (`react-native -v`): 0.66.1
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 10,
    disableElasticity: Platform.OS !== 'ios',
    elasticityMultiplier: Platform.OS !== 'ios' ? 0 : 4,
    stopOnTerminate: false,
    enableHeadless: true,
    foregroundService: true,
    locationAuthorizationRequest: 'Always',
    backgroundPermissionRationale: {
      title:
        '',
      message:
        '',
      positiveAction: '',
      negativeAction: '',
    },
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    locationAuthorizationAlert: {
      titleWhenNotEnabled: 'Por favor, ative devidamente o acesso ao GPS!',
      titleWhenOff: 'Por favor, ative o acesso ao GPS',
      cancelButton: 'Cancelar',
      settingsButton: 'Configurações',
      instructions:
        '',
    },
    notification: {
      title: '',
      text: '',
      largeIcon: 'drawable/ic_launcher',
      smallIcon: 'drawable/ic_notification',
    },
    disableLocationAuthorizationAlert: false,
    fastestLocationUpdateInterval: 10000,
    locationTemplate:
      '{"latitude":<%= latitude %>,"longitude":<%= longitude %>}',
    httpRootProperty: '.',
    url: ''
    method: 'PUT',
    headers: {
      Authorization: `Bearer ${userToken}`,
    },
    debug: false,
  }
```

## Expected Behavior

Not to crash.

## Actual Behavior

Crashing.

## Steps to Reproduce

```javascript
BackgroundGeolocation.getState().then((status) => {
        if (!status.enabled) {
          BackgroundGeolocation.start().then(() => {
            BackgroundGeolocation.changePace(true);
          });
        }
      });
```

## Context

Start the tracking.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
FATAL EXCEPTION: main

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.loocal/com.transistorsoft.locationmanager.activity.TSLocationManagerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference

FATAL EXCEPTION: main
Process: com.loocal, PID: 8244
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.loocal/com.transistorsoft.locationmanager.activity.TSLocationManagerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
	at com.transistorsoft.locationmanager.config.TSBackgroundPermissionRationale.onStartActivity(Unknown Source:50)
	at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.requestBackgroundLocationPermission(Unknown Source:17)
	at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.execute(Unknown Source:63)
	at com.transistorsoft.locationmanager.activity.TSLocationManagerActivity.onCreate(Unknown Source:7)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
	... 11 more
```

</details>

**Comment by christocracy** [comment]
What was it?  I would have asked to see your build.gradle to see what compileSdkVersion, dependency versions.
