### ISSUE TITLE
TSLocationManager: java.lang.NumberFormatException: For input string: "∞"

### ISSUE THREAD

**Issue by adbs1** [transistorsoft/react-native-background-geolocation#1461]
## Your Environment
* Plugin version: "react-native-background-geolocation": "^4.4.4"
* Platform: iOS or Android
* OS version: Android 10
* Device manufacturer / model: Galaxy Note 9
* React Native version (`react-native -v`): 6.4.0
* Plugin config
```
{"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":0,"backgroundPermissionRationale":{"title":"Allow this app to access to this device's location in the background?","message":"To allow this app to record your tracks and give instant location finding, please enable {backgroundPermissionOptionLabel} location permission","positiveAction":"Change to {backgroundPermissionOptionLabel}","negativeAction":"Cancel"},"batchSync":false,"configUrl":"","debug":false,"deferTime":0,"desiredAccuracy":-1,"desiredOdometerAccuracy":25,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableStopDetection":false,"distanceFilter":3,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":3000,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.rnbackgroundgeolocation.HeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":true,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":3000,"locationsOrderDirection":"ASC","logLevel":0,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","smallIcon":"","largeIcon":"","priority":0,"sticky":false,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":false,"stationaryRadius":3,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":true,"stopTimeout":15,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":1,"odometer":97040.9765625,"isFirstBoot":false,"didLaunchInBackground":false,"didDeviceReboot":false}
```

## Actual Behavior
Testing the app with mocklocations often crashes the app with the same route loaded.

## Steps to Reproduce
1. Open the app
2. Open mocklocations and start a pre-recorded gpx route
3. The app runs for a few seconds then crashes

## Context
Test navigation via the mocklocations app

Happy to ignore it as it's only not real world usage, but understanding and handling the exception would be good if possible.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
03-22 09:38:29.244   980   980 I EdgeLightingManager: showForNotificationScreenOn : return false by isAvailableEdgeLighting.
03-22 09:38:29.244   980  1054 D API test: getContainerInfo: value is 
03-22 09:38:29.245 27543  1536 D TSLocationManager: [c.t.l.l.TSLocationManager onLocationResult] 
03-22 09:38:29.245 27543  1536 D TSLocationManager:   ℹ️  IGNORED: same as last location
03-22 09:38:29.245 27543 27543 W TSLocationManager: [c.t.l.service.TrackingService b] 
03-22 09:38:29.245 27543 27543 W TSLocationManager:   ⚠️  performStopDetection found mStoppedAtLocation == null
03-22 09:38:29.250 27543 27543 D TSLocationManager: [c.t.l.service.AbstractService a] ⚙️︎  finish TrackingService [eventCount: 0, sticky: true]
03-22 09:38:29.250  1814  1814 D Launcher.NotificationListener: onNotificationPosted : com.myapp number : 0 listener : null
03-22 09:38:29.252  1529  1599 V NotificationManager_FLP: Notification for foreground service is posted, 0|com.myapp|9942585|null|11112
03-22 09:38:29.252  3340  3340 D [AirCmd]_MediaControlStateMonitor: getActiveSessionsForUser : userId = 0
03-22 09:38:29.253  3340  3340 D [AirCmd]_MediaControlStateMonitor: isActive : media session list is empty
03-22 09:38:29.257 27543 32284 W com.myapp: Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (greylist, reflection, allowed)
03-22 09:38:29.257 27543 32284 W com.myapp: Accessing hidden method Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object; (greylist, reflection, allowed)
03-22 09:38:29.278   520   520 I SurfaceFlinger: SFWD update time=43753716781935
03-22 09:38:29.302 27543 32377 I TSLocationManager: [c.t.l.l.TSLocationManager removeLocationUpdates] 
03-22 09:38:29.302 27543 32377 I TSLocationManager:   🔴  Location-services: OFF
03-22 09:38:29.303 27543 32284 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
03-22 09:38:29.303 27543 32284 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
03-22 09:38:29.304   787   861 D EnterpriseController: netId is 0
03-22 09:38:29.304   787   861 E Netd    : getNetworkForDns: getNetId from enterpriseCtrl is netid 0
03-22 09:38:29.304   787   861 D DnsProxyListener: DNSDBG::dns addrinfo af 2 - 11112
03-22 09:38:29.306 27543 32377 E TSLocationManager: [c.t.l.a.BackgroundGeolocation$x0 uncaughtException] 
03-22 09:38:29.306 27543 32377 E TSLocationManager:   ‼️  Uncaught Exception: For input string: "∞"
03-22 09:38:29.306 27543 32377 E TSLocationManager: {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":0,"backgroundPermissionRationale":{"title":"Allow the app to access to this device's location in the background?","message":"To allow the app to record your tracks and give instant location finding, please enable {backgroundPermissionOptionLabel} location permission","positiveAction":"Change to {backgroundPermissionOptionLabel}","negativeAction":"Cancel"},"batchSync":false,"configUrl":"","debug":false,"deferTime":0,"desiredAccuracy":-1,"desiredOdometerAccuracy":25,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableStopDetection":false,"distanceFilter":3,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":3000,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.rnbackgroundgeolocation.HeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":true,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":3000,"locationsOrderDirection":"ASC","logLevel":0,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","smallIcon":"","largeIcon":"","priority":0,"sticky":false,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":false,"stationaryRadius":3,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":true,"stopTimeout":15,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":1,"odometer":97040.9765625,"isFirstBoot":false,"didLaunchInBackground":false,"didDeviceReboot":false}
03-22 09:38:29.306 27543 32377 E TSLocationManager: java.lang.NumberFormatException: For input string: "∞"
03-22 09:38:29.306 27543 32377 E TSLocationManager:    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
03-22 09:38:29.306 27543 32377 E TSLocationManager:    at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
03-22 09:38:29.306 27543 32377 E TSLocationManager:    at java.lang.Double.parseDouble(Double.java:538)
03-22 09:38:29.306 27543 32377 E TSLocationManager:    at java.lang.Double.valueOf(Double.java:502)
03-22 09:38:29.306 27543 32377 E TSLocationManager:    at com.transistorsoft.locationmanager.location.TSLocation.initialize(Unknown Source:262)
03-22 09:38:29.306 27543 32377 E TSLocationManager:    at com.transistorsoft.locationmanager.location.TSLocation.<init>(Unknown Source:25)
03-22 09:38:29.306 27543 32377 E TSLocationManager:    at com.transistorsoft.locationmanager.location.TSLocationManager.buildTSLocation(Unknown Source:14)
03-22 09:38:29.306 27543 32377 E TSLocationManager:    at com.transistorsoft.locationmanager.location.TSLocationManager.onLocationResult(Unknown Source:302)
03-22 09:38:29.306 27543 32377 E TSLocationManager:    at com.transistorsoft.locationmanager.service.TrackingService$a.run(Unknown Source:4)
03-22 09:38:29.306 27543 32377 E TSLocationManager:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-22 09:38:29.306 27543 32377 E TSLocationManager:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-22 09:38:29.306 27543 32377 E TSLocationManager:    at java.lang.Thread.run(Thread.java:919)
03-22 09:38:29.306  1529  1599 V GmsLocationManagerService_FLP: removeExpiredGmsRequests, count=0
03-22 09:38:29.306  1529  1599 E RequestManager_FLP: [FusedLocationApi] Location remove 2bd1ccf from com.myapp
03-22 09:38:29.307  1529  1599 V RequestManager_FLP: Remove in requestInfoList, 2bd1ccf / ListSize[GMS_FUSED]=0
03-22 09:38:29.309   980  1558 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
03-22 09:38:29.310   980  2265 D Debug   : !@DumpState : SHIP
03-22 09:38:29.310   980  2265 D Debug   : !@DumpState : debug level:0x4f4c
03-22 09:38:29.310   980  2265 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
03-22 09:38:29.312   980  2265 W ActivityManager: crash : com.myapp
03-22 09:38:29.313   980  2265 W ActivityTaskManager:   Force finishing activity com.myapp/.MainActivity
03-22 09:38:29.313   980  2265 V WindowManager: Prepare app transition: transit=TRANSIT_CRASHING_ACTIVITY_CLOSE mNextAppTransition=TRANSIT_UNSET alwaysKeepCurrent=false displayId=0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:6356 com.android.server.wm.DisplayContent.prepareAppTransition:6350 com.android.server.wm.ActivityStack.finishTopCrashedActivityLocked:4649 com.android.server.wm.RootActivityContainer.finishTopCrashedActivities:1217 com.android.server.wm.ActivityTaskManagerService$LocalService.finishTopCrashedActivities:9078 
03-22 09:38:29.314   980  2265 D ActivityTaskManager: updateMinimizedState: unknown notifyReason=2
03-22 09:38:29.314   980  2265 D InputDispatcher: Focused application set to (0): 253dd20
)
```

</details>

**Comment by christocracy** [comment]
It will be investigated but is likely something unusual being injected by the mock location provider that wouldn’t occur in the real world.

**Comment by adbs1** [comment]
Noted, thanks ! Will pass that on ...
