### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference

### ISSUE THREAD

**Issue by MostafaMareyAhmed** [transistorsoft/react-native-background-geolocation#1469]
## Your Environment
* Plugin version: 4.4.4
* Platform: Android 
* OS version: 11
* Device manufacturer / model: Redmi 5
* React Native version (`react-native -v`): 0.67.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      // Geolocation Config
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter: 500,
      // Activity Recognition
      stopTimeout: 5,
      // Application config
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true, // <-- Auto start tracking when device is powered-up.
      // HTTP / SQLite config
      url: `${ApiLink}/api/locations/`,
      batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.
      headers: {
        // <-- Optional HTTP headers
        Authorization: token,
      },
      locationAuthorizationRequest: 'Always',
      backgroundPermissionRationale: {
        title:
          "Allow CommuteSaver to access this device's location even when closed or not in use ?",
        message:
          'CommuteSaver collects location data to enable co2 emissions calculation even when the app is closed or not in use.',
      },
    }).then(state => {
      console.log(
        '[ready] BackgroundGeolocation is configured and ready to use',
      );
      BackgroundGeolocation.start();
    });
```

## Steps to Reproduce

1. build .aab file
2. open logcat
3. try to open app

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
2022-04-11 21:45:33.541 18210-18227/? E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.commutesaver, PID: 18210
    java.lang.ExceptionInInitializerError
        at ja.b.T(Unknown Source:0)
        at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.<init>(Unknown Source:29)
        at com.transistorsoft.rnbackgroundgeolocation.a.c(Unknown Source:7)
        at com.facebook.react.t.a(Unknown Source:41)
        at com.facebook.react.e.b(Unknown Source:30)
        at com.facebook.react.o.W(Unknown Source:35)
        at com.facebook.react.o.X(Unknown Source:54)
        at com.facebook.react.o.t(Unknown Source:36)
        at com.facebook.react.o.d(Unknown Source:0)
        at com.facebook.react.o$f.run(Unknown Source:68)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at ab.a.e(Unknown Source:27)
        at ja.b.<clinit>(Unknown Source:2)
        at ja.b.T(Unknown Source:0) 
        at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.<init>(Unknown Source:29) 
        at com.transistorsoft.rnbackgroundgeolocation.a.c(Unknown Source:7) 
        at com.facebook.react.t.a(Unknown Source:41) 
        at com.facebook.react.e.b(Unknown Source:30) 
        at com.facebook.react.o.W(Unknown Source:35) 
        at com.facebook.react.o.X(Unknown Source:54) 
        at com.facebook.react.o.t(Unknown Source:36) 
        at com.facebook.react.o.d(Unknown Source:0) 
        at com.facebook.react.o$f.run(Unknown Source:68) 
        at java.lang.Thread.run(Thread.java:764) 
```

</details>

**Comment by christocracy** [comment]
post your `android/build.gradle` and `android/app/build.gradle`.

**Comment by christocracy** [comment]
From your `android/app/build.gradle`

```gradle
/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = true
```

```
buildTypes {
        .
        .
        .        
        release {
             .
             .
             .            
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
```

See the [Android Setup Instructions](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-ANDROID-AUTO.md#proguard-config).  You missed a **required** step.

<img width="1048" alt="Screen Shot 2022-04-12 at 10 05 33 AM" src="https://user-images.githubusercontent.com/14999/162980665-8a0c829f-ab41-4b57-a9d5-bfc1baa0e117.png">
