### ISSUE TITLE
Scheduler seems not working on android

### ISSUE THREAD

**Issue by emmanuelfrancis** [transistorsoft/react-native-background-geolocation#1470]
## Your Environment
* Plugin version:4.4.4
* Platform: Android
* OS version: Android 11
* Device manufacturer / model: Nokia 5.3 
* React Native version (`react-native -v`): 0.66.3
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
	  schedule: [ '2-6 07:00-10:00 geofence' ],
      stopOnTerminate: false,
      startOnBoot: true,
      showsBackgroundLocationIndicator:true,
      locationAuthorizationRequest: 'Always',
      disableMotionActivityUpdates: true,
      activityType: BackgroundGeolocation.ACTIVITY_TYPE_OTHER,    
      geofenceModeHighAccuracy:true,
      scheduleUseAlarmManager: true,   

    }).then((state) => {  
      // Start the Scheduler
      console.log("ready state ", state)
      BackgroundGeolocation.startSchedule()
    }).catch(error => {
      console.log("- BackgroundGeolocation error: ", error);
});

unsubscribeOnSchedule = BackgroundGeolocation.onSchedule( async(state) => {
      let enabled = state.enabled;
      console.log("[onSchedule] - enabled? ", enabled);
});
    
    
```

## Expected Behavior
Expect every Monday to Friday at 7 AM onSchedule to be called.

## Actual Behavior
Not getting called on Monday. Debug log shows below
╔═════════════════════════════════════════════
║ 🎾  Scheduler ON
╠═════════════════════════════════════════════
╟─ Schedule[07:00-10:00, Days: [2, 3, 4, 5, 6], trackingMode: 0]
╚═════════════════════════════════════════════

  📅  Day #5: Searching schedule for alarms...

  📅  Day #5: Failed to find alarms on this day.  Trying tomorrow...

  📅  Day #6: Searching schedule for alarms...

  📅  Scheduled Alarm: ON at 07:00 on Friday

  ℹ️  Schedule with AlarmManager

## Steps to Reproduce

1. Installed the app on Friday afternoon after 10 AM
2. Put the app in the background.
3. On Monday expected to see a console log print for onSchedule
4. Nothing happened on Monday

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
Did you move around with the device during the scheduled "on time" or did you let it sit still?

**Comment by christocracy** [comment]
When testing, use LOG_LEVEL_VERBOSE (see api docs Config.logLevel).

Also use `debug: true`.

See wiki *Debugging*.

**Comment by emmanuelfrancis** [comment]
@christocracy do you suggest anything else to look into to check why the schedule is not getting started? 

My observation is that the schedule gets started for the current day only if I set it for '2-6 07:00-10:00 geofence' and installed the app at say 6 AM, then it works fine and starts at 7:00 AM, but does not start on next day.

**Comment by christocracy** [comment]
Ensure your device settings are configured according to https://dontkillmyapp.com

**Comment by emmanuelfrancis** [comment]
@christocracy I am trying to log.
I have setup
logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
debug:true,

BackgroundGeolocation.logger.emailLog('myemail@example.com').then((success) => {
        console.log('[emailLog] SUCCESS');
      }).catch((error) => {
        console.log('[emailLog] ERROR: ', error);
      });

It crashes with error [emailLog] ERROR:  Failed to read log database.

**Comment by christocracy** [comment]
Call it when .ready() resolves

**Comment by emmanuelfrancis** [comment]
Thanks, I am calling it completely from a separate screen. .ready() is app.js
 
    BackgroundGeolocation.ready({
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
      stopOnTerminate: false,
      startOnBoot: true,
      showsBackgroundLocationIndicator:true,
      locationAuthorizationRequest: 'Always',
      disableMotionActivityUpdates: true,
      activityType: BackgroundGeolocation.ACTIVITY_TYPE_OTHER,    
      geofenceModeHighAccuracy:true,
      scheduleUseAlarmManager: true,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      debug:true
    }).then((state) => {  
      console.log("ready state ", state)
    }).catch(error => {
      console.log("- BackgroundGeolocation error: ", error);
    });

On another UI screen on button click called :
BackgroundGeolocation.logger.emailLog('[myemail@example.com](mailto:myemail@example.com)').then((success) => {
console.log('[emailLog] SUCCESS');
}).catch((error) => {
console.log('[emailLog] ERROR: ', error);
});

It crashes with error [emailLog] ERROR: Failed to read log database.

**Comment by christocracy** [comment]
Capture the entire stacktrace in `$ adb logcat`

**Comment by emmanuelfrancis** [comment]
Thanks, @christocracy I will send you logs. Could you please let me know what could be the reason for this exception?

04-19 08:00:01.918  1931  5862 E AppOps  : java.lang.SecurityException: Specified package com.transistorsoft.backgroundgeolocation.react under uid 10526 but it is really -1
04-19 08:00:01.918  1931  5862 E AppOps  : 	at com.android.server.appop.AppOpsService.verifyAndGetBypass(AppOpsService.java:3874)
04-19 08:00:01.918  1931  5862 E AppOps  : 	at com.android.server.appop.AppOpsService.checkOperationUnchecked(AppOpsService.java:2865)
04-19 08:00:01.918  1931  5862 E AppOps  : 	at com.android.server.appop.AppOpsService.checkOperationImpl(AppOpsService.java:2848)
04-19 08:00:01.918  1931  5862 E AppOps  : 	at com.android.server.appop.AppOpsService.checkOperationInternal(AppOpsService.java:2835)
04-19 08:00:01.918  1931  5862 E AppOps  : 	at com.android.server.appop.AppOpsService.checkOperation(AppOpsService.java:2826)
04-19 08:00:01.918  1931  5862 E AppOps  : 	at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:425)
04-19 08:00:01.918  1931  5862 E AppOps  : 	at android.os.Binder.execTransactInternal(Binder.java:1154)
04-19 08:00:01.918  1931  5862 E AppOps  : 	at android.os.Binder.execTransact(Binder.java:1123)

**Comment by christocracy** [comment]
> Specified package com.transistorsoft.backgroundgeolocation.react 

Why do you have a reference to the SampleApp applicationId in your stacktrace?

**Comment by emmanuelfrancis** [comment]
Oh, maybe it's from the sample app (https://play.google.com/store/apps/details?id=com.transistorsoft.backgroundgeolocation.react) I downloaded from play store giving error.

There are no references of sample app.

 <service android:name="com.transistorsoft.locationmanager.service.TrackingService" android:foregroundServiceType="location" />
       <service android:name="com.transistorsoft.locationmanager.service.LocationRequestService" android:foregroundServiceType="location" />

      <meta-data 
        android:name="com.transistorsoft.locationmanager.license" 
        android:value="our licensee key" 
      />

**Comment by christocracy** [comment]
Did you purchase a key?

**Comment by emmanuelfrancis** [comment]
Yes, we have a licensee key. Please let me know if I would have to directly email you.

**Comment by christocracy** [comment]
I don't need your key.

Show me your android/app/build.gradle

**Comment by emmanuelfrancis** [comment]
Attached here, thank you
[build.gradle.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/8515244/build.gradle.txt)

**Comment by christocracy** [comment]
I don't see anything wrong in your build.gradle.

I suggest you remove the SampleApp and attempt to capture the stacktrace in `adb logcat` once again.

**Comment by emmanuelfrancis** [comment]
I have a schedule set for tomorrow, I will be testing it and will send you logs. Thanks.

**Comment by emmanuelfrancis** [comment]
@christocracy Please find the attached logs. 
App package name is changed with com.geofence.app
Schedule set was '2-6 07:00-10:00 geofence'


[logcatNokia-04-21-2.log](https://github.com/transistorsoft/react-native-background-geolocation/files/8531458/logcatNokia-04-21-2.log)

**Comment by christocracy** [comment]
Show me your `AndroidManifest.xml` (with sensitive information **redacted**, such as license keys / api keys)

**Comment by emmanuelfrancis** [comment]
Attached AndroidManifest.xml
[AndroidManifest.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/8531697/AndroidManifest.txt)
l

**Comment by christocracy** [comment]
I'm testing a `schedule` on *Pixel 3a @ 11*, configured to start every 2 minutes.  I have no issue with scheduler running in the background.

However, from your logs I see this:
```
04-21 08:52:48.873  1706  3884 W ActivityManager: Foreground service started from background can not have location/camera/microphone access: service com.geofence.app/com.transistorsoft.locationmanager.service.GeofencingService
```

In your `AndroidManifest.xml`, beneath this line

```xml
<service android:name="com.transistorsoft.locationmanager.service.LocationRequestService" android:foregroundServiceType="location" />
```

Add this line:
```xml
<service android:name="com.transistorsoft.locationmanager.service.GeofencingService" android:foregroundServiceType="location" />
```

**Comment by christocracy** [comment]
> is this flag "GeofencingService"

No.  Like I said, it works perfectly in my Pixel 3a without requiring that.  It's most likely something device-specific (if it fixes your issue).

**Comment by christocracy** [comment]
I have never heard of your issue.

**Comment by emmanuelfrancis** [comment]
Hi, @christocracy I tried on Samsung too, but same behavior. Did you get a chance to check the logs?
