### ISSUE TITLE
Execution failed for task ':app:processDebugMainManifest'.

### ISSUE THREAD

**Issue by Joshig99** [transistorsoft/react-native-background-geolocation#1502]
I'm getting issue when add this package to my project in android 

BUILD FAILED in 20s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
/Users/var/MyProjects/reactnativecli/installapp/android/app/src/main/AndroidManifest.xml Error:
        Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s

    at makeError (/Users/var/MyProjects/reactnativecli/installapp/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /Users/var/MyProjects/reactnativecli/installapp/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (/Users/var/MyProjects/reactnativecli/installapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/var/MyProjects/reactnativecli/installapp/node_modules/@react-native-community/cli/build/index.js:186:9)

## Your Environment
* Plugin version: "^4.8.0"
* Platform: iOS or Android:Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):0.64.0
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  **android/build.gradle**

buildscript {
    //ext.kotlin_version = '1.6.0-RC2'
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "20.1.5948944"
        kotlinVersion = "1.4.32"
        kotlin_version = '1.4.32'
        dokka_version = '0.10.1'
        appCompatVersion = "1.1.0"      // Or higher.  Required for new AndroidX compatibility.
        googlePlayServicesLocationVersion = "19.0.1"  // Or higher.
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:4.2.1')
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
       // classpath "org.jetbrains.dokka:dokka-gradle-plugin:${version_dokka}"
        classpath "org.jetbrains.dokka:dokka-gradle-plugin:$dokka_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
          classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
       maven {
         // react-native-background-fetch
          url("${project(':react-native-background-fetch').projectDir}/libs")
        }
            maven {
          // Required for react-native-background-geolocation
          url("${project(':react-native-background-geolocation').projectDir}/libs")
      }
        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

```

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
This is not related to the plugin.  Post your `AndroidManifest.xml`

**Comment by christocracy** [comment]
Unrelated:  references to *deprecated* `jcenter()` should be replaced with `mavenCentral()` in all gradle files.

**Comment by Joshig99** [comment]
> Unrelated: references to _deprecated_ `jcenter()` should be replaced with `mavenCentral()` in all gradle files.

I replaced but getting same error

**Comment by christocracy** [comment]
Also see [here](https://developer.android.com/about/versions/12/behavior-changes-12) from android developer docs.

The plugin's own `AndroidManifest` has correctly configured `android:exported` for all its required elements for over a year.

**Comment by christocracy** [comment]
The plugin does not use or require *Kotlin*.

**Comment by christocracy** [comment]
Google your `Flipper` issues.  The plugin has nothing to do with `Flipper`.

**Comment by Joshig99** [comment]
> The plugin does not use or require _Kotlin_.

Ok thanks, please let me ask one question

I want to send user current location details to server for every 15 min even the app in foreground/background/terminated.
i'm trying to setup `react-native-background-fetch` to run the task for every 15 min even app in foreground/background/terminated ,  do i need `react-native -background-geolocation` to get the current location details when the app in background/terminated or can i use any community package to get current location

**Comment by christocracy** [comment]
> or can i use any community package to get current location

I have no idea.  I've never used the "community package".
