### ISSUE TITLE
Changes to locationTemplate do not appear to be correctly applied.

### ISSUE THREAD

**Issue by papaschmidt** [transistorsoft/react-native-background-geolocation#1527]
## Your Environment
* Plugin version: 4.8.2
* Platform: Android (same issue happens on iOS too)
* OS version: 11
* Device manufacturer / model: Pixel 4
* React Native version (`react-native -v`): 0.66.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
    reset: true,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
    debug: false,
    logLevel: __DEV__
      ? BackgroundGeolocation.LOG_LEVEL_VERBOSE
      : BackgroundGeolocation.LOG_LEVEL_OFF,
    stopOnTerminate: false,
    enableHeadless: true,
    foregroundService: true,
    disableLocationAuthorizationAlert: true,
    backgroundPermissionRationale: utils.en.backgroundPermissionRationale,
    httpRootProperty: ".",
    headers: {
      authorization: `Bearer ${authToken}`,
    },
  }
```

## Expected Behavior

Plugin should successfully apply new `locationTemplate` configuration via `setConfig()`

## Actual Behavior

Plugin does not seem to apply the newly passed `locationTemplate` correctly via `setConfig()`.  Server response returns 500.  Upon further investigation, we have discovered that what is being sent by the plugin is the default location schema, so it appears like the locationTemplate we passed in is not being applied.

## Steps to Reproduce

1.  Provide a configuration to `BackgroundGeolocation.ready()` that does not include an initially defined `locationTemplate` and `url`.  Example is configuration given above.
2.  The app should programmatically call `setConfig()` with `url` and `locationTemplate` passed in.
```typescript
BackgroundGeolocation.setConfig({
        url: Config.API_URL,
        locationTemplate: `{ "operationName": "TrackPath", "query": "mutation TrackPath($input: TrackPathInput!) { trackPath(input: $input) { data { lat lng } } }", "variables": { "input": { "lat": <%= latitude %>, "lng": <%= longitude %>, "Id": "${Id}" } } }`,
      }).then(state => {
        console.info("[setConfig Change] - Success: ", state);
      },state => {
        console.info("[setConfig Change] - Failed: ", state);
      });
```
3.  Watch the HTTP service fire off a POST due to an onLocation event and witness error due to locationTemplate apparently not being applied.

Example)
Screenshot showing what backend is receiving after `locationTemplate` is "applied".  It just sends the default location schema.
![image](https://user-images.githubusercontent.com/79602911/186511967-ea916d1d-43e3-4a87-a343-79095260854f.png)

## Context

The provided Configuration above is our initial configuration provided with the app.  When the user is ready to start a commute, we call `BackgroundGeolocation.setConfig()` with the provided `url` and `locationTemplate`.  The following first (and subsequent) HTTP POST(s) will return a 500.  This is because we end up only sending the default location schema to the backend.

We use GraphQL endpoint for our calls. Reproducible steps show an example of our locationTemplate.

The interesting observation that we have made is that if we take the _exact same_ `locationTemplate` and `url` above and provide it with the initial configuration that it will work correctly and any subsequent `setConfig()` calls with an updated `locationTemplate` (it is just a different id being passed in in the id input field that changes) will also be successfully applied.  

It just does not seem to apply correctly if you do not have one defined initially and attempt to define one later on with `setConfig()`

## Debug logs

<details><summary>Logs</summary>

-Android: $ adb logcat -s TSLocationManager logs
``` <!-- Syntax highlighting:  DO NOT REMOVE -->
08-24 09:44:40.449 15817 15817 I TSLocationManager: [c.t.l.u.BackgroundTaskManager$Task start] ⏳ startBackgroundTask: 1
08-24 09:44:40.457 15817 15908 D TSLocationManager: [c.t.l.data.sqlite.b first] 
08-24 09:44:40.457 15817 15908 D TSLocationManager:   ✅  Locked 1 records
08-24 09:44:40.457 15817 15908 I TSLocationManager: [c.t.l.http.HttpService a] 
08-24 09:44:40.457 15817 15908 I TSLocationManager:   🔵  HTTP POST: b7a622db-4a83-441b-810a-3dd53ec02f8d
08-24 09:44:41.351 15817 16345 W TSLocationManager: [c.t.l.http.HttpService$h onResponse] 
08-24 09:44:41.351 15817 16345 W TSLocationManager:   ⚠️  Response: 500, 
08-24 09:44:41.365 15817 16345 D TSLocationManager: [c.t.l.data.sqlite.b unlock] 
08-24 09:44:41.365 15817 16345 D TSLocationManager:   ✅  UNLOCKED: b7a622db-4a83-441b-810a-3dd53ec02f8d
08-24 09:44:41.365 15817 16345 I TSLocationManager: [c.t.l.u.BackgroundTaskManager$Task stop] ⏳ stopBackgroundTask: 1
08-24 09:44:41.365 15817 16345 D TSLocationManager: [c.t.l.service.AbstractService finish] ⚙️︎  finish BackgroundTaskService [eventCount: 0, sticky: false]
08-24 09:44:41.385 15817 15817 D TSLocationManager: [c.t.l.service.AbstractService onDestroy] 
```
Console output with successful setConfig call (and config) and the onHTTPResponse
```<!-- Syntax highlighting:  DO NOT REMOVE -->
 INFO  [setConfig Change] - Success:  {"activityRecognitionInterval": 10000, "allowIdenticalLocations": false, "authorization": {}, "autoSync": true, "autoSyncThreshold": 0, "backgroundPermissionRationale": {"message": "In order to track your activity in the background, please enable “{backgroundPermissionOptionLabel}” location permission.", "negativeAction": "Cancel", "positiveAction": "Change to “{backgroundPermissionOptionLabel}”", "title": "Allow {applicationName} to access to this device's location in the background?"}, "batchSync": false, "configUrl": "", "debug": false, "deferTime": 0, "desiredAccuracy": -2, "desiredOdometerAccuracy": 100, "didDeviceReboot": false, "didLaunchInBackground": false, "disableAutoSyncOnCellular": false, "disableElasticity": false, "disableLocationAuthorizationAlert": true, "disableMotionActivityUpdates": false, "disableStopDetection": false, "distanceFilter": 10, "elasticityMultiplier": 1, "enableHeadless": true, "enableTimestampMeta": false, "enabled": true, "extras": {"activeId": "87ad4f99-3df5-44a8-8c78-9b591d9bf70d"}, "fastestLocationUpdateInterval": -1, "foregroundService": true, "geofenceInitialTriggerEntry": true, "geofenceModeHighAccuracy": false, "geofenceProximityRadius": 1000, "geofenceTemplate": "", "headers": {"authorization": "Bearer REMOVED_FOR_GITHUB_ISSUE"}, "headlessJobService": "com.transistorsoft.rnbackgroundgeolocation.HeadlessTask", "heartbeatInterval": -1, "httpRootProperty": ".", "httpTimeout": 60000, "isFirstBoot": true, "isMoving": true, "locationAuthorizationRequest": "Always", "locationTemplate": "{ \"operationName\": \"TrackPath\", \"query\": \"mutation TrackPath($input: TrackPathInput!) { trackPath(input: $input) { data { lat lng } } }\", \"variables\": { \"input\": { \"lat\": <%= latitude %>, \"lng\": <%= longitude %>, \"Id\": \"87ad4f99-3df5-44a8-8c78-9b591d9bf70d\" } } }", "locationTimeout": 60, "locationUpdateInterval": 1000, "locationsOrderDirection": "ASC", "logLevel": 5, "logMaxDays": 3, "maxBatchSize": -1, "maxDaysToPersist": 1, "maxRecordsToPersist": -1, "method": "POST", "minimumActivityRecognitionConfidence": 75, "motionTriggerDelay": 0, "notification": {"actions": [], "channelName": "TSLocationManager", "color": "", "largeIcon": "", "layout": "", "priority": 0, "smallIcon": "", "sticky": false, "strings": {}, "text": "Location Service activated", "title": ""}, "odometer": 29.96030044555664, "params": {}, "persist": true, "persistMode": 2, "schedule": [], "scheduleUseAlarmManager": false, "schedulerEnabled": false, "speedJumpFilter": 300, "startOnBoot": false, "stationaryRadius": 25, "stopAfterElapsedMinutes": 0, "stopOnStationary": false, "stopOnTerminate": false, "stopTimeout": 5, "trackingMode": 1, "triggerActivities": "in_vehicle, on_bicycle, on_foot, running, walking", "url": "REMOVED_FOR_GITHUB_ISSUE", "useSignificantChangesOnly": false}
 INFO  [BackgroundGeolocation] HTTP Reponse:  false 500 {"status":500,"stack":"** (ErlangError) Erlang error: FunctionClauseError\n    (elixir 1.12.3) lib/regex.ex:321: Regex.run(~r/mutation/i, nil, [])\n    (abc_app 22.8.24+7b5f459) lib/web/api/controllers/graphql_controller.ex:30: ABC.Web.API.GraphQLController.create/2\n    (abc_app 22.8.24+7b5f459) lib/web/api/controllers/graphql_controller.ex:1: ABC.Web.API.GraphQLController.action/2\n    (abc_app 22.8.24+7b5f459) lib/web/api/controllers/graphql_controller.ex:1: ABC.Web.API.GraphQLController.phoenix_controller_pipeline/2\n    (phoenix 1.6.9) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2\n    (phoenix 1.6.9) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2\n    (phoenix 1.6.9) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2\n    (abc_app 22.8.24+7b5f459) lib/web/endpoint.ex:1: ABC.Web.Endpoint.plug_builder_call/2\n","kind":"Internal Server Error","error":"Elixir.FunctionClauseError"}
```

</details>

**Comment by blwinters** [comment]
This has been open quite a while and I may have a related issue with the `extras` property. Any updates on this?

**Comment by christocracy** [comment]
These sorts of issue are always related to existing records recorded before the locationTemplate was applied.

the plugin does not re-render the template for existing records in the plug-in’s database.

I suggest you create a new issue.
