### ISSUE TITLE
ForegroundServiceDidNotStartInTimeException

### ISSUE THREAD

**Issue by cedricjacobs** [transistorsoft/react-native-background-geolocation#1600]
## Your Environment
* Plugin version: 4.9.3
* Platform: Android
* OS version: 12
* Device manufacturer / model: Samsung; models: Galaxy Xcover 5, Galaxy A12
* React Native version (`react-native -v`): 0.70.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      foregroundService: true,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter,
      activityType: BackgroundGeolocation.ACTIVITY_TYPE_OTHER_NAVIGATION,
      allowIdenticalLocations: true,
      disableMotionActivityUpdates: true,
      disableStopDetection: true,
      stopOnTerminate: false,
      pausesLocationUpdatesAutomatically: false,
      stopOnStationary: true,
      stopTimeout: 5,
      locationUpdateInterval: 30000,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      startOnBoot: false,
      httpRootProperty: '.',
      batchSync: false,
      autoSync: true,
      locationTemplate: '{}',
      locationAuthorizationRequest: 'Always',
      locationAuthorizationAlert: {
        titleWhenNotEnabled: 'Location Services not enabled',
        titleWhenOff: 'Location Services turned off',
        instructions: "You must enable 'Always' in location Services",
        cancelButton: 'Cancel',
        settingsButton: 'Settings',
      },
      backgroundPermissionRationale: {
        title: "Allow {applicationName} to access to this device's location in the background?",
        message:
          'In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission',
        positiveAction: 'Change to {backgroundPermissionOptionLabel}',
        negativeAction: 'Cancel',
      },
      maxRecordsToPersist: 1,
    }
```

## Expected Behavior
We would like to see this not happening 

## Actual Behavior
There crashes reported by some of our users where it reports ``Fatal Exception: android.app.ForegroundServiceDidNotStartInTimeException``

## Steps to Reproduce
ATM it is unclear how to reproduce

## Context
Tracking background locations

## Debug logs
ATM not possible to deliver as we can't reproduce

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
Fatal Exception: android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{7849c0e u0 com.triptomatic.app/com.transistorsoft.locationmanager.service.BackgroundTaskService}
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2147)
       at android.app.ActivityThread.access$2800(ActivityThread.java:310)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2376)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

</details>

**Comment by christocracy** [comment]
This has been posted dozens of times before.  Please *search* before posting.

duplicate #976
