### ISSUE TITLE
App crashes when trying to upgrade to Android SDK 31

### ISSUE THREAD

**Issue by ps-danielk** [transistorsoft/react-native-background-geolocation#1617]
## Your Environment
* Plugin version: 3.10.0
* Platform: Android
* OS version: 12.0
* Device manufacturer / model: Emulator - Pixel 6 Pro
* React Native version (`react-native -v`): 0.61.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
export const requestAndroidPermission = async (enableHighAccuracy = false) => {
    // Note: Rationale only shows if user has previously denied the request or if the user manually turned off the permission

    const { PERMISSIONS, RESULTS } = PermissionsAndroid;
    const granted = await PermissionsAndroid.request(
        enableHighAccuracy ? PERMISSIONS.ACCESS_FINE_LOCATION : PERMISSIONS.ACCESS_COARSE_LOCATION,
        {
            title: 'Background Location Access',
            message:
                'This app collects location data to enable technician enroute tracking and address vicinity alerts even when the app is closed or not in use.',
            buttonPositive: 'OK',
        }
    );

    if (granted !== RESULTS.GRANTED) {
        return false;
    }

    return true;
};
```

## Expected Behavior
App requests location permissions upon start up, user proceeds to use the app
## Actual Behavior
App crashes
## Steps to Reproduce

1.Install the application
2.Upon startup, device requests permission to access the users location
3. Once accepted, app crashes
4. Trying to start the app again, app crashes

## Context

Start the app with necessary location permissions
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
Uncaught Exception: com.fahw_mobileapp: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
    {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":0,"backgroundPermissionRationale":{"title":"Background Location Access","message":"This app collects location data to enable technician enroute tracking and address vicinity alerts even when the app is closed or not in use.","positiveAction":"Change to \"{backgroundPermissionOptionLabel}\"","negativeAction":"Cancel"},"batchSync":false,"configUrl":"","debug":false,"deferTime":0,"desiredAccuracy":-1,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":true,"disableStopDetection":false,"distanceFilter":10,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":-1,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{"X-FOO":"bar"},"headlessJobService":"com.transistorsoft.rnbackgroundgeolocation.HeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"Always","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":5,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","smallIcon":"","largeIcon":"","priority":0,"sticky":false,"strings":{},"actions":[]},"params":{"auth_token":"maybe_your_server_authenticates_via_token_YES?"},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":true,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":1,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"http:\/\/yourserver.com\/locations","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":1,"odometer":0,"isFirstBoot":false,"didLaunchInBackground":false}
    java.lang.IllegalArgumentException: com.fahw_mobileapp: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:724)
        at android.app.PendingIntent.getForegroundService(PendingIntent.java:716)
        at com.transistorsoft.locationmanager.service.ActivityRecognitionService.a(Unknown Source:25)
        at com.transistorsoft.locationmanager.service.ActivityRecognitionService.b(Unknown Source:78)
        at com.transistorsoft.locationmanager.service.TrackingService.a(Unknown Source:29)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$z0.run(Unknown Source:165)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)

```

</details>

**Comment by christocracy** [comment]
> Plugin version: 3.10.0

You’re using a version from two years ago, before api 31 existed.  See the CHANGELOG and update to latest version, which is compiled with api 33.
