### ISSUE TITLE
ConcurrentModificationException java.util.ArrayList$Itr in next

### ISSUE THREAD

**Issue by macielrsf** [transistorsoft/react-native-background-geolocation#1647]
## Your Environment
* Plugin version: 4.10.0
* Platform: Android
* OS version: macOS 13.2.1
* Device manufacturer / model: Mac mini (Chip Apple M1)
* React Native version (`react-native -v`): 0.71.2
* 
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
        const config = {
            notification: {
                title: 'Company',
                text: 'Executando',
            },
            disableMotionActivityUpdates: true,
            desiredAccuracy: Platform.select({
                ios: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
                android: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            }),
            debug: __DEV__ ? true : false,
            logLevel: __DEV__
                ? BackgroundGeolocation.LOG_LEVEL_VERBOSE
                : BackgroundGeolocation.LOG_LEVEL_OFF,
            stopOnTerminate: false,
            startOnBoot: false,
            url,
            batchSync: true,
            autoSync: true,
            autoSyncThreshold: 5,
            maxBatchSize: 100,
            distanceFilter: Platform.select({ios: 10, android: 20}),
            stopTimeout: 5,
            locationTemplate:
                '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"velocidade":<%= speed %>,"time":"<%= timestamp %>","id":"<%= uuid %>","nivel_bateria": <%= battery.level %>}',
            headers: {
                accept: 'application/json',
                'content-type': 'application/json',
                authorization: httpClient.defaults.headers.common.Authorization,
            },
            params: {
                timezone: 'America/Recife',
            },
            extras: {
                modelo_dispositivo,
                fabricante,
            },
            //iOS Options
            showsBackgroundLocationIndicator: true,
            stationaryRadius: 10,
            heartbeatInterval: Platform.select({ios: 10, android: 60}),
            preventSuspend: Platform.select({ios: true, android: false}),
            activityType:
                BackgroundGeolocation.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION,
        };
```

## Expected Behavior

None bug reported on Sentry 

## Actual Behavior

Native Exception (Android): ConcurrentModificationException java.util.ArrayList$Itr in next

Stack Trace:
java.util.ConcurrentModificationException: null
    at java.util.ArrayList$Itr.next(ArrayList.java:860)
    at com.transistorsoft.locationmanager.util.c$j.onPermissionGranted
    at com.intentfilter.androidpermissions.PermissionHandler.checkPermissions(PermissionHandler.java:44)
    at com.intentfilter.androidpermissions.PermissionManager.checkPermissions(PermissionManager.java:55)
    at com.transistorsoft.locationmanager.util.c$j.run
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:236)
    at android.app.ActivityThread.main(ActivityThread.java:7912)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

## Context

Apparently the crash happens after our users have accepted background geolocation permissions. On Sentry, the most reports are from Android 10 and 11 in Xiaomi devices mainly (Redmi Note 8, Redmi Note 9, Redmi Prime 9S, Redmi Note 9S, Redmi Note 11, etc)

Complete Issue link: https://hubsoftbrasil.sentry.io/share/issue/ae5d1d147c7241eea763fd7b9643fa0a/

**Comment by christocracy** [comment]
I do not have any explanation for this error.  The plugin code is properly interacting with a `static` `List` within `@synchronized` blocks.

Show me your code.

**Comment by macielrsf** [comment]
Below, it's my component where I control the "start/stop" of your service:
  
`import React, {useCallback, Fragment, useEffect, useState} from 'react';
import DeviceInfo from 'react-native-device-info';
import NetInfo from '@react-native-community/netinfo';
import {connect} from 'react-redux';
import BackgroundGeolocation from 'react-native-background-geolocation';
import moment from 'moment';
import {useDispatch} from 'react-redux';
import {AppState, Platform} from 'react-native';

import showToast from '~/services/Toast';
import Unauthorized from '~/services/Unauthorized';

import httpClient from '~/HttpClient';

import * as types from '~/constants/ActionTypes';

import {
    modificaNivelBateria,
    modificaDispositivoInfo,
    modificaStatusConexao,
} from '~/actions/DeviceInfoActions';

import useSyncGeolocation from '~/hooks/sync_geolocation';
import {checkRequest} from '~/hooks/sync_geolocation/Useful';

const HubsoftBackgroundGeolocation = ({
    navigation,
    nivel_bateria,
    modelo_dispositivo,
    fabricante,
    modificaNivelBateria,
    modificaDispositivoInfo,
}) => {
    const dispatch = useDispatch();
    const handleSync = useSyncGeolocation();

    const [enabled, setEnabled] = useState(false);

    useEffect(() => {
        // Força a captura de localizações
        if ((__DEV__ && enabled) || (enabled && Platform.OS === 'ios')) {
            BackgroundGeolocation.changePace(true)
                .then(success => console.log('changePace(true):', success))
                .catch(err => console.error('changePace(false):', err));
        }
    }, [enabled]);

    useEffect(() => {
        /// 1.  Subscribe to events.
        const onLocation = BackgroundGeolocation.onLocation(location => {
            console.log('[onLocation]');
            _modificaDeviceInfo();
        });

        const config = {
            notification: {
                title: 'Hubsoft',
                text: 'Executando',
            },
            disableMotionActivityUpdates: true,
            desiredAccuracy: Platform.select({
                ios: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
                android: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
            }),
            debug: __DEV__ ? true : false,
            logLevel: __DEV__
                ? BackgroundGeolocation.LOG_LEVEL_VERBOSE
                : BackgroundGeolocation.LOG_LEVEL_OFF,
            stopOnTerminate: false,
            startOnBoot: false,
            url: `${httpClient.defaults.baseURL}api/v1/app/geolocalizacao/usuario`,
            batchSync: true,
            autoSync: true,
            autoSyncThreshold: 5,
            maxBatchSize: 100,
            distanceFilter: Platform.select({ios: 10, android: 20}),
            stopTimeout: 5,
            locationTemplate:
                '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"velocidade":<%= speed %>,"time":"<%= timestamp %>","id":"<%= uuid %>","nivel_bateria": <%= battery.level %>}',
            headers: {
                accept: 'application/json',
                'content-type': 'application/json',
                authorization: httpClient.defaults.headers.common.Authorization,
            },
            params: {
                timezone: 'America/Recife',
            },
            extras: {
                modelo_dispositivo,
                fabricante,
            },
            //iOS Options
            showsBackgroundLocationIndicator: true,
            stationaryRadius: 10,
            heartbeatInterval: Platform.select({ios: 10, android: 60}),
            preventSuspend: Platform.select({ios: true, android: false}),
            activityType:
                BackgroundGeolocation.ACTIVITY_TYPE_AUTOMOTIVE_NAVIGATION,
        };

        /// 2. ready the plugin.
        BackgroundGeolocation.ready(config)
            .then(state => {
                const handler = () => {
                    setEnabled(state.enabled);

                    console.log(
                        '- BackgroundGeolocation is configured and ready: ',
                        state.enabled,
                    );

                    // Sincroniza geolocalizações
                    // ao iniciar APP
                    if (state.enabled) {
                        _handleSync();
                    }
                };

                handler();
            })
            .catch(err => {
                console.error(err);
            });

        return () => {
            // Remove BackgroundGeolocation event-subscribers when the View is removed or refreshed
            // during development live-reload.  Without this, event-listeners will accumulate with
            // each refresh during live-reload.
            onLocation.remove();
        };
    }, [
        fabricante,
        _handleSync,
        modelo_dispositivo,
        _modificaDeviceInfo,
        _verificaStatusGeolocalizacao,
    ]);

    /// 3. start / stop BackgroundGeolocation
    React.useEffect(() => {
        _verificaStatusGeolocalizacao();
    }, [_verificaStatusGeolocalizacao]);

    const _getCurrentPosition = useCallback(() => {
        BackgroundGeolocation.getCurrentPosition({
            timeout: 30, // 30 second timeout to fetch location
            maximumAge: 5000, // Accept the last-known-location if not older than 5000 ms.
            desiredAccuracy: 10, // Try to fetch a location with an accuracy of `10` meters.
            samples: 3, // How many location samples to attempt.
            extras: {
                // Custom meta-data.
                fabricante,
                modelo_dispositivo,
            },
        })
            .then(location => {
                console.log('[_getCurrentPosition]: ', location);
                handleSync();
            })
            .catch(e => {
                console.error(
                    '[_getCurrentPosition]: Falha ao consultar localização atual',
                );
                console.error(e);
            });
    }, [fabricante, modelo_dispositivo, handleSync]);

    const _handleSync = useCallback(() => {
        try {
            _getCurrentPosition();
        } catch (e) {
            console.error('[_handleSync]: Falhou');
            console.error(e);
        }
    }, [_getCurrentPosition]);

    const _verificaStatusGeolocalizacao = useCallback(async () => {
        try {
            /*
             * Verifica se já excedeu o intervalo
             * de 2 minutos desde a última verificação do
             * status de geolocalização
             */
            const allowReq = await checkRequest('ultima_verificacao', 2);

            if (!allowReq) {
                return;
            }

            const state = await NetInfo.fetch();

            if (state.isConnected) {
                httpClient
                    .get(
                        'api/v1/app/geolocalizacao/usuario/rastreamento/status',
                    )
                    .then(response => {
                        dispatch({
                            type: types.MODIFICA_ULTIMA_VERIFICACAO_GEOLOCALIZACAO,
                            payload: {ultima_verificacao: moment()},
                        });

                        if (response.data.status === 'success') {
                            _handleBgGeolocation(response.data.iniciar);
                        } else {
                            _handleBgGeolocation(true);
                        }
                    })
                    .catch(err => {
                        Unauthorized(dispatch, err);
                    });
            } else {
                _handleBgGeolocation(true);
            }
        } catch (e) {
            console.error(e);
            showToast(
                'error',
                'Problema',
                'Falha ao tentar verificar status do rastreamento',
            );
        }
    }, [dispatch, _handleBgGeolocation]);

    const _handleBgGeolocation = useCallback(
        iniciar => {
            const _dispatch = () => {
                dispatch({
                    type: types.MODIFICA_RASTREAMENTO_USUARIO,
                    payload: {
                        rastreamento_usuario: iniciar,
                    },
                });
            };

            if (!enabled && iniciar) {
                BackgroundGeolocation.start()
                    .then(state => console.log('[start] success - ', state))
                    .catch(e => console.error(e))
                    .finally(() => _dispatch());
            } else if (!iniciar && AppState.currentState === 'active') {
                BackgroundGeolocation.stop()
                    .then(() => _dispatch())
                    .catch(() => _dispatch());
            }
        },
        [dispatch, enabled],
    );

    const _modificaDeviceInfo = useCallback(() => {
        try {
            DeviceInfo.getBatteryLevel().then(batteryLevel => {
                let value = Math.round(batteryLevel.toFixed(2) * 100);
                modificaNivelBateria(value);
            });

            modificaDispositivoInfo({
                modelo_dispositivo: DeviceInfo.getModel(),
                fabricante: DeviceInfo.getBrand(),
            });
        } catch (e) {
            console.error(e);
        }
    }, [modificaDispositivoInfo, modificaNivelBateria]);

    return <Fragment />;
};

const mapStateToProps = state => ({
    nivel_bateria: state.DeviceInfoReducer.nivel_bateria,
    modelo_dispositivo: state.DeviceInfoReducer.modelo_dispositivo,
    fabricante: state.DeviceInfoReducer.fabricante,
});

const actions = {
    modificaNivelBateria,
    modificaDispositivoInfo,
    modificaStatusConexao,
};

export default connect(mapStateToProps, actions)(HubsoftBackgroundGeolocation);`

**Comment by christocracy** [comment]
You are calling .changePace before .start has resolved.

the plug-in is not enabled until .start() has resolved.  .start() / .stop() toggles `.State.enabled`

it makes no sense to call .changePace when the plug-in is disabled.

check your code.

**Comment by christocracy** [comment]
Show me `$ adb logcat *:S TSLocationManager:V` of your app launching from a fresh install

**Comment by macielrsf** [comment]
> Show me `$ adb logcat *:S TSLocationManager:V` of your app launching from a fresh install

Type	Time	PID	Tag	Message
	2023-03-23T12:56:11.812Z	1952	MiuiKnockGestureService	focus window:com.hubsoft_app
	2023-03-23T12:56:11.815Z	7602	GST	forePkg: com.hubsoft_app, preForePkg: com.google.android.permissioncontroller
	2023-03-23T12:56:11.816Z	17491	ProcessMonitor	onForegroundInfoChanged: ForegroundInfo{mForegroundPackageName='com.hubsoft_app', mForegroundUid=10718, mForegroundPid=24331, mLastForegroundPackageName='com.google.android.permissioncontroller', mLastForegroundUid=10097, mLastForegroundPid=22857, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
	2023-03-23T12:56:11.816Z	22857	RenderInspector	DequeueBuffer time out on com.google.android.permissioncontroller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity, count=1, avg=21 ms, max=21 ms.
	2023-03-23T12:56:11.821Z	17491	GameBoosterService	onForegroundInfoChanged: Cur=com.hubsoft_app	 last=com.google.android.permissioncontroller
	2023-03-23T12:56:11.822Z	2417	EventBus	[2417, u0] send(AppTransitionFinishedEvent)
	2023-03-23T12:56:11.822Z	2417	EventBus	[2417, u0]  -> ForcedResizableInfoActivityController [0xdb03348, P1] onBusEvent(AppTransitionFinishedEvent)
	2023-03-23T12:56:11.822Z	1952	Timeline	Timeline: App_transition_ready time:1301000159
	2023-03-23T12:56:11.823Z	2417	EventBus	[2417, u0] onBusEvent(AppTransitionFinishedEvent) duration: 182 microseconds, avg: 526
	2023-03-23T12:56:11.823Z	1952	Timeline	Timeline: App_transition_stopped time:1301000159
	2023-03-23T12:56:11.824Z	2417	EventBus	[2417, u0] send(AppTransitionFinishedEvent)
	2023-03-23T12:56:11.824Z	2417	EventBus	[2417, u0]  -> ForcedResizableInfoActivityController [0xdb03348, P1] onBusEvent(AppTransitionFinishedEvent)
	2023-03-23T12:56:11.824Z	2417	EventBus	[2417, u0] onBusEvent(AppTransitionFinishedEvent) duration: 19 microseconds, avg: 526
	2023-03-23T12:56:11.824Z	2417	EventBus	[2417, u0] send(AppTransitionFinishedEvent)
	2023-03-23T12:56:11.824Z	2417	EventBus	[2417, u0]  -> ForcedResizableInfoActivityController [0xdb03348, P1] onBusEvent(AppTransitionFinishedEvent)
	2023-03-23T12:56:11.825Z	2417	EventBus	[2417, u0] onBusEvent(AppTransitionFinishedEvent) duration: 17 microseconds, avg: 526
	2023-03-23T12:56:11.825Z	2417	StatusBar	disable<e i a s b h r c s > disable2<q i n g r >
	2023-03-23T12:56:11.838Z	22857	OpenGLRenderer	endAllActiveAnimators on 0x701ae26600 (RippleDrawable) with handle 0x701ae6b360
	2023-03-23T12:56:11.842Z	1952	ActivityTrigger	ActivityTrigger activityPauseTrigger 
	2023-03-23T12:56:11.845Z	2417	PhoneStatusBar/NavigationBarView	setDisabledFlags back:false home:false recent:false
	2023-03-23T12:56:11.845Z	2417	StatusBarClock	 isNormalMode= true clock visible=true
	2023-03-23T12:56:11.846Z	2417	PhoneStatusBar/NavigationBarView	onDraw
	2023-03-23T12:56:11.847Z	17491	GameBoosterService	onGameStatusChange foreground:ForegroundInfo{mForegroundPackageName='com.hubsoft_app', mForegroundUid=10718, mForegroundPid=24331, mLastForegroundPackageName='com.google.android.permissioncontroller', mLastForegroundUid=10097, mLastForegroundPid=22857, mMultiWindowForegroundPackageName='null', mMultiWindowForegroundUid=-1, mFlags=0}
	2023-03-23T12:56:11.847Z	17491	VideoBoxUtils	isSupportVideoBox: false
	2023-03-23T12:56:11.850Z	17491	VideoToolBoxService	splitMode: onfalse
	2023-03-23T12:56:11.850Z	17491	VideoToolBoxService	onForegroundInfoChanged: Exit Vtb
	2023-03-23T12:56:11.852Z	24331	TSLocationManager	[c.t.locationmanager.util.c$j onPermissionGranted] 
  ✅  LocationAuthorization: Permission granted
	2023-03-23T12:56:11.856Z	24331	TSLocationManager	- Enable: false → true, trackingMode: 1
	2023-03-23T12:56:11.860Z	24331	Settings	Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
	2023-03-23T12:56:11.866Z	2417	EventBus	[2417, u0] send(TaskSnapshotChangedEvent)
	2023-03-23T12:56:11.870Z	1952	MiuiKnockGestureService	focus window:com.hubsoft_app
	2023-03-23T12:56:11.873Z	24331	TSLocationManager	[c.t.l.http.HttpService startMonitoringConnectivityChanges] 
  🎾  Start monitoring connectivity changes
	2023-03-23T12:56:11.878Z	1952	Timeline	Timeline: App_transition_ready time:1301000215
	2023-03-23T12:56:11.879Z	24331	TSLocationManager	[c.t.l.device.DeviceSettings startMonitoringPowerSaveChanges] 
  🎾  Start monitoring powersave changes
	2023-03-23T12:56:11.882Z	2417	EventBus	[2417, u0] send(AppTransitionFinishedEvent)
	2023-03-23T12:56:11.882Z	2417	EventBus	[2417, u0]  -> ForcedResizableInfoActivityController [0xdb03348, P1] onBusEvent(AppTransitionFinishedEvent)
	2023-03-23T12:56:11.882Z	2417	EventBus	[2417, u0] onBusEvent(AppTransitionFinishedEvent) duration: 25 microseconds, avg: 526
	2023-03-23T12:56:11.894Z	24331	TSLocationManager	[c.t.l.service.HeartbeatService start] 
  🎾  Start heartbeat (60s)
	2023-03-23T12:56:11.898Z	24331	Settings	Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
	2023-03-23T12:56:11.907Z	24331	TSLocationManager	[c.t.locationmanager.util.c h] 
  ℹ️  LocationAuthorization: Permission granted
	2023-03-23T12:56:11.908Z	24331	TSLocationManager	[c.t.l.service.TrackingService changePace] 
  🔵  setPace: false → false
	2023-03-23T12:56:11.910Z	24331	Settings	Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
	2023-03-23T12:56:11.917Z	24331	TSLocationManager	[c.t.l.service.TrackingService changePace] 
  ⚠️  Waiting for existing motionchange request #1 to complete
	2023-03-23T12:56:11.922Z	24331	TSLocationManager	[c.t.locationmanager.util.c h] 
  ℹ️  LocationAuthorization: Permission granted
	2023-03-23T12:56:11.924Z	24331	TSLocationManager	[c.t.l.p.TSProviderManager handleProviderChangeEvent] 
╔═════════════════════════════════════════════
║ Location-provider change: true
╠═════════════════════════════════════════════
╟─ GPS: true
╟─ Network: true
╟─ AP Mode: false

	2023-03-23T12:56:11.926Z	24331	TSLocationManager	[c.t.l.http.HttpService a] 
╔═════════════════════════════════════════════
║ 📶  Connectivity change: connected? true
╠═════════════════════════════════════════════

	2023-03-23T12:56:11.936Z	2833	SarService	Receiver polling >>>> Change receiver mode: off
	2023-03-23T12:56:11.940Z	1952	SensorService	check list, getPackageName  com.facebook.react.common.ShakeDetector
	2023-03-23T12:56:11.941Z	704	sensors-hal	batch:180, android.sensor.accelerometer/44, period=66667000, max_latency=0
	2023-03-23T12:56:11.941Z	704	sensors-hal	batch:189, android.sensor.accelerometer/44, period=66667000, max_latency=0 request completed
	2023-03-23T12:56:11.941Z	704	sensors-hal	activate:147, android.sensor.accelerometer/44 en=1
	2023-03-23T12:56:11.941Z	704	sensors-hal	get_qmi_debug_flag:230, support_qmi_debug : false
	2023-03-23T12:56:11.946Z	722	/vendor/bin/hw/vendor.qti.hardware.servicetracker@1.1-service	bindService is called for service : com.google.android.gms/com.google.android.location.internal.GoogleLocationManagerService and for client com.hubsoft_app
	2023-03-23T12:56:11.946Z	722	/vendor/bin/hw/vendor.qti.hardware.servicetracker@1.1-service	total connections for service : com.google.android.gms/com.google.android.location.internal.GoogleLocationManagerServiceare :8
	2023-03-23T12:56:11.946Z	722	/vendor/bin/hw/vendor.qti.hardware.servicetracker@1.1-service	total connections for client : com.hubsoft_appare :1
	2023-03-23T12:56:11.946Z	704	sensors-hal	activate:158, android.sensor.accelerometer/44 en=1 completed
	2023-03-23T12:56:11.948Z	24331	OneSignal	Already initialized the OneSignal React-Native SDK
	2023-03-23T12:56:11.950Z	1952	MiuiNetworkPolicy	updateUidState uid = 10186, uidState = 2
	2023-03-23T12:56:11.951Z	24331	TSLocationManager	[c.t.l.l.LifecycleManager onResume] ☯️  onResume
	2023-03-23T12:56:11.954Z	704	sensors-hal	handle_indication_realtime:439,  SCHED_FIFO(10) for qmi_cbk
	2023-03-23T12:56:11.958Z	24331	TSLocationManager	[c.t.l.http.HttpService flush] 
╔═════════════════════════════════════════════
║ HTTP Service (count: 0)
╠═════════════════════════════════════════════

	2023-03-23T12:56:11.959Z	722	/vendor/bin/hw/vendor.qti.hardware.servicetracker@1.1-service	bindService is called for service : com.hubsoft_app/androidx.work.impl.background.systemjob.SystemJobService and for client system
	2023-03-23T12:56:11.959Z	722	/vendor/bin/hw/vendor.qti.hardware.servicetracker@1.1-service	total connections for service : com.hubsoft_app/androidx.work.impl.background.systemjob.SystemJobServiceare :1
	2023-03-23T12:56:11.959Z	722	/vendor/bin/hw/vendor.qti.hardware.servicetracker@1.1-service	total connections for client : systemare :17
	2023-03-23T12:56:11.960Z	1952	CompatibilityInfo	mCompatibilityFlags - 0
	2023-03-23T12:56:11.960Z	1952	CompatibilityInfo	applicationDensity - 461
	2023-03-23T12:56:11.960Z	1952	CompatibilityInfo	applicationScale - 1.0
	2023-03-23T12:56:11.961Z	27002	GoogleInputMethodService	GoogleInputMethodService.onFinishInput():3302 

	2023-03-23T12:56:11.962Z	27002	GoogleInputMethodService	GoogleInputMethodService.updateDeviceLockedStatus():2152 repeatCheckTimes = 0, unlocked = true

	2023-03-23T12:56:11.962Z	27002	GoogleInputMethodService	GoogleInputMethodService.onStartInput():1930 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.hubsoft_app fieldId=-1 fieldName=null extras=null}, false)

	2023-03-23T12:56:11.962Z	27002	GoogleInputMethodService	GoogleInputMethodService.shouldHideHeaderOnInitialState():4116 ShouldHideHeaderOnInitialState = false

	2023-03-23T12:56:11.963Z	27002	GoogleInputMethodService	GoogleInputMethodService.updateDeviceLockedStatus():2152 repeatCheckTimes = 2, unlocked = true

	2023-03-23T12:56:11.965Z	722	/vendor/bin/hw/vendor.qti.hardware.servicetracker@1.1-service	startService() is called for servicecom.hubsoft_app/androidx.work.impl.background.systemjob.SystemJobService
	2023-03-23T12:56:11.968Z	1952	CompatibilityInfo	mCompatibilityFlags - 0
	2023-03-23T12:56:11.968Z	1952	CompatibilityInfo	applicationDensity - 461
	2023-03-23T12:56:11.968Z	1952	CompatibilityInfo	applicationScale - 1.0
	2023-03-23T12:56:11.969Z	722	/vendor/bin/hw/vendor.qti.hardware.servicetracker@1.1-service	startService() is called for servicecom.hubsoft_app/com.transistorsoft.locationmanager.service.LocationRequestService
	2023-03-23T12:56:11.974Z	2417	EventBus	[2417, u0] send(AppTransitionFinishedEvent)
	2023-03-23T12:56:11.974Z	2417	EventBus	[2417, u0]  -> ForcedResizableInfoActivityController [0xdb03348, P1] onBusEvent(AppTransitionFinishedEvent)
	2023-03-23T12:56:11.974Z	2417	EventBus	[2417, u0] onBusEvent(AppTransitionFinishedEvent) duration: 19 microseconds, avg: 526
	2023-03-23T12:56:11.974Z	17491	SCTaskStackListener	onTaskStackChanged! inSplit = false
	2023-03-23T12:56:11.987Z	601	ResolverController	No valid NAT64 prefix (352, <unspecified>/0)
	2023-03-23T12:56:11.991Z	1952	Timeline	Timeline: App_transition_stopped time:1301000328
	2023-03-23T12:56:11.993Z	2417	EventBus	[2417, u0] send(AppTransitionFinishedEvent)
	2023-03-23T12:56:11.993Z	2417	EventBus	[2417, u0]  -> ForcedResizableInfoActivityController [0xdb03348, P1] onBusEvent(AppTransitionFinishedEvent)
	2023-03-23T12:56:11.993Z	2417	EventBus	[2417, u0] onBusEvent(AppTransitionFinishedEvent) duration: 22 microseconds, avg: 526
	2023-03-23T12:56:12.009Z	24331	ReactNativeJS	
	2023-03-23T12:56:12.019Z	1952	PerfShielderService	com.hubsoft_app|com.hubsoft_app/com.hubsoft_app.MainActivity|144|1300994529677301|144|3|1
	2023-03-23T12:56:12.025Z	24331	TSLocationManager	
	2023-03-23T12:56:12.044Z	3843	MiuiPerfServiceClient	interceptAndQueuing:24331|com.hubsoft_app|144|144|unknown|null|com.hubsoft_app/com.hubsoft_app.MainActivity|1300994529677301|Slow handle traversal|1
	2023-03-23T12:56:12.099Z	24331	TSLocationManager	[c.t.l.service.AbstractService start] 
  🎾  LocationRequestService [eventCount: 1]

**Comment by macielrsf** [comment]
> Show me `$ adb logcat *:S TSLocationManager:V` of your app launching from a fresh install

![Captura de Tela 2023-03-23 às 10 01 20](https://user-images.githubusercontent.com/8006109/227212399-32ad2867-0760-4e02-b3ed-53f80474ef9b.png)

![Captura de Tela 2023-03-23 às 10 01 32](https://user-images.githubusercontent.com/8006109/227212464-2677de71-4066-4fb0-a8b0-5b90ba974585.png)

![Captura de Tela 2023-03-23 às 10 01 48](https://user-images.githubusercontent.com/8006109/227212488-fe689307-19f9-4608-884a-701e6a369036.png)

**Comment by christocracy** [comment]
Please don't post screenshots of logs.

In terminal  window, execute the following.

```
$ adb logcat *:S TSLocationManager:V
```

**Comment by macielrsf** [comment]
> Show me `$ adb logcat *:S TSLocationManager:V` of your app launching from a fresh install

[TSLocationManagerLogs.zip](https://github.com/transistorsoft/react-native-background-geolocation/files/11051182/TSLocationManagerLogs.zip)

**Comment by macielrsf** [comment]
> > Show me `$ adb logcat *:S TSLocationManager:V` of your app launching from a fresh install
> 
> [TSLocationManagerLogs.zip](https://github.com/transistorsoft/react-native-background-geolocation/files/11051182/TSLocationManagerLogs.zip)

I exported the logs from Flipper in JSON format for easy viewing. Would it be this ?

**Comment by macielrsf** [comment]
Hi @christocracy, 

To use .emailLog, do I need to set debug as "true" on production ? For this bug, logLevel as "LOG_LEVEL_ERROR", will it be enough ? 

Will sounds and notifications be trigged on production ? I wouldn't like it.

**Comment by christocracy** [comment]
emailLog has nothing to do with debug: true.

Use LOG_LEVEL_VERBOSE

**Comment by macielrsf** [comment]
Are there any workaround that I can use it ? Like a timeout to initialize or config BackgroundGeolocation ?

I was checking android-permissions dependency of this library and I found this old issue:
https://github.com/nishkarsh/android-permissions/issues/16

Is there something similar with current issue ?

**Comment by christocracy** [comment]
> Is there something similar with current issue ?

No, it’s unrelated.

 I suggest you install the latest version.  You are the only person reporting this issue.

let me know if you know how to reproduce it.
