### ISSUE TITLE
Sometimes getting FATAL error on (dev only?) launch

### ISSUE THREAD

**Issue by savv** [transistorsoft/react-native-background-geolocation#1720]
## Your Environment
* Plugin version: 4.12.1
* Platform: Android
* OS version: 31
* Device manufacturer / model: emulator
* React Native version (`react-native -v`): 0.71.10
* Plugin config
```typescript <!-- Syntax-highlighting:  paste your code below -->
{
  desiredAccuracy: BackgroundGeolocation?.DESIRED_ACCURACY_HIGH,
  distanceFilter: 20,
  foregroundService: true,

  locationAuthorizationRequest: 'WhenInUse',
  disableLocationAuthorizationAlert: true,
  stopDetectionDelay: 2,
  stopTimeout: 10,
}
```

## Expected Behavior
No crash.

## Actual Behavior
Yes crash.

## Steps to Reproduce
Reproducing this involves starting our app (in dev mode only, so far) multiple times. Our app uses headless mode which may be relevant; and it uses flipper.

## Context
It seems others recently reported this in #399 

## Debug logs
``` <!-- Syntax highlighting:  DO NOT REMOVE -->
06-21 13:27:14.145  6160  6224 E AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
06-21 13:27:14.145  6160  6224 E AndroidRuntime: Process: com.greentriangle.greentriangle.dev, PID: 6160
06-21 13:27:14.145  6160  6224 E AndroidRuntime: java.lang.ClassCastException: org.slf4j.helpers.SubstituteLogger cannot be cast to ch.qos.logback.classic.Logger
06-21 13:27:14.145  6160  6224 E AndroidRuntime: 	at com.transistorsoft.locationmanager.logger.TSLog.getRootLogger(Unknown Source:10)
06-21 13:27:14.145  6160  6224 E AndroidRuntime: 	at com.transistorsoft.locationmanager.logger.TSLog.access$000(Unknown Source:0)
06-21 13:27:14.145  6160  6224 E AndroidRuntime: 	at com.transistorsoft.locationmanager.logger.TSLog$a.run(Unknown Source:0)
06-21 13:27:14.145  6160  6224 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
06-21 13:27:14.145  6160  6224 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
06-21 13:27:14.145  6160  6224 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
06-21 13:27:14.148   536   595 W ActivityTaskManager:   Force finishing activity com.greentriangle.greentriangle.dev/com.greentriangle.MainActivity
06-21 13:27:14.149   342   413 D goldfish-address-space: claimShared: Ask to claim region [0x1eec0c000 0x1ef1e8000]
06-21 13:27:14.180  6160  6221 D InstallReferrerState: FEATURE_NOT_SUPPORTED
06-21 13:27:14.182  6160  6221 I RNFusedLocation: RNFusedLocation initialized
06-21 13:27:14.185  6160  6221 I Leveldb : Loading C++ library...
06-21 13:27:14.187   536  6227 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
06-21 13:27:14.189  6160  6224 I Process : Sending signal. PID: 6160 SIG: 9
06-21 13:27:14.190  6205  6205 I         : OkHttp Dispatch (6205) used greatest stack depth: 10528 bytes left
06-21 13:27:14.196  1004  1004 D MainContentCaptureSession: Flushing 1 event(s) for act:com.google.android.apps.nexuslauncher/.NexusLauncherActivity [state=2 (ACTIVE), disabled=false], reason=FULL
06-21 13:27:14.200   536   564 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
06-21 13:27:14.209   376   485 W TransactionTracing: Could not find layer id -1
06-21 13:27:14.212   536   564 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
06-21 13:27:14.215   536   610 W WindowManager: Failed to deliver inset state change to w=Window{aac069b u0 com.greentriangle.greentriangle.dev/com.greentriangle.MainActivity}
06-21 13:27:14.215   536   610 W WindowManager: android.os.DeadObjectException
06-21 13:27:14.215   536   610 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
06-21 13:27:14.215   536   610 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
06-21 13:27:14.215   536   610 W WindowManager: 	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:473)
06-21 13:27:14.215   536   610 W WindowManager: 	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3995)
06-21 13:27:14.215   536   610 W WindowManager: 	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$4(InsetsStateController.java:351)
06-21 13:27:14.215   536   610 W WindowManager: 	at com.android.server.wm.InsetsStateController.$r8$lambda$An2IoiA3BeA5IWc6QwBOjKArM80(Unknown Source:0)
06-21 13:27:14.215   536   610 W WindowManager: 	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda3.run(Unknown Source:2)
06-21 13:27:14.215   536   610 W WindowManager: 	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:345)
06-21 13:27:14.215   536   610 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:832)
06-21 13:27:14.215   536   610 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:777)
06-21 13:27:14.215   536   610 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:177)
06-21 13:27:14.215   536   610 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:126)
06-21 13:27:14.215   536   610 W WindowManager: 	at com.android.server.wm.WindowManagerService.relayoutWindow(WindowManagerService.java:2466)
06-21 13:27:14.215   536   610 W WindowManager: 	at com.android.server.wm.Session.relayout(Session.java:253)
06-21 13:27:14.215   536   610 W WindowManager: 	at android.view.IWindowSession$Stub.onTransact(IWindowSession.java:727)
06-21 13:27:14.215   536   610 W WindowManager: 	at com.android.server.wm.Session.onTransact(Session.java:178)
06-21 13:27:14.215   536   610 W WindowManager: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
06-21 13:27:14.215   536   610 W WindowManager: 	at android.os.Binder.execTransact(Binder.java:1244)
06-21 13:27:14.216   610   610 I binder_alloc: 6160: binder_alloc_buf, no vma

```

**Comment by christocracy** [comment]
Show me the result of:

```
$ cd android
$ ./gradlew app:dependencies
```
(It’s a lot of output.  Capture into a text file and attach to this thread)

**Comment by savv** [comment]
[deps.txt](https://github.com/transistorsoft/react-native-background-geolocation/files/11817447/deps.txt)
