### ISSUE TITLE
android failed to merge android manifest 

### ISSUE THREAD

**Issue by geongun20** [transistorsoft/react-native-background-geolocation#1816]
## Your Environment
* Plugin version: 4.13.3
* Platform: Android
* OS version: 13
* Device manufacturer / model: samsung SM-A326K
* React Native version (`react-native -v`): 0.71.7
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
        isMoving: true,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        locationAuthorizationRequest: "WhenInUse",
        disableStopDetection: true,
        pausesLocationUpdatesAutomatically: false,
        preventSuspend: true,
        disableLocationAuthorizationAlert: true,
        showsBackgroundLocationIndicator: true,
        heartbeatInterval: 60,
        stopOnTerminate: true,
        distanceFilter: 3,
        disableElasticity: true,
        stopTimeout: 500000,
        autoSync: false,
        logLevel: 2,
```

## Expected Behavior

build well

## Actual Behavior

build failed after update plugin version

## Steps to Reproduce

1. update version 4.11.4 -> 4.13.3
2. build app test device
3.
4.

## Context

I use airbridge sdk. I think I need to way to merge backup_rules file. But I have no information about backup_rules in tslocationmanager sdk

## Debug logs

<details><summary>Logs</summary>
<img width="853" alt="image" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/43872798/2b168217-205a-419f-bf3a-a02a8403aba1">

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/seunggeonlee/tracer/tracer/packages/app/android/app/src/debug/AndroidManifest.xml:23:18-78 Error:
        Attribute application@fullBackupContent value=(@xml/airbridge_auto_backup_rules) from [io.airbridge:sdk-android:2.22.0] AndroidManifest.xml:23:18-78
        is also present at [com.transistorsoft:tslocationmanager:3.4.5] AndroidManifest.xml:41:18-63 value=(@xml/backup_rules).
        Suggestion: add 'tools:replace="android:fullBackupContent"' to <application> element at AndroidManifest.xml:7:5-12:19 to override.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : Attribute application@fullBackupContent value=(@xml/airbridge_auto_backup_rules) from [io.airbridge:sdk-android:2.22.0] AndroidManifest.xml:23:18-78
        is also present at [com.transistorsoft:tslocationmanager:3.4.5] AndroidManifest.xml:41:18-63 value=(@xml/backup_rules).
        Suggestion: add 'tools:replace="android:fullBackupContent"' to <application> element at AndroidManifest.xml:7:5-12:19 to override.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 13s

    at makeError (/Users/seunggeonlee/tracer/tracer/packages/app/node_modules/execa/index.js:174:9)
    at /Users/seunggeonlee/tracer/tracer/packages/app/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/seunggeonlee/tracer/tracer/packages/app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:82:7)
    at async Command.handleAction (/Users/seunggeonlee/tracer/tracer/packages/app/node_modules/@react-native-community/cli/build/index.js:108:9)
```

</details>

**Comment by christocracy** [comment]
Read the ]CHANGELOG](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#4131--2023-08-24)

**Comment by geongun20** [comment]
@christocracy My issue is about backup_rules. But I couldn't find any information about backup_rules in 4.13.1 changes. Could you let me know what can i do?

**Comment by christocracy** [comment]
I didn’t closely read your error because you posted a screenshot and I didn’t have my glasses on (post *text*).

why don’t you try the suggestion in the error message about tools:replace?

**Comment by geongun20** [comment]
@christocracy I posted error texts under screenshot! I tried the suggestion about tools:replace but It doesn't work.

I think I need information about tslocationmanager backup settings. Could you give me that info?
[Here](https://help.airbridge.io/en/developers/android-sdk#auto-backup) is backup settings info of airbridge.
