### ISSUE TITLE
App crash fatal exception pool-12-thread-1

### ISSUE THREAD

**Issue by lduran1997** [transistorsoft/react-native-background-geolocation#1873]
## Your Environment
* Plugin version: ^4.14.3
* Platform: Android
* OS version: iOS (Mac)
* Device manufacturer / model:  Xiaomi 12 Pro
* React Native version (`react-native -v`): 0.70.6
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
// Step 1:  Listen to events:
      await BackgroundGeolocation.onLocation(
        onLocation.bind(this),
        onLocationError.bind(this),
      );

      // Step 2:  #configure:
      const backgroundPermission = await hasBackgroundGeolocationPermission();
      const motionPermission = await hasMotionPermission();
      let state = await BackgroundGeolocation.ready({
        debug: false,
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
        disableMotionActivityUpdates: !motionPermission, // No requerir el permiso de actividad fisica
        distanceFilter: 10, // Distancia a recorrer para grabar una posicion
        stationaryRadius: 15, // Distancia que debe recorrer el usuario para activarse el tracking constante
        notification: {
          title: 'Tracking de Zerel activo.',
          text: 'Zerel está grabando su ubicación en tiempo real.',
          smallIcon: 'drawable/icon_small_bg',
        },
        url: awsconfig.aws_appsync_graphqlEndpoint,
        headers: {
          'x-api-key': awsconfig.aws_appsync_apiKey,
          authorization: user_token,
        },
        httpRootProperty: '.',
        autoSync: true, // Envío automático de tracks
        // autoSync: false,
        stopOnTerminate: false, // Sigue grabando al cerrar la app
        //stopOnTerminate: true,
        startOnBoot: true, // Reinicia al encender el móvil
        foregroundService: true, // Robusto frente a que el SO lo cierre
        //enableHeadless: true,
        //heartbeatInterval: 30,
        disableLocationAuthorizationAlert: false, // <-- we handle the location alerts ourselves.
        locationAuthorizationRequest: backgroundPermission
          ? 'Always'
          : 'WhenInUse',
      });
```

## Expected Behavior
The app should starts correctly and not get crashed, fetching user location.

## Actual Behavior
App crashes and it stop crashing if we dont use BackgroundGeolocation functions. It occurs after upgrading BackgroundGeolocation version.

## Context
We are trying to get all libraries we use fully updated, but when we update BackgroundGeolocation and did some configuration changes as in documentation says, we get app crashed.

## Debug logs
<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
FATAL EXCEPTION: pool-12-thread-1
Process: com.TheBasement.zerel.parking, PID: 23706
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~CcvSl3lU9vAE17N3KIr6hQ==/com.TheBasement.zerel.parking-bIeiiseU1wUxVPQ3v4mQNQ==/base.apk)
	at com.transistorsoft.xms.g.location.FusedLocationProviderClient.getLastLocation(Unknown Source:50)
	at com.transistorsoft.locationmanager.location.TSLocationManager.getLastLocation(Unknown Source:20)
	at com.transistorsoft.locationmanager.location.TSLocationManager.getCurrentPosition(Unknown Source:8)
	at com.transistorsoft.locationmanager.service.TrackingService.changePace(Unknown Source:293)
	at com.transistorsoft.locationmanager.service.TrackingService.start(Unknown Source:134)
	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$z0.run(Unknown Source:139)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

FATAL EXCEPTION: pool-10-thread-2
Process: com.TheBasement.zerel.parking, PID: 25026
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~CcvSl3lU9vAE17N3KIr6hQ==/com.TheBasement.zerel.parking-bIeiiseU1wUxVPQ3v4mQNQ==/base.apk)
	at com.transistorsoft.xms.g.location.FusedLocationProviderClient.getLastLocation(Unknown Source:50)
	at com.transistorsoft.locationmanager.location.TSLocationManager.getLastLocation(Unknown Source:20)
	at com.transistorsoft.locationmanager.location.TSLocationManager.getCurrentPosition(Unknown Source:8)
	at com.transistorsoft.locationmanager.service.TrackingService.changePace(Unknown Source:293)
	at com.transistorsoft.locationmanager.service.TrackingService.start(Unknown Source:134)
	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$z0.run(Unknown Source:139)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

FATAL EXCEPTION: pool-10-thread-2
Process: com.TheBasement.zerel.parking, PID: 25572
java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~CcvSl3lU9vAE17N3KIr6hQ==/com.TheBasement.zerel.parking-bIeiiseU1wUxVPQ3v4mQNQ==/base.apk)
	at com.transistorsoft.xms.g.location.FusedLocationProviderClient.getLastLocation(Unknown Source:50)
	at com.transistorsoft.locationmanager.location.TSLocationManager.getLastLocation(Unknown Source:20)
	at com.transistorsoft.locationmanager.location.TSLocationManager.getCurrentPosition(Unknown Source:8)
	at com.transistorsoft.locationmanager.service.TrackingService.start(Unknown Source:109)
	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$z0.run(Unknown Source:139)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

</details>

**Comment by christocracy** [comment]
[Search issues](https://github.com/transistorsoft/react-native-background-geolocation/issues?q=IncompatibleClassChangeError) **BEFORE** posting.  This issue has been posted *dozens* of time and is the fault of a well-known breaking change in `play-services-location`.

Duplicate #1710
