### ISSUE TITLE
App crashes on Android Release version - Could not invoke RNBackgroundGeolocation.ready

### ISSUE THREAD

**Issue by UnderTheMoonspell** [transistorsoft/react-native-background-geolocation#1943]
I followed all the setup steps for Android. Even copied the proguard rules from the lib to our own to confirm it was not some problem importing the proguard rules.

**_NOTE_**: in this release version we are still not providing a license key (its inserted in our production pipelines). Could that be the problem?

## Your Environment
* Plugin version: 4.14.3
* Platform: Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.72.8
* Plugin config
![image](https://github.com/transistorsoft/react-native-background-geolocation/assets/10156878/fa6c2b1f-0a5b-4eaf-8b6b-1ece26911afd)

## Expected Behavior
The app works like the debug version in that it doesn't crash upon calling BackgroundGeolocation.ready()

## Actual Behavior
The app crashes in Android. If we comment the .ready() initialization the app works as expected.

## Steps to Reproduce

1. Generate a release build
2. Initiate the app and call .ready() method

## Debug logs

<img width="1390" alt="image" src="https://github.com/transistorsoft/react-native-background-geolocation/assets/10156878/7e25d1b7-1527-4a67-b9b8-c58fced9361a">

**Comment by christocracy** [comment]
show me the following files (as *text* -- **NOT** screenshots):
- `android/build.gradle`
- `android/app/build.gradle`

**Comment by UnderTheMoonspell** [comment]
build.gradle
```
def REACT_NATIVE_VERSION = [
    'node',
    '--print',
    "JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"
].execute(null, rootDir).text.trim()

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
        kotlinVersion = "1.7.22"
        AsyncStorage_next_roomVersion = '2.4.3'
    }
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        // Kotlin
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
        // Google Services
        classpath("com.google.gms:google-services:4.3.15")
        // Crashlytics Gradle plugin
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.4'
        // Performance Monitoring Plugin
        classpath 'com.google.firebase:perf-plugin:1.4.2'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    configurations.all {
        resolutionStrategy {
            // Remove this override in 0.65+, as a proper fix is included in react-native itself.
            force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
        }
    }

    repositories {
        mavenCentral()
        google()
        maven { url 'https://www.jitpack.io' }
        maven { url "https://appboy.github.io/appboy-android-sdk/sdk" }
        maven { url "https://storage.googleapis.com/logrocket-maven/" }
        maven { url 'https://zendesk.jfrog.io/zendesk/repo' }
        maven {
            url "$rootDir/../node_modules/@notifee/react-native/android/libs"
        }
        maven { url("${project(':react-native-background-geolocation').projectDir}/libs") }
        maven { url 'https://developer.huawei.com/repo/' }
        maven { url("${project(':react-native-background-fetch').projectDir}/libs") }
    }
}
```

**Comment by christocracy** [comment]
I asked for *two* gradle files.

**Comment by UnderTheMoonspell** [comment]
Yes i know sorry, i was just cleaning the app/build.gradle:

```
apply plugin: "com.android.application"
apply plugin: "com.facebook.react"
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.firebase.firebase-perf'

import com.android.build.OutputFile

react {
    root = file("../../")
    cliFile = file("../../node_modules/react-native/cli.js")

    //* Variants */
    entryFile = file("../../engine_autogenerated/index.js")
    hermesCommand = "$rootDir/../node_modules/react-native/sdks/hermesc/%OS-BIN%/hermesc"
}

project.ext.envConfigFiles = [
    ************
]

apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
apply from: file('./mainfile.gradle')

// background-geolocation
Project background_geolocation = project(':react-native-background-geolocation')
apply from: "${background_geolocation.projectDir}/app.gradle"

def enableSeparateBuildPerCPUArchitecture = false

def enableProguardInReleaseBuilds = true

def jscFlavor = 'org.webkit:android-jsc:+'

def reactNativeArchitectures() {
    def value = project.getProperties().get("reactNativeArchitectures")
    return value ? value.split(",") : ["armeabi-v7a", "x86", "x86_64", "arm64-v8a"]
}

android {
    ndkVersion rootProject.ext.ndkVersion
    compileSdkVersion rootProject.ext.compileSdkVersion

    namespace "************"
    defaultConfig {
        applicationId "************"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        resValue "string", "build_config_package", "************"
        
        def information = getVersionInformation()
        versionCode information.buildCode.toInteger()
        versionName information.buildVersion
        // include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        
        multiDexEnabled true
    }

    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true
        // Sets Java compatibility to Java 8
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include (*reactNativeArchitectures())
        }
    }

    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }

        release {
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }

            enableV1Signing = true
            enableV2Signing = true
            enableV3Signing = true
            enableV4Signing = true
        }
    }

    flavorDimensions.addAll(["product", "enviroment"])
    
    productFlavors {
        dev {
            dimension "product"
        }

        production {
            applicationId "************"
            dimension "product"
        }

        development {
            signingConfig signingConfigs.debug
            applicationIdSuffix ".development"
            buildConfigField "boolean", "IS_PRODUCTION", "false"
            dimension "enviroment"
            manifestPlaceholders.geolocationLicenseKey = ""
        }

        staging {
            applicationIdSuffix ".dev"
            buildConfigField "boolean", "IS_PRODUCTION", "false"
            dimension "enviroment"
            manifestPlaceholders.geolocationLicenseKey = System.getenv('GEOLOCATION_LICENSE_KEY') ?: ""
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.getByName("debug")
        }

        release {
            debuggable false
            signingConfig signingConfigs.getByName("release")
            multiDexKeepProguard file('multidex-config.pro')
            minifyEnabled enableProguardInReleaseBuilds
            shrinkResources enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"

            ndk {
                debugSymbolLevel 'SYMBOL_TABLE'
            }

            firebaseCrashlytics {
                nativeSymbolUploadEnabled true
                unstrippedNativeLibsDir "build/intermediates/merged_native_libs/${getCurrentFlavor()}Release/out/lib"
            }
        }
    }

    configurations {
        implementation.exclude module:'work-runtime-ktx'
        all*.exclude group: 'androidx.work', module: 'listenablefuture'
    }


    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
}

dependencies {
    // -> SHARED DEPENDENCIES
    implementation fileTree(dir: "libs", include: ["*.jar"])
    // https://developer.android.com/studio/write/java8-support#library-desugaring-versions
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.2.2'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$rootProject.ext.kotlinVersion"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.0'

    // The version of react-native is set by the React Native Gradle Plugin
    implementation 'com.facebook.react:react-android'

    // Android X libraries
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.0.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.biometric:biometric:1.1.0'
    implementation "androidx.core:core-splashscreen:1.0.0"

    implementation 'com.liftric:kvault:1.9.0'

    // Flippper
    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}")
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }
    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:0.182.0")

    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }

    implementation project(":react-native-screens")
    implementation project(":react-native-safe-area-context")

    // We are using BOM from React Native Firebase Crashlytcs: When using the BoM, don't specify versions in Firebase dependencies
    implementation platform("com.google.firebase:firebase-bom:${getFirebaseBoMVersion()}")
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-common-ktx'
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-messaging:23.0.+'
    implementation 'androidx.work:work-runtime-ktx:2.8.0'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
```

**Comment by UnderTheMoonspell** [comment]
@christocracy this is the only thing I get from the lib logs:

![image](https://github.com/transistorsoft/react-native-background-geolocation/assets/10156878/a445db2c-0669-4531-861d-de52e03aef6e)

**Comment by christocracy** [comment]
Please don't show screenshots of **code OR logs**.  Post text.  [learn to syntax highlight "fenced code blocks"](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

Why are you configuring the plugin with `reset: false`?  Do you know what that does?

**Comment by UnderTheMoonspell** [comment]
Reset is not longer needed as we removed the setConfigs we used to have. But the problem still stands

**Comment by christocracy** [comment]
After removing `reset: false` (or changing to `true`), enable verbose logging `logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE` then restart your app.

**Comment by UnderTheMoonspell** [comment]
Exact same logs:

```
2024-02-13 16:23:33.285 31655-31879 ReactNativeJS           ****************                     I  STARTINITLOGS
2024-02-13 16:23:33.285 31655-31879 ReactNativeJS           ****************                     I  02-13 16:21:42.049 DEBUG [LoggerFacade$a a] ℹ️   Persist config, dirty: []
                                                                                                    02-13 16:23:31.455 DEBUG [LoggerFacade$a a] ℹ️   Persist config, dirty: []
2024-02-13 16:23:33.286 31655-31882 Settings                ****************                     W  Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
2024-02-13 16:23:33.288 31655-31882 AndroidRuntime          ****************                     E  FATAL EXCEPTION: mqt_native_modules
                                                                                                    Process: us.rain.app.dev, PID: 31655
                                                                                                    java.lang.RuntimeException: Could not invoke RNBackgroundGeolocation.ready
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(SourceFile:193)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(SourceFile:148)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:1)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(SourceFile:38)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(SourceFile:149)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(SourceFile:148) 
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:1) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(SourceFile:38) 
                                                                                                    	at java.lang.Thread.run(Thread.java:920) 
                                                                                                    Caused by: java.lang.NoSuchMethodError: No virtual method e()I in class Lorg/json/JSONArray; or its super classes (declaration of 'org.json.JSONArray' appears in /apex/com.android.art/javalib/core-libart.jar)
                                                                                                    	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.convertJsonToArray(SourceFile:7)
                                                                                                    	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.jsonToMap(SourceFile:49)
                                                                                                    	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.jsonToMap(SourceFile:35)
                                                                                                    	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.getState(SourceFile:2)
                                                                                                    	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.a(Unknown Source:0)
                                                                                                    	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule$1.onSuccess(Unknown Source:7)
                                                                                                    	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.ready(Unknown Source:188)
                                                                                                    	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.ready(SourceFile:169)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(SourceFile:149) 
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(SourceFile:148) 
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(SourceFile:1) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(SourceFile:38) 
                                                                                                    	at java.lang.Thread.run(Thread.java:920) 
2024-02-13 16:23:33.338 31655-31675 libcrashlytics          ****************                     D  Initializing libcrashlytics version 3.2.0
2024-02-13 16:23:33.338 31655-31675 libcrashlytics          ****************                     D  Initializing native crash handling successful.
2024-02-13 16:23:33.401  1461-3463  ActivityManager         system_process                       E  App crashed on incremental package ****************which is 100% loaded.
```

**Comment by christocracy** [comment]
There is something odd about your app config that seems to be obfuscating `org.json.JSONArray`.

See [here](https://stackoverflow.com/questions/57274183/android-issue-using-json-library-in-pure-java-package)

There are a number of odd things in your gradle config.
- usage of [deprecated `jcenter()` repository](https://developer.android.com/build/jcenter-migration) (deprecated since 2021)
- manually importing react-native plugin dependencies:
```
implementation project(":react-native-screens")
implementation project(":react-native-safe-area-context")
```
react-native dependencies been *automatically imported for years* by the last line of `app/build.gradle`:
```
apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
```

**Comment by UnderTheMoonspell** [comment]
@christocracy thanks for the tips. Will investigate and post updates here.

**Comment by christocracy** [comment]
and delete this line from `app/build.gradle`:
```
shrinkResources enableProguardInReleaseBuilds
```

**Comment by christocracy** [comment]
I suspect your app has gone through a number of *manual upgrades* of react-native version.   It's probably time for you to generate a fresh, new RN app and migrate your source code into it.  It takes a couple of hours but gets rid of all the errors you've accumulated from manually upgrading your app.

**Comment by UnderTheMoonspell** [comment]
You're right on point. We inherited the app like this, and it's quite the task to update react-native indeed.

**Comment by christocracy** [comment]
Your problem probably goes away in a freshly generated RN app.
- generate fresh RN app.
- Use [react-native-rename](https://www.npmjs.com/package/react-native-rename) to rename your app to the same as current app.
- Copy plugin `dependencies` from old `package.json`.
- Copy `index.js` and `/src` from old to new.
- Copy required Android `AndroidManifest` elements.
- Copy required iOS `Info.plist` elements.
- Copy app icons for both iOS / Android

**Comment by UnderTheMoonspell** [comment]
@christocracy this solved our problem:

```
-keep class org.json.**
-keepclassmembers,includedescriptorclasses class org.json.** { *; }
```

Thank you so much. This was the only thing preventing us from launching the feature. But indeed we knew already we need to create a fresh RN install, we are just lacking time/capacity.
