### ISSUE TITLE
com.facebook.react.bridge.NoSuchKeyException

### ISSUE THREAD

**Issue by rabbiss** [transistorsoft/react-native-background-geolocation#1965]
## Your Environment
* Plugin version: 4.14.6
* Platform: Android
* OS version: Android 13 (SDK 33)
* Device manufacturer / model: OnePlus OP555BL1
* React Native version (`react-native -v`): 0.72.6
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
export const pluginConfigObject: Config = {
    reset: true,
    geofenceModeHighAccuracy: false,
    allowIdenticalLocations: false,
    debug: false,
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    disableLocationAuthorizationAlert: true,
    disableStopDetection: true,
    distanceFilter: 10,
    disableElasticity: false,
    elasticityMultiplier: 1,
    foregroundService: true,
    logLevel: BackgroundGeolocation.LOG_LEVEL_ERROR
    locationAuthorizationRequest: 'WhenInUse',
    stopOnTerminate: false,
    startOnBoot: true,
    enableHeadless: true,
    stationaryRadius: 200,
    stopTimeout: 1,
};
```

## Expected Behavior
No crashes or exceptions.

## Actual Behavior
App crash on com.facebook.react.bridge.NoSuchKeyException

## Steps to Reproduce
Reported by Android vitals, so unfortunately no debug logs available. I have not been able to reproduce this issue while debugging either.

## Context
I have this stacktrace from Android vitals:
```
Exception com.facebook.react.bridge.NoSuchKeyException: latitude
  at com.facebook.react.bridge.ReadableNativeMap.getValue (ReadableNativeMap.java:113)
  at com.facebook.react.bridge.ReadableNativeMap.getValue (ReadableNativeMap.java:117)
  at com.facebook.react.bridge.ReadableNativeMap.getDouble (ReadableNativeMap.java:154)
  at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.buildGeofence (RNBackgroundGeolocationModule.java:702)
  at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.addGeofences (RNBackgroundGeolocationModule.java:682)
  at java.lang.reflect.Method.invoke
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:188)
  at com.facebook.jni.NativeRunnable.run
  at android.os.Handler.handleCallback (Handler.java:942)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:27)
  at android.os.Looper.loopOnce (Looper.java:240)
  at android.os.Looper.loop (Looper.java:351)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:228)
  at java.lang.Thread.run (Thread.java:1012)
```

We have multiple reports, right now hundreds of devices affected. Just wondering if you can point me in the right direction, as I don't know where to start looking for the problem.

No such key exception points to latitude. I have checked our geofence methods on the Javascript side, and "latitude" is always defined (it's a fixed value, so no chance of being undefined):

```
await BackgroundGeolocation.addGeofence({
    identifier: "mock_identifier",
    radius: 200,
    latitude: 60.123123123,
    longitude: 24.123123123,
    notifyOnEntry: true,
    notifyOnExit: false,
    notifyOnDwell: false,
})
```

I know this isn't much, but any help would be appreciated!

**Comment by christocracy** [comment]
>  at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.buildGeofence (RNBackgroundGeolocationModule.java:702)

[Line 702](https://github.com/transistorsoft/react-native-background-geolocation/blob/230b5ce4da3655662eca4ee20775816dc4e552c0/android/src/main/java/com/transistorsoft/rnbackgroundgeolocation/RNBackgroundGeolocationModule.java#L702)

```java
if (config.hasKey("latitude"))         { builder.setLatitude(config.getDouble("latitude")); }
```

Crashes here within react-native's [`ReadableMap.getValue`](https://github.com/facebook/react-native/blob/7a00623947f559741a1448a7dde1deea43558fd2/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReadableNativeMap.java#L113).

Can you reproduce this?

**Comment by christocracy** [comment]
I added your code into my *SampleApp*.  The geofence is successfully created and monitored.  

The *SampleApp* uses `"react-native": "0.73.0",`

```javascript
await BackgroundGeolocation.addGeofence({
    identifier: "mock_identifier",
    radius: 200,
    latitude: 60.123123123,
    longitude: 24.123123123,
    notifyOnEntry: true,
    notifyOnExit: false,
    notifyOnDwell: false,
})
```

```console
03-12 11:08:09.830  9179  9179 D TSLocationManager: ╔═════════════════════════════════════════════
03-12 11:08:09.830  9179  9179 D TSLocationManager: ║ TSGeofenceManager monitoring 1/1
03-12 11:08:09.830  9179  9179 D TSLocationManager: ╠═════════════════════════════════════════════
03-12 11:08:09.830  9179  9179 D TSLocationManager: ╟─ 🎾  mock_identifier
03-12 11:08:09.830  9179  9179 D TSLocationManager: ╚═════════════════════════════════════════════
```

I see it in the wilderness of Suomi (small green circle).

![IMG_0621](https://github.com/transistorsoft/react-native-background-geolocation/assets/14999/e5f2f112-d40e-4b76-8d87-6eaa1de716fa)

**Comment by christocracy** [comment]
Check your code:  you **MUST** be setting `latitude: null` somewhere.  I can reproduce with the following:

```javascript
await BackgroundGeolocation.addGeofence({
        identifier: "mock_identifier",
        radius: 200,
        latitude: null, // <---------------------- null
        longitude: 24.123123123,
        notifyOnEntry: true,
        notifyOnExit: false,
        notifyOnDwell: false,
})
```

```console
03-12 11:21:42.253 11566 11609 E AndroidRuntime: com.facebook.react.bridge.NoSuchKeyException: latitude
03-12 11:21:42.253 11566 11609 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:113)
03-12 11:21:42.253 11566 11609 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:117)
03-12 11:21:42.253 11566 11609 E AndroidRuntime: 	at com.facebook.react.bridge.ReadableNativeMap.getDouble(ReadableNativeMap.java:154)
03-12 11:21:42.253 11566 11609 E AndroidRuntime: 	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.buildGeofence(RNBackgroundGeolocationModule.java:702)
```

**Comment by rabbiss** [comment]
Yes, I can now reproduce the error with debugger connected. It is a safe bet that this null value is a bug in the code. Thanks for investigating!
