### ISSUE TITLE
Crash on getCurrentPosition with NullPointerException when calling com.getcapacitor.JSObject.has

### ISSUE THREAD

**Issue by josiahbryan** [transistorsoft/react-native-background-geolocation#2139]
## Your Environment
* Plugin version: 6.1.0 **(Using CapacitorJS 6.0.0)**
* Platform: Android
* OS version: 14
* Device manufacturer / model: Google Pixel 9 Pro XL
* React Native version (`react-native -v`): N/A
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
const baseNativeConfig = {
	// Geolocation Config
	desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
	distanceFilter: 1,
	preventSuspend: true,
	// Activity Recognition
	stopTimeout: 1,
	// Application config
	debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
	logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
	stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
	startOnBoot: false, // <-- Auto start tracking when device is powered-up.
	// HTTP / SQLite config
	batchSync: false, // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
	autoSync: true, // <-- [Default: true] Set true to sync each location to server as it arrives.

	foregroundService: true,
	notification: {
		channelName: 'Vaya GPS',
		title: 'Vaya is using your location',
		text: 'Safety and enhanced member experiences are important to Vaya',
		//   "Vaya uses your location while you're wait ing for a ride or riding in the car in order to keep you safe and enhance your ride experience",
		smallIcon: 'drawable/push_icon',
		// largeIcon: 'drawable/push_icon',
		color: `#${MAP_BRAND_COLOR_RAW_HEX}`,
		// Notification strongly weighted to bottom of list; notification-bar icon hidden
		// https://transistorsoft.github.io/capacitor-background-geolocation/interfaces/notification.html#priority
		priority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
		// TODO: Custom layout? https://transistorsoft.github.io/capacitor-background-geolocation/interfaces/notification.html#layout
		// https://github.com/transistorsoft/capacitor-background-geolocation/wiki/Android-Custom-Notification-Layout
	},

	// Update 20230905 for valet stuff
	// Changing auth req from 'Always' to 'WhenInUse' so we start more gently.
	// Then when we need live tracking, we can then request 'Always' later
	// Docs: https://transistorsoft.github.io/capacitor-background-geolocation/interfaces/config.html#locationauthorizationrequest
	// locationAuthorizationRequest: 'Always',
	locationAuthorizationRequest: 'WhenInUse',

	// Android 11+ requires:
	backgroundPermissionRationale: {
		title:
			"Allow {applicationName} to access to this device's location in the background?",
		message:
			'In order to accurately members and drivers and to ensure your safety in the background, please enable {backgroundPermissionOptionLabel} location permission',
		positiveAction: 'Change to {backgroundPermissionOptionLabel}',
		negativeAction: 'Cancel',
	},
	// // customize post properties
	// postTemplate: {
	// 	lat: '@latitude',
	// 	lng: '@longitude',
	// 	accuracy: '@accuracy',
	// 	// Added to attempt server-side walk/run/drive detection
	// 	speed: '@speed',
	// 	altitude: '@altitude',
	// 	bearing: '@bearing',
	// 	// built above from deviceInfo()
	// 	sensor,
	// },
};

BackgroundGeolocation.ready(baseNativeConfig);
```

## Expected Behavior
App should not crash

## Actual Behavior
App crashes

## Steps to Reproduce

1. Config plugin using `.ready` (see above)
2. Update config later before starting with authorization token and other settings:
```javascript
const state = await BackgroundGeolocation.setConfig(
			(bgConfig = {
				...baseNativeConfig,
				extras: {
					// <-- Optional meta-data appended to each recorded location.
					sensor,
					// For correlating on the server to a given device and via datadog
					clientTransactionId: `${transactionPrefix}.native`,
				},
				url: gpsWorkerPostUrl, // `${urlRoot}/api/v1/store-gps-location`,
				// syncUrl: `${server.urlRoot}/api/v1/store-gps-location`,
				// syncThreshold: 1,
				headers: {
					// We should have token by now because
					Authorization: token,
				},
			}),
		)
```
3. Start the plugin if not enabled
```javascript
if (!state.enabled) {
					// //
					// 3. Start tracking!
					//
					await BackgroundGeolocation.start()
						.then(() => {
							console.log('[start] success');
						})
						.catch((ex) => {
							console.error(
								`[start] Error calling BackgroundGeolocation.start:`,
								{
									message: ex.message,
									originalException: ex,
									...ex,
								},
							);
						});
				}

```

5. Call `.getCurrentPosition`:
```javascript
location = await BackgroundGeolocation.getCurrentPosition({
				timeout: 30, // 30 second timeout to fetch location
				maximumAge: 5000, // Accept the last-known-location if not older than 5000 ms.
				desiredAccuracy: 10, // Try to fetch a location with an accuracy of `10` meters.
				samples: 3, // How many location samples to attempt.
			}).catch((error) => {
				hasError = error;
				this.logNativeGpsError(error);
			});
```
6. App crashes at:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.getcapacitor.JSObject.has(java.lang.String)' on a null object reference
...at com.transistorsoft.bggeo.capacitor.BackgroundGeolocationPlugin.getCurrentPosition(BackgroundGeolocationPlugin.java:376)
```

## Context
Calling `BackgroundGeolocation.getCurrentPosition(...)`

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->

2024-09-08 15:50:11.871  9515-9817  Capacitor/Plugin        com.vayadriving                      V  To native (Capacitor plugin): callbackId: 92551827, pluginId: BackgroundGeolocation, methodName: ready
2024-09-08 15:50:11.874  9515-9817  Capacitor               com.vayadriving                      V  callback: 92551827, pluginId: BackgroundGeolocation, methodName: ready, methodData: {"options":{"desiredAccuracy":-1,"distanceFilter":1,"preventSuspend":true,"stopTimeout":1,"debug":false,"logLevel":5,"stopOnTerminate":false,"startOnBoot":false,"batchSync":false,"autoSync":true,"foregroundService":true,"notification":{"channelName":"Vaya GPS","title":"Vaya is using your location","text":"Safety and enhanced member experiences are important to Vaya","smallIcon":"drawable\/push_icon","color":"#B5479B","priority":-2},"locationAuthorizationRequest":"WhenInUse","backgroundPermissionRationale":{"title":"Allow {applicationName} to access to this device's location in the background?","message":"In order to accurately members and drivers and to ensure your safety in the background, please enable {backgroundPermissionOptionLabel} location permission","positiveAction":"Change to {backgroundPermissionOptionLabel}","negativeAction":"Cancel"}}}
2024-09-08 15:50:11.879  9515-9817  Capacitor/Plugin        com.vayadriving                      V  To native (Capacitor plugin): callbackId: 92551828, pluginId: BackgroundGeolocation, methodName: stop
2024-09-08 15:50:11.879  9515-9817  Capacitor               com.vayadriving                      V  callback: 92551828, pluginId: BackgroundGeolocation, methodName: stop, methodData: {}
2024-09-08 15:50:11.894  9515-9515  Capacitor/Console       com.vayadriving                      I  File: https://vaya-dev-client.ngrok.io/static/js/src_App_js.chunk.js - Line 16306 - Msg: Connecting Native GPS Logger with GPS Worker Path: https://vaya-dev-gps.ngrok.io/api/reflect/634e4096-ea3c-43a1-879e-9c041c729979/store
2024-09-08 15:50:11.897  9515-9817  Capacitor/Plugin        com.vayadriving                      V  To native (Capacitor plugin): callbackId: 92551829, pluginId: BackgroundGeolocation, methodName: addListener
2024-09-08 15:50:11.897  9515-9817  Capacitor               com.vayadriving                      V  callback: 92551829, pluginId: BackgroundGeolocation, methodName: addListener, methodData: {"eventName":"location"}
2024-09-08 15:50:11.903  9515-9817  Capacitor/Plugin        com.vayadriving                      V  To native (Capacitor plugin): callbackId: 92551830, pluginId: BackgroundGeolocation, methodName: setConfig
2024-09-08 15:50:11.906  9515-9817  Capacitor               com.vayadriving                      V  callback: 92551830, pluginId: BackgroundGeolocation, methodName: setConfig, methodData: {"options":{"desiredAccuracy":-1,"distanceFilter":1,"preventSuspend":true,"stopTimeout":1,"debug":false,"logLevel":5,"stopOnTerminate":false,"startOnBoot":false,"batchSync":false,"autoSync":true,"foregroundService":true,"notification":{"channelName":"Vaya GPS","title":"Vaya is using your location","text":"Safety and enhanced member experiences are important to Vaya","smallIcon":"drawable\/push_icon","color":"#B5479B","priority":-2},"locationAuthorizationRequest":"WhenInUse","backgroundPermissionRationale":{"title":"Allow {applicationName} to access to this device's location in the background?","message":"In order to accurately members and drivers and to ensure your safety in the background, please enable {backgroundPermissionOptionLabel} location permission","positiveAction":"Change to {backgroundPermissionOptionLabel}","negativeAction":"Cancel"},"extras":{"sensor":"phone.native","clientTransactionId":"dtc6xiq72t6f491lxh0gh9d0rg.s18.native"},"url":"https:\/\/vaya-dev-gps.ngrok.io\/api\/reflect\/634e4096-ea3c-43a1-879e-9c041c729979\/store","headers":{"Authorization":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzRlNDA5Ni1lYTNjLTQzYTEtODc5ZS05YzA0MWM3Mjk5NzkiLCJhbiI6bnVsbCwidGVuYW50SWQiOiJ2YXlhIiwiaWF0IjoxNzI1ODI4NTQ1fQ.9KsFjwmyeqrmpxfqdN9Pjf2O51um99Uj3Du_uRPXYIM"}}}
2024-09-08 15:50:11.911  9515-9741  TSLocationManager       com.vayadriving                      D  [c.t.l.adapter.TSConfig e] ℹ️   Persist config, dirty: [backgroundPermissionRationale, backgroundPermissionRationale.title, backgroundPermissionRationale.message, backgroundPermissionRationale.positiveAction, backgroundPermissionRationale.negativeAction, desiredAccuracy, distanceFilter, headlessJobService, locationAuthorizationRequest, logLevel, notification, notification.title, notification.text, notification.color, notification.smallIcon, notification.priority, notification.channelName, stopOnTerminate, stopTimeout]
2024-09-08 15:50:11.916  9515-9741  Settings                com.vayadriving                      W  Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
2024-09-08 15:50:11.920  9515-9741  TSLocationManager       com.vayadriving                      D  [c.t.l.u.LocationAuthorization withBackgroundPermission] 
                                                                                                      ℹ️  LocationAuthorization: Permission granted
2024-09-08 15:50:11.922  9515-9790  TSLocationManager       com.vayadriving                      I  - Enable: true → true, trackingMode: 1
2024-09-08 15:50:11.924  9515-9741  Settings                com.vayadriving                      W  Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
2024-09-08 15:50:11.928  9515-9790  TSLocationManager       com.vayadriving                      D  [c.t.l.http.HttpService startMonitoringConnectivityChanges] 
                                                                                                      🎾  Start monitoring connectivity changes
2024-09-08 15:50:11.929  9515-9741  TSLocationManager       com.vayadriving                      D  [c.t.l.adapter.TSConfig e] ℹ️   Persist config, dirty: [extras, headers, url]
2024-09-08 15:50:11.930  9515-9790  TSLocationManager       com.vayadriving                      D  [c.t.l.device.DeviceSettings startMonitoringPowerSaveChanges] 
                                                                                                      🎾  Start monitoring powersave changes
2024-09-08 15:50:11.934  9515-17949 TSLocationManager       com.vayadriving                      D  [c.t.l.l.TSLocationManager a] 
                                                                                                      ℹ️  Clear last odometer location
2024-09-08 15:50:11.935  9515-17950 TSLocationManager       com.vayadriving                      I  [c.t.l.http.HttpService flush] 
                                                                                                    ╔═════════════════════════════════════════════
                                                                                                    ║ HTTP Service (count: 0)
                                                                                                    ╠═════════════════════════════════════════════
2024-09-08 15:50:11.936  9515-17949 TSLocationManager       com.vayadriving                      I  [c.t.l.s.ActivityRecognitionService stop] 
                                                                                                      🔴  Stop motion-activity updates
2024-09-08 15:50:11.936  9515-17951 TSLocationManager       com.vayadriving                      D  [c.t.l.g.TSGeofenceManager c] 
                                                                                                      🔴  Stop monitoring geofences
2024-09-08 15:50:11.937  9515-9790  TSLocationManager       com.vayadriving                      I  [c.t.l.s.ActivityRecognitionService start] 
                                                                                                      🎾  Start motion-activity updates
2024-09-08 15:50:11.940  9515-9515  Capacitor/Console       com.vayadriving                      I  File: https://vaya-dev-client.ngrok.io/static/js/src_App_js.chunk.js - Line 16326 - Msg: Received background GPS state after config start: [object Object]
2024-09-08 15:50:11.941  9515-9515  Capacitor/Console       com.vayadriving                      I  File: https://vaya-dev-client.ngrok.io/static/js/src_App_js.chunk.js - Line 16327 - Msg: BackgroundGeolocation is configured and ready to use  false https://vaya-dev-api.ngrok.io [object Object]
2024-09-08 15:50:11.941  9515-9817  Capacitor/Plugin        com.vayadriving                      V  To native (Capacitor plugin): callbackId: 92551831, pluginId: BackgroundGeolocation, methodName: start
2024-09-08 15:50:11.942  9515-9817  Capacitor               com.vayadriving                      V  callback: 92551831, pluginId: BackgroundGeolocation, methodName: start, methodData: {}
2024-09-08 15:50:11.942  9515-9741  TSLocationManager       com.vayadriving                      D  [c.t.l.u.LocationAuthorization withBackgroundPermission] 
                                                                                                      ℹ️  LocationAuthorization: Permission granted
2024-09-08 15:50:11.944  9515-17951 TSLocationManager       com.vayadriving                      I  - Enable: false → true, trackingMode: 1
2024-09-08 15:50:11.944  9515-17949 TSLocationManager       com.vayadriving                      I  [c.t.l.service.HeartbeatService stop] 
                                                                                                      🔴  Stop heartbeat
2024-09-08 15:50:11.945  9515-17951 TSLocationManager       com.vayadriving                      I  [c.t.l.g.TSGeofenceManager start] 
                                                                                                      🎾  Start monitoring geofences
2024-09-08 15:50:11.946  9515-17949 TSLocationManager       com.vayadriving                      D  [c.t.l.http.HttpService stopMonitoringConnectivityChanges] 
                                                                                                      🔴  Stop monitoring connectivity changes
2024-09-08 15:50:11.946  9515-17951 TSLocationManager       com.vayadriving                      D  [c.t.l.http.HttpService startMonitoringConnectivityChanges] 
                                                                                                      🎾  Start monitoring connectivity changes
2024-09-08 15:50:11.946  9515-17951 TSLocationManager       com.vayadriving                      D  [c.t.l.device.DeviceSettings startMonitoringPowerSaveChanges] 
                                                                                                      🎾  Start monitoring powersave changes
2024-09-08 15:50:11.946  9515-17951 TSLocationManager       com.vayadriving                      I  [c.t.l.s.ActivityRecognitionService start] 
                                                                                                      🎾  Start motion-activity updates
2024-09-08 15:50:11.947  9515-17949 TSLocationManager       com.vayadriving                      D  [c.t.l.device.DeviceSettings stopMonitoringPowerSaveChanges] 
                                                                                                      🔴  Stop monitoring powersave changes
2024-09-08 15:50:11.948  9515-9790  TSLocationManager       com.vayadriving                      I  [c.t.l.service.HeartbeatService stop] 
                                                                                                      🔴  Stop heartbeat
2024-09-08 15:50:11.948  9515-17951 TSLocationManager       com.vayadriving                      I  [c.t.l.service.HeartbeatService stop] 
                                                                                                      🔴  Stop heartbeat
2024-09-08 15:50:11.949  9515-17951 TSLocationManager       com.vayadriving                      I  [c.t.l.service.TrackingService changePace] 
                                                                                                      🔵  setPace: false → false
2024-09-08 15:50:11.959  9515-9515  TSLocationManager       com.vayadriving                      W  [c.t.l.l.TSLocationManager onSingleLocationResult] 
                                                                                                      ℹ️  Failed to find SingleLocationRequest.  Request ignored.
2024-09-08 15:50:11.966  9515-9515  TSLocationManager       com.vayadriving                      I  [c.t.l.l.TSLocationManager a] 
                                                                                                    ╔═════════════════════════════════════════════
                                                                                                    ║ motionchange LocationResult: 2 (4521ms old)
                                                                                                    ╠═════════════════════════════════════════════
                                                                                                    ╟─ 📍  Location[fused 30.267428,-97.749637 hAcc=12.634 et=+2m8s33ms alt=217.70001220703125 vAcc=1.2263803 vel=0.07759176 sAcc=1.5], time: 1725828607442
2024-09-08 15:50:11.968  9515-9515  TSLocationManager       com.vayadriving                      I  [c.t.l.l.TSLocationManager onSingleLocationResult] 
                                                                                                      🔵  Acquired motionchange position, isMoving: false
2024-09-08 15:50:11.969  9515-9515  TSLocationManager       com.vayadriving                      D  [c.t.l.l.TSLocationManager a] Median accuracy: 12.634
2024-09-08 15:50:11.993  9515-9515  Capacitor/...tionPlugin com.vayadriving                      V  Notifying listeners for event location
2024-09-08 15:50:11.994  9515-9515  TSLocationManager       com.vayadriving                      D  [c.t.l.g.TSGeofenceManager startMonitoringStationaryRegion] 
                                                                                                      ℹ️  Cannot monitor stationary-region with 'WhenInUse' authorization
2024-09-08 15:50:11.994  9515-17951 TSLocationManager       com.vayadriving                      I  [c.t.l.d.s.SQLiteLocationDAO persist] 
                                                                                                      ✅  INSERT: bb118fd5-e591-4d51-9e2e-dd537d481d81
2024-09-08 15:50:11.997  9515-17951 TSLocationManager       com.vayadriving                      I  [c.t.l.http.HttpService flush] 
                                                                                                    ╔═════════════════════════════════════════════
                                                                                                    ║ HTTP Service (count: 1)
                                                                                                    ╠═════════════════════════════════════════════
2024-09-08 15:50:11.998  9515-9515  Capacitor/Console       com.vayadriving                      I  File: https://vaya-dev-client.ngrok.io/static/js/src_App_js.chunk.js - Line 16333 - Msg: [start] success
2024-09-08 15:50:12.001  9515-9817  Capacitor/Plugin        com.vayadriving                      V  To native (Capacitor plugin): callbackId: 92551832, pluginId: BackgroundGeolocation, methodName: getCurrentPosition
2024-09-08 15:50:12.001  9515-9817  Capacitor               com.vayadriving                      V  callback: 92551832, pluginId: BackgroundGeolocation, methodName: getCurrentPosition, methodData: {"timeout":30,"maximumAge":5000,"desiredAccuracy":10,"samples":3}
2024-09-08 15:50:12.004  9515-9741  Capacitor               com.vayadriving                      E  Serious error executing plugin
                                                                                                    java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:821)
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:85)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.getcapacitor.JSObject.has(java.lang.String)' on a null object reference
                                                                                                    	at com.transistorsoft.bggeo.capacitor.BackgroundGeolocationPlugin.getCurrentPosition(BackgroundGeolocationPlugin.java:376)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:821) 
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:85) 
--------- beginning of crash
2024-09-08 15:50:12.014  9515-9515  Capacitor/Console       com.vayadriving                      I  File: https://vaya-dev-client.ngrok.io/static/js/src_App_js.chunk.js - Line 16268 - Msg: [BackgroundGeolocation.onLocation] [object Object] [object Object]
2024-09-08 15:50:12.015  9515-9741  AndroidRuntime          com.vayadriving                      E  FATAL EXCEPTION: CapacitorPlugins
                                                                                                    Process: com.vayadriving, PID: 9515
                                                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:830)
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:85)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:821)
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:85) 
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.getcapacitor.JSObject.has(java.lang.String)' on a null object reference
                                                                                                    	at com.transistorsoft.bggeo.capacitor.BackgroundGeolocationPlugin.getCurrentPosition(BackgroundGeolocationPlugin.java:376)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:821) 
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:85) 
2024-09-08 15:50:12.018  9515-9515  TSLocationManager       com.vayadriving                      D  [c.t.l.service.AbstractService a] 
                                                                                                      🎾  motionchange [TrackingService  startId: 1, eventCount: 1]
2024-09-08 15:50:12.019  9515-9515  TSLocationManager       com.vayadriving                      I  [c.t.l.service.TrackingService k] 
                                                                                                    ╔═════════════════════════════════════════════
                                                                                                    ║ TrackingService motionchange: false
                                                                                                    ╠═════════════════════════════════════════════
2024-09-08 15:50:12.021  9515-9515  TSLocationManager       com.vayadriving                      D  [c.t.l.service.AbstractService a] 
                                                                                                      ⚙️︎   FINISH [TrackingService startId: 1, eventCount: 0, sticky: false]
2024-09-08 15:50:12.023  9515-9741  TSLocationManager       com.vayadriving                      E  [c.t.l.a.BackgroundGeolocation$w0 uncaughtException] 
                                                                                                      ‼️  Uncaught Exception: java.lang.reflect.InvocationTargetException
                                                                                                    {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"authorization":{},"autoSync":true,"autoSyncThreshold":0,"backgroundPermissionRationale":{"title":"Allow {applicationName} to access to this device's location in the background?","message":"In order to accurately members and drivers and to ensure your safety in the background, please enable {backgroundPermissionOptionLabel} location permission","positiveAction":"Change to {backgroundPermissionOptionLabel}","negativeAction":"Cancel"},"batchSync":false,"configUrl":"","crashDetector":{"enabled":false,"accelerometerThresholdHigh":20,"accelerometerThresholdLow":4.5,"gyroscopeThresholdHigh":20,"gyroscopeThresholdLow":4.5},"debug":false,"deferTime":0,"desiredAccuracy":-1,"desiredOdometerAccuracy":100,"disableAutoSyncOnCellular":false,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableMotionActivityUpdates":false,"disableProviderChangeRecord":false,"disableStopDetection":false,"distanceFilter":1,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"extras":{"sensor":"phone.native","clientTransactionId":"dtc6xiq72t6f491lxh0gh9d0rg.s18.native"},"fastestLocationUpdateInterval":-1,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{"Authorization":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzRlNDA5Ni1lYTNjLTQzYTEtODc5ZS05YzA0MWM3Mjk5NzkiLCJhbiI6bnVsbCwidGVuYW50SWQiOiJ2YXlhIiwiaWF0IjoxNzI1ODI4NTQ1fQ.9KsFjwmyeqrmpxfqdN9Pjf2O51um99Uj3Du_uRPXYIM"},"headlessJobService":"com.vayadriving.BackgroundGeolocationHeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationAuthorizationRequest":"WhenInUse","locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":5,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxMonitoredGeofences":97,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"motionTriggerDelay":0,"notification":{"layout":"","title":"Vaya is using your location","text":"Safety and enhanced member experiences are important to Vaya","color":"#B5479B","channelName":"Vaya GPS","channelId":"","smallIcon":"drawable\/push_icon","largeIcon":"","priority":-2,"sticky":false,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":false,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":1,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"https:\/\/vaya-dev-gps.ngrok.io\/api\/reflect\/634e4096-ea3c-43a1-879e-9c041c729979\/store","useSignificantChangesOnly":false,"enabled":true,"schedulerEnabled":false,"trackingMode":1,"odometer":2752.947509765625,"isFirstBoot":false,"didLaunchInBackground":false,"didDeviceReboot":false}
                                                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:830)
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:85)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException: null
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:821)
                                                                                                    	... 7 common frames omitted
2024-09-08 15:50:12.023  9515-9741  TSLocationManager       com.vayadriving                      E  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.getcapacitor.JSObject.has(java.lang.String)' on a null object reference
                                                                                                    	at com.transistorsoft.bggeo.capacitor.BackgroundGeolocationPlugin.getCurrentPosition(BackgroundGeolocationPlugin.java:376)
                                                                                                    	... 10 common frames omitted
2024-09-08 15:50:12.030  9515-17953 Compatibil...geReporter com.vayadriving                      D  Compat change id reported: 194532703; UID 10500; state: ENABLED
2024-09-08 15:50:12.031  9515-17953 Compatibil...geReporter com.vayadriving                      D  Compat change id reported: 253665015; UID 10500; state: ENABLED
2024-09-08 15:50:12.031  9515-17953 Compatibil...geReporter com.vayadriving                      D  Compat change id reported: 311402873; UID 10500; state: DISABLED
2024-09-08 15:50:12.031  9515-17953 Compatibil...geReporter com.vayadriving                      D  Compat change id reported: 323349338; UID 10500; state: DISABLED
2024-09-08 15:50:12.043  9515-9741  Process                 com.vayadriving                      I  Sending signal. PID: 9515 SIG: 9
---------------------------- PROCESS ENDED (9515) for package com.vayadriving ----------------------------
```

</details>

**Comment by christocracy** [comment]
You're not posting to the correct Github repo.  This is the *React Native* version.  There are **four different** versions of this plugin:
- *Cordova*
- *Capacitor*
- *React Native* (this repo)
- *Flutter*

Please repost at the correct GIthub repo:  https://github.com/transistorsoft/capacitor-background-geolocation

<img width="1185" alt="Screenshot 2024-09-09 at 11 49 16 AM" src="https://github.com/user-attachments/assets/3eadadd6-373d-45e7-918e-8af46391bb5b">

**Comment by josiahbryan** [comment]
Apologies, my bad, that's what I get for posting after 4 straight hours of debugging - sorry about that. Will do right now.
