### ISSUE TITLE
[Expo][Android] App Crashes on Load: java.lang.ClassCastException: org.slf4j.helpers.NOPLogger cannot be cast to ch.qos.logback.classic.Logger

### ISSUE THREAD

**Issue by rob-glazier** [transistorsoft/react-native-background-geolocation#2152]
I looked at all the issues related to this error and tried to follow the solutions for them with no success. The closest example I could find was this [issue](https://github.com/transistorsoft/react-native-background-geolocation/issues/1675) and the solution did not work for me. 

## Your Environment
* Plugin version: 4.16.6
* Platform: Android
* OS version: Android 14
* Device manufacturer / model: Pixel 8 Pro
* React Native version (`react-native -v`): 0.73.6
* Plugin config: N/A - This was removed and the app still crashes

## Expected Behavior
The app should load without crashing.

## Actual Behavior
The app crashes right as the splash screen disappears. The logs show this error dozens of times: `java.lang.ClassCastException: org.slf4j.helpers.NOPLogger cannot be cast to ch.qos.logback.classic.Logger`

## Context

I removed all of the Typescript code that uses `react-native-background-geolocation` and it still crashes on app startup when `react-native-background-geolocation` is only located in the `package.json` and the `app.config.ts`. If I remove `react-native-background-geolocation` fully, the app does not crash.

## Code
<details><summary>app.config.ts</summary>

```
plugins: [
                ...
		[
			'react-native-background-geolocation',
			{
				license: 'OUR_LICENSE_KEY',
			},
		],
		[
			'expo-gradle-ext-vars',
			{
				googlePlayServicesLocationVersion: '21.1.0',
				appCompatVersion: '1.4.2',
				logbackVersion: '2.0.1',
				slf4jVersion: '1.7.36',
			},
		],
```
</details>

<details><summary>package.json</summary>

```
"dependencies": {
		"@clerk/clerk-expo": "^0.19.22",
		"@datadog/mobile-react-native": "^2.3.2",
		"@datadog/mobile-react-navigation": "^2.3.2",
		"@emotion/react": "^11.11.3",
		"@fortawesome/fontawesome-svg-core": "^6.5.1",
		"@fortawesome/pro-duotone-svg-icons": "^6.5.1",
		"@fortawesome/pro-regular-svg-icons": "^6.5.1",
		"@fortawesome/pro-solid-svg-icons": "^6.5.1",
		"@fortawesome/react-native-fontawesome": "^0.3.0",
		"@gorhom/bottom-sheet": "^4.6.1",
		"@hookform/resolvers": "^3.3.4",
		"@intercom/intercom-react-native": "^7.2.0",
		"@prisma/client": "~5.2.0",
		"@react-native-async-storage/async-storage": "1.21.0",
		"@react-native-community/netinfo": "11.1.0",
		"@react-navigation/bottom-tabs": "^6.5.12",
		"@react-navigation/native": "^6.1.10",
		"@react-navigation/native-stack": "^6.9.18",
		"@tanstack/query-async-storage-persister": "^5.29.1",
		"@tanstack/react-query": "^4.0.0",
		"@tanstack/react-query-persist-client": "^5.29.0",
		"@trpc/client": "^10.44.1",
		"@trpc/react-query": "^10.44.1",
		"@trpc/server": "^10.44.1",
		"axios": "^1.6.7",
		"date-fns": "^3.6.0",
		"expo": "~50.0.20",
		"expo-auth-session": "~5.4.0",
		"expo-build-properties": "~0.11.1",
		"expo-constants": "~15.4.6",
		"expo-datadog": "~50.2.0",
		"expo-dev-client": "~3.3.12",
		"expo-document-picker": "~11.10.1",
		"expo-gradle-ext-vars": "^0.1.2",
		"expo-image-manipulator": "~11.8.0",
		"expo-image-picker": "~14.7.1",
		"expo-location": "~16.5.5",
		"expo-print": "~12.8.1",
		"expo-secure-store": "~12.8.1",
		"expo-sensors": "~12.9.1",
		"expo-status-bar": "~1.11.1",
		"expo-updates": "~0.24.13",
		"jwt-decode": "^4.0.0",
		"luxon": "^3.2.1",
		"react": "18.2.0",
		"react-dom": "^18.2.0",
		"react-error-boundary": "^4.0.13",
		"react-hook-form": "^7.50.1",
		"react-native": "0.73.6",
		"react-native-background-fetch": "^4.2.5",
		"react-native-background-geolocation": "4.16.6",
		"react-native-blob-util": "^0.19.9",
		"react-native-calendars": "^1.1303.0",
		"react-native-element-dropdown": "^2.10.4",
		"react-native-gesture-handler": "~2.14.0",
		"react-native-maps": "1.10.0",
		"react-native-pdf": "^6.7.5",
		"react-native-popup-menu": "^0.16.1",
		"react-native-reanimated": "~3.6.2",
		"react-native-safe-area-context": "4.8.2",
		"react-native-screens": "~3.29.0",
		"react-native-signature-canvas": "^4.7.2",
		"react-native-svg": "^14.1.0",
		"react-native-toast-message": "^2.2.0",
		"react-native-view-shot": "3.8.0",
		"react-native-webview": "13.6.4",
		"superjson": "^1.7.4",
		"text-encoding": "^0.7.0",
		"zod": "^3.22.4"
	},
```
</details>

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
09-26 14:42:06.361 26194 26341 E AndroidRuntime: java.lang.ClassCastException: org.slf4j.helpers.NOPLogger cannot be cast to ch.qos.logback.classic.Logger
09-26 14:42:06.361 26194 26341 E AndroidRuntime: 	at com.transistorsoft.locationmanager.logger.TSLog.a(Unknown Source:6)
09-26 14:42:06.361 26194 26341 E AndroidRuntime: 	at com.transistorsoft.locationmanager.logger.TSLog.a(Unknown Source:0)
09-26 14:42:06.361 26194 26341 E AndroidRuntime: 	at com.transistorsoft.locationmanager.logger.TSLog.$r8$lambda$3YB4RZFGV-hL2r0EClp1u86FGKM(Unknown Source:0)
09-26 14:42:06.361 26194 26341 E AndroidRuntime: 	at com.transistorsoft.locationmanager.logger.TSLog$$ExternalSyntheticLambda1.run(Unknown Source:4)
09-26 14:42:06.361 26194 26341 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
09-26 14:42:06.361 26194 26341 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
09-26 14:42:06.361 26194 26341 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
```

</details>

**Comment by christocracy** [comment]
```
$ cd android
$ ./gradlew app:dependencies
```

capture all the output and save to a text file.  Attach here.

**Comment by rob-glazier** [comment]
I am using Expo so I don't normally build on my device or have an `/android` folder. Once I have taken care of making the build locally, this is the result of `./gradlew app:dependencies`.

[output.txt](https://github.com/user-attachments/files/17155565/output.txt)

Thank you for any insights you can provide.

**Comment by christocracy** [comment]
The problem looks related to this `"@intercom/intercom-react-native": "^7.2.0"` plugin you're using, where one of its dependencies is importing and old version of [`org.slf4j-api:1.8.0-beta4`](https://mvnrepository.com/artifact/org.slf4j/slf4j-api) from *2019*.

```
|         |    +--- io.intercom.android:intercom-sdk-lightcompressor:15.10.3
|         |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.9.22 -> 2.0.0 (*)
|         |    |    +--- androidx.core:core-ktx:1.13.1 (*)
|         |    |    +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1 (*)
|         |    |    +--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1 (*)
|         |    |    \--- org.mp4parser:isoparser:1.9.56
|         |    |         +--- org.aspectj:aspectjrt:1.9.7
|         |    |         \--- org.slf4j:slf4j-api:1.8.0-beta4 //<--------- 1.8.0-beta4????
```

**Comment by christocracy** [comment]
Whoever is in-charge of this library "`org.mp4parser`" (which *Intercom* ultimately imports), should be kicked in the nuts for importing version `1.8.0-beta4` of [`slf4j-api`](https://mvnrepository.com/artifact/org.slf4j/slf4j-api), whose `1.8.0` branch never had a stable release.

<img width="969" alt="Screenshot 2024-09-27 at 9 31 33 AM" src="https://github.com/user-attachments/assets/9cadc0a2-4bd4-41be-a122-3952fc7f2b05">

**Comment by rob-glazier** [comment]
The change you suggested fixed my issue. Thank you very much. You are the best.
