### ISSUE TITLE
App is crashing - ObjectAlreadyConsumedException: Map already consumed

### ISSUE THREAD

**Issue by jakub-oone** [transistorsoft/react-native-background-geolocation#2235]
Hello Chris,

we have just released new app version with updated latest react-native 0.76.5. In Firebase Crashlytics we have lots of new crashes related to react-native-background-geolocation npm. _Fatal Exception: com.facebook.react.bridge.ObjectAlreadyConsumedException
Map already consumed_

Here is a stack trace:

Fatal Exception: com.facebook.react.bridge.ObjectAlreadyConsumedException: Map already consumed
       at com.facebook.react.bridge.NativeMap.toString(NativeMap.kt)
       at java.lang.String.valueOf(String.java:4102)
       at java.lang.StringBuilder.append(StringBuilder.java:179)
       at com.transistorsoft.rnbackgroundgeolocation.HeadlessTaskManager$Task.toString(HeadlessTaskManager.java:396)
       at com.transistorsoft.rnbackgroundgeolocation.HeadlessTask.lambda$onHeadlessEvent$2(HeadlessTask.java:107)
       at com.transistorsoft.rnbackgroundgeolocation.HeadlessTask$$ExternalSyntheticLambda2.onError(D8$$SyntheticClass)
       at com.transistorsoft.rnbackgroundgeolocation.HeadlessTaskManager$Task.onError(HeadlessTaskManager.java:391)
       at com.transistorsoft.rnbackgroundgeolocation.HeadlessTaskManager.invokeStartTask(HeadlessTaskManager.java:144)
       at com.transistorsoft.rnbackgroundgeolocation.HeadlessTaskManager.lambda$drainTaskQueue$0(HeadlessTaskManager.java:270)
       at com.transistorsoft.rnbackgroundgeolocation.HeadlessTaskManager.$r8$lambda$VRbt315bsy87r1TSkMrb-32Ptpc()
       at com.transistorsoft.rnbackgroundgeolocation.HeadlessTaskManager$$ExternalSyntheticLambda0.accept(D8$$SyntheticClass)
       at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895)
       at java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
       at com.transistorsoft.rnbackgroundgeolocation.HeadlessTaskManager.lambda$drainTaskQueue$1(HeadlessTaskManager.java:269)
       at com.transistorsoft.rnbackgroundgeolocation.HeadlessTaskManager.$r8$lambda$KUkIcjcbxNpojhfJKgicI76X1Uw()
       at com.transistorsoft.rnbackgroundgeolocation.HeadlessTaskManager$$ExternalSyntheticLambda1.run(D8$$SyntheticClass)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:255)
       at android.os.Looper.loop(Looper.java:364)
       at android.app.ActivityThread.main(ActivityThread.java:8979)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1053)

Could you please look at that? 
Thank you.

Jakub

## Your Environment
* Plugin version: 4.18.2
* Platform: Android
* OS version: Android 14
* Device manufacturer / model: Samsung /  Galaxy A52
* React Native version (`react-native -v`): 0.76.5 - old architecture
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
const state:State = await BackgroundGeolocation.ready({
     desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_MEDIUM,
    distanceFilter: 20,
    reset: true,
    debug: false,
    stopOnTerminate: false,
    stopOnStationary: false,
    startOnBoot: true,
    enableHeadless: true,
    maxDaysToPersist: 2,
    geofenceProximityRadius: 50000,
    geofenceInitialTriggerEntry: true,
    preventSuspend: true,
    disableLocationAuthorizationAlert: true,
    locationAuthorizationRequest: 'Always',
    useSignificantChangesOnly: false,
    geofenceModeHighAccuracy: false,
    logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
    });
```

## Expected Behavior
App is not crashing

## Actual Behavior
App is crashing

## Steps to Reproduce

1. Start monitore polygone
2. App is crashing on bg randomly

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by mikehardy** [comment]
Fascinating - that's unexpected, @christocracy looks like you get one-and-only-one chance to convert any of the new-arch non-primitive data structures to strings:

https://github.com/facebook/react-native/blob/44ef2c484a91aa6c72d87ba8e32c3bb34e38dac6/packages/react-native/ReactAndroid/src/main/jni/react/jni/NativeMap.cpp#L17

https://github.com/facebook/react-native/blob/44ef2c484a91aa6c72d87ba8e32c3bb34e38dac6/packages/react-native/ReactAndroid/src/main/jni/react/jni/NativeMap.cpp#L34

https://github.com/facebook/react-native/blob/44ef2c484a91aa6c72d87ba8e32c3bb34e38dac6/packages/react-native/ReactAndroid/src/main/jni/react/jni/NativeCommon.h#L30-L36

https://github.com/transistorsoft/react-native-background-geolocation/blob/7789d93ef82cbd28d9476d755f727fa34f25c1b6/android/src/main/java/com/transistorsoft/rnbackgroundgeolocation/HeadlessTaskManager.java#L396

Didn't have that on my bingo card. I've adopted this style of code in Notifee but I amended the toString so it just prints out the taskId, avoiding this partially by luck.

I looked over in background-fetch and don't see a toString on the map there so it might be local to just the implementation here and in the sibling `-android` variant https://github.com/transistorsoft/react-native-background-fetch/blob/a40287b2753fa99640067ebfe5d93501397b7b17/android/src/main/java/com/transistorsoft/rnbackgroundfetch/HeadlessTask.java#L32

**Comment by jakub-oone** [comment]
@mikehardy thank you for your quick response and fix suggestion. We are gonna do hotfix temp patch until it is solved here :-)

**Comment by Buthrakaur** [comment]
@mikehardy this app is RN 0.76.5 with old architecture still so it's probably not specifically related to the new architecture

> Fascinating - that's unexpected, @christocracy looks like you get one-and-only-one chance to convert any of the new-arch non-primitive data structures to strings

**Comment by mikehardy** [comment]
@Buthrakaur if it's not new arch then my analysis may not apply, no, but equally I'll be confused then how it happens. I did a repo search on react-native repo fir that string and that's the only spot it shows up. I encourage you to do the same to verify+cross-check me. I'll be happy to learn something new here based on your findings as it's clearly an area of current work for all of us...

**Comment by christocracy** [comment]
Thanks @mikehardy.  

Fix published to `4.18.3`.
