### ISSUE TITLE
App faills to start when running on Android

### ISSUE THREAD

**Issue by greyvugrin** [transistorsoft/react-native-background-geolocation#228]
## Your Environment
* Plugin version: 2.7.0
* Platform: Android
* OS version: 7.1.1
* Device manufacturer / model: Google / Nexus 6P
* React Native version (`react-native -v`): 0.41.2
* Plugin config:
```
{
        // Geolocation Config
        desiredAccuracy: 0,
        stationaryRadius: 25,
        distanceFilter: 10,
        // Activity Recognition
        stopTimeout: 1,
        // Application config
        debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
        // HTTP / SQLite config
        url: 'http://yourserver.com/locations',
        batchSync: false,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
        autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
        headers: {              // <-- Optional HTTP headers
          "X-FOO": "bar"
        },
        params: {               // <-- Optional HTTP params
          "auth_token": "maybe_your_server_authenticates_via_token_YES?"
        }
      }, function(state) {
        console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);

        if (!state.enabled) {
          BackgroundGeolocation.start(function() {
            console.log("- Start success");
          });
        }
      });
    }
```

## Expected Behavior
App to boot up normally, and start using this awesome plugin!

## Actual Behavior

App crashes immediately after the "Fetching JS bundle" stage of RN booting up.

## Steps to Reproduce

1. Install following Android Guide
2. Boot up app
3. App crashes

## Context

The app uses airbnb's react native maps, which has caused issues with conflicting play-services-location versions. See [here](https://github.com/mauron85/react-native-background-geolocation-example):

> Module react-native-maps v0.8.2 requires Google Play Services library version 9.4.0, we need to change node_modules/react-native-mauron85-background-geolocation/android/lib/build.gradle
> 
> dependencies {
>     ...
>     compile 'com.google.android.gms:play-services-location:9.4.0'
>     ...
> }

I tried doing the above fix in the node package, but maybe this would need to be done differently in this package because of how you bundle things.

I didn't see a list of required Android packages either so I'm wondering if what I have (mostly latest sdks) is too up to date for this, and I need an older version of a package?

Here is the full list of packages I'm using also:

```
  "dependencies": {
    "moment": "^2.17.1",
    "react": "15.4.2",
    "react-native": "0.41.2",
    "react-native-background-geolocation": "^2.7.0",
    "react-native-db-models": "^0.1.3",
    "react-native-maps": "^0.12.4"
  },
  "devDependencies": {
    "babel-jest": "18.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "18.1.0",
    "react-test-renderer": "15.4.2"
  },
```

## Debug logs

Android Logs:
```
03-14 22:43:44.840   909 12202 I ActivityManager: Killing 4091:com.whatsmyhood/u0a141 (adj 900): crash
03-14 22:43:44.840   909 12202 D ActivityManager: cleanUpApplicationRecord -- 4091
03-14 22:43:44.843   540   680 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
03-14 22:43:44.843   909 12202 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.whatsmyhood/.MainActivity (has extras)} from uid 10040 on display 0
03-14 22:43:44.863   540   680 D audio_hw_primary: enable_snd_device: snd_device(2: speaker)
03-14 22:43:44.866   540   680 D audio_hw_primary: enable_audio_route: usecase(1) apply and update mixer path: low-latency-playback speaker
03-14 22:43:44.877   909  5544 D GraphicsStats: Buffer count: 10
03-14 22:43:44.886   909 12571 E ActivityManager: applyOptionsLocked: Unknown animationType=0
03-14 22:43:44.899  4265  4265 I art     : Late-enabling -Xcheck:jni
03-14 22:43:44.902   909 12571 I ActivityManager: Start proc 4265:com.whatsmyhood/u0a141 for activity com.whatsmyhood/.MainActivity
03-14 22:43:44.968  4265  4265 V fb-UnpackingSoSource: locked dso store /data/user/0/com.whatsmyhood/lib-main
03-14 22:43:44.968  4265  4265 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.whatsmyhood/lib-main
03-14 22:43:44.968  4265  4265 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.whatsmyhood/lib-main
03-14 22:43:45.005  4265  4265 D NetworkSecurityConfig: No Network Security Config specified, using platform default
03-14 22:43:45.015   909 12205 I sensors : batch
03-14 22:43:45.021   909 12205 I nanohub : queueBatch: sensor=1, handle=1, period=66667000, latency=0
03-14 22:43:45.021   909 12205 I sensors : activate
03-14 22:43:45.023   909 12205 I nanohub : queueActivate: sensor=1, handle=1, enable=1
03-14 22:43:45.029  4265  4265 W unknown:React: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
03-14 22:43:45.030  4265  4294 W unknown:React: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
03-14 22:43:45.030  4265  4295 W unknown:React: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
03-14 22:43:45.070   909   942 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
03-14 22:43:45.079  4265  4265 I art     : Thread[1,tid=4265,Native,Thread*=0xec505400,peer=0x73f99610,"main"] recursive attempt to load library "/data/app/com.whatsmyhood-2/lib/arm/libfb.so"
03-14 22:43:45.080  4265  4265 W unknown:React: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
03-14 22:43:45.091  4265  4265 W unknown:React: Packager connection already open, nooping.
03-14 22:43:45.091  4265  4265 W unknown:React: Inspector connection already open, nooping.
03-14 22:43:45.094  4265  4305 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.maps.GoogleMapOptions>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/AbstractSafeParcelable;
03-14 22:43:45.094  4265  4305 I art     :   at void com.airbnb.android.react.maps.AirMapManager.<init>(com.facebook.react.bridge.ReactApplicationContext) (AirMapManager.java:54)
03-14 22:43:45.094  4265  4305 I art     :   at java.util.List com.airbnb.android.react.maps.MapsPackage.createViewManagers(com.facebook.react.bridge.ReactApplicationContext) (MapsPackage.java:39)
03-14 22:43:45.094  4265  4305 I art     :   at java.util.List com.facebook.react.XReactInstanceManagerImpl.createAllViewManagers(com.facebook.react.bridge.ReactApplicationContext) (XReactInstanceManagerImpl.java:699)
03-14 22:43:45.094  4265  4305 I art     :   at com.facebook.react.uimanager.UIManagerModule com.facebook.react.CoreModulesPackage.createUIManager(com.facebook.react.bridge.ReactApplicationContext) (CoreModulesPackage.java:206)
03-14 22:43:45.094  4265  4305 I art     :   at com.facebook.react.uimanager.UIManagerModule com.facebook.react.CoreModulesPackage.access$200(com.facebook.react.CoreModulesPackage, com.facebook.react.bridge.ReactApplicationContext) (CoreModulesPackage.java:71)
03-14 22:43:45.094  4265  4305 I art     :   at com.facebook.react.bridge.NativeModule com.facebook.react.CoreModulesPackage$8.get() (CoreModulesPackage.java:145)
03-14 22:43:45.094  4265  4305 I art     :   at java.lang.Object com.facebook.react.CoreModulesPackage$8.get() (CoreModulesPackage.java:142)
03-14 22:43:45.094  4265  4305 I art     :   at java.util.List com.facebook.react.LazyReactPackage.createNativeModules(com.facebook.react.bridge.ReactApplicationContext) (LazyReactPackage.java:76)
03-14 22:43:45.094  4265  4305 I art     :   at void com.facebook.react.XReactInstanceManagerImpl.processPackage(com.facebook.react.ReactPackage, com.facebook.react.bridge.ReactApplicationContext, java.util.List, java.util.Map, com.facebook.react.bridge.JavaScriptModuleRegistry$Builder) (XReactInstanceManagerImpl.java:958)
03-14 22:43:45.094  4265  4305 I art     :   at com.facebook.react.bridge.ReactApplicationContext com.facebook.react.XReactInstanceManagerImpl.createReactContext(com.facebook.react.cxxbridge.JavaScriptExecutor, com.facebook.react.cxxbridge.JSBundleLoader) (XReactInstanceManagerImpl.java:863)
03-14 22:43:45.094  4265  4305 I art     :   at com.facebook.react.bridge.ReactApplicationContext com.facebook.react.XReactInstanceManagerImpl.access$600(com.facebook.react.XReactInstanceManagerImpl, com.facebook.react.cxxbridge.JavaScriptExecutor, com.facebook.react.cxxbridge.JSBundleLoader) (XReactInstanceManagerImpl.java:110)
03-14 22:43:45.094  4265  4305 I art     :   at com.facebook.react.XReactInstanceManagerImpl$Result com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(com.facebook.react.XReactInstanceManagerImpl$ReactContextInitParams[]) (XReactInstanceManagerImpl.java:214)
03-14 22:43:45.094  4265  4305 I art     :   at java.lang.Object com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(java.lang.Object[]) (XReactInstanceManagerImpl.java:193)
03-14 22:43:45.094  4265  4305 I art     :   at java.lang.Object android.os.AsyncTask$2.call() (AsyncTask.java:305)
03-14 22:43:45.094  4265  4305 I art     :   at void java.util.concurrent.FutureTask.run() (FutureTask.java:237)
03-14 22:43:45.094  4265  4305 I art     :   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1133)
03-14 22:43:45.094  4265  4305 I art     :   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:607)
03-14 22:43:45.094  4265  4305 I art     :   at void java.lang.Thread.run() (Thread.java:761)
03-14 22:43:45.094  4265  4305 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable" on path: DexPathList[[zip file "/data/app/com.whatsmyhood-2/base.apk"],nativeLibraryDirectories=[/data/app/com.whatsmyhood-2/lib/arm, /system/fake-libs, /data/app/com.whatsmyhood-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
03-14 22:43:45.094  4265  4305 I art     :   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
03-14 22:43:45.094  4265  4305 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
03-14 22:43:45.094  4265  4305 I art     :   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
03-14 22:43:45.094  4265  4305 I art     :   at void com.airbnb.android.react.maps.AirMapManager.<init>(com.facebook.react.bridge.ReactApplicationContext) (AirMapManager.java:54)
03-14 22:43:45.094  4265  4305 I art     :   at java.util.List com.airbnb.android.react.maps.MapsPackage.createViewManagers(com.facebook.react.bridge.ReactApplicationContext) (MapsPackage.java:39)
03-14 22:43:45.094  4265  4305 I art     :   at java.util.List com.facebook.react.XReactInstanceManagerImpl.createAllViewManagers(com.facebook.react.bridge.ReactApplicationContext) (XReactInstanceManagerImpl.java:699)
03-14 22:43:45.094  4265  4305 I art     :   at com.facebook.react.uimanager.UIManagerModule com.facebook.react.CoreModulesPackage.createUIManager(com.facebook.react.bridge.ReactApplicationContext) (CoreModulesPackage.java:206)
03-14 22:43:45.094  4265  4305 I art     :   at com.facebook.react.uimanager.UIManagerModule com.facebook.react.CoreModulesPackage.access$200(com.facebook.react.CoreModulesPackage, com.facebook.react.bridge.ReactApplicationContext) (CoreModulesPackage.java:71)
03-14 22:43:45.094  4265  4305 I art     :   at com.facebook.react.bridge.NativeModule com.facebook.react.CoreModulesPackage$8.get() (CoreModulesPackage.java:145)
03-14 22:43:45.094  4265  4305 I art     :   at java.lang.Object com.facebook.react.CoreModulesPackage$8.get() (CoreModulesPackage.java:142)
03-14 22:43:45.094  4265  4305 I art     :   at java.util.List com.facebook.react.LazyReactPackage.createNativeModules(com.facebook.react.bridge.ReactApplicationContext) (LazyReactPackage.java:76)
03-14 22:43:45.094  4265  4305 I art     :   at void com.facebook.react.XReactInstanceManagerImpl.processPackage(com.facebook.react.ReactPackage, com.facebook.react.bridge.ReactApplicationContext, java.util.List, java.util.Map, com.facebook.react.bridge.JavaScriptModuleRegistry$Builder) (XReactInstanceManagerImpl.java:958)
03-14 22:43:45.094  4265  4305 I art     :   at com.facebook.react.bridge.ReactApplicationContext com.facebook.react.XReactInstanceManagerImpl.createReactContext(com.facebook.react.cxxbridge.JavaScriptExecutor, com.facebook.react.cxxbridge.JSBundleLoader) (XReactInstanceManagerImpl.java:863)
03-14 22:43:45.094  4265  4305 I art     :   at com.facebook.react.bridge.ReactApplicationContext com.facebook.react.XReactInstanceManagerImpl.access$600(com.facebook.react.XReactInstanceManagerImpl, com.facebook.react.cxxbridge.JavaScriptExecutor, com.facebook.react.cxxbridge.JSBundleLoader) (XReactInstanceManagerImpl.java:110)
03-14 22:43:45.094  4265  4305 I art     :   at com.facebook.react.XReactInstanceManagerImpl$Result com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(com.facebook.react.XReactInstanceManagerImpl$ReactContextInitParams[]) (XReactInstanceManagerImpl.java:214)
03-14 22:43:45.094  4265  4305 I art     :   at java.lang.Object com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(java.lang.Object[]) (XReactInstanceManagerImpl.java:193)
03-14 22:43:45.094  4265  4305 I art     :   at java.lang.Object android.os.AsyncTask$2.call() (AsyncTask.java:305)
03-14 22:43:45.094  4265  4305 I art     :   at void java.util.concurrent.FutureTask.run() (FutureTask.java:237)
03-14 22:43:45.094  4265  4305 I art     :   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1133)
03-14 22:43:45.094  4265  4305 I art     :   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:607)
03-14 22:43:45.094  4265  4305 I art     :   at void java.lang.Thread.run() (Thread.java:761)
03-14 22:43:45.094  4265  4305 I art     : 
03-14 22:43:45.096  4265  4305 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
03-14 22:43:45.096  4265  4305 E AndroidRuntime: Process: com.whatsmyhood, PID: 4265
03-14 22:43:45.096  4265  4305 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:325)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/GoogleMapOptions;
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:54)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl.createAllViewManagers(XReactInstanceManagerImpl.java:699)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:206)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:71)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:145)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:142)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:76)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl.processPackage(XReactInstanceManagerImpl.java:958)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl.createReactContext(XReactInstanceManagerImpl.java:863)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl.access$600(XReactInstanceManagerImpl.java:110)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:214)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.doInBackground(XReactInstanceManagerImpl.java:193)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	... 3 more
03-14 22:43:45.096  4265  4305 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.google.android.gms.maps.GoogleMapOptions
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	... 18 more
03-14 22:43:45.096  4265  4305 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/AbstractSafeParcelable;
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	... 18 more
03-14 22:43:45.096  4265  4305 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable" on path: DexPathList[[zip file "/data/app/com.whatsmyhood-2/base.apk"],nativeLibraryDirectories=[/data/app/com.whatsmyhood-2/lib/arm, /system/fake-libs, /data/app/com.whatsmyhood-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-14 22:43:45.096  4265  4305 E AndroidRuntime: 	... 18 more
03-14 22:43:45.098   909  4383 W ActivityManager:   Force finishing activity com.whatsmyhood/.MainActivity
03-14 22:43:45.120  4265  4265 W unknown:React: Caught exception after cancelling react context init
03-14 22:43:45.120  4265  4265 W unknown:React: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.facebook.react.XReactInstanceManagerImpl$Result.get()' on a null object reference
03-14 22:43:45.120  4265  4265 W unknown:React: 	at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.onCancelled(XReactInstanceManagerImpl.java:243)
03-14 22:43:45.120  4265  4265 W unknown:React: 	at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.onCancelled(XReactInstanceManagerImpl.java:193)
03-14 22:43:45.120  4265  4265 W unknown:React: 	at android.os.AsyncTask.finish(AsyncTask.java:665)
03-14 22:43:45.120  4265  4265 W unknown:React: 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
03-14 22:43:45.120  4265  4265 W unknown:React: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
03-14 22:43:45.120  4265  4265 W unknown:React: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-14 22:43:45.120  4265  4265 W unknown:React: 	at android.os.Looper.loop(Looper.java:154)
03-14 22:43:45.120  4265  4265 W unknown:React: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
03-14 22:43:45.120  4265  4265 W unknown:React: 	at java.lang.reflect.Method.invoke(Native Method)
03-14 22:43:45.120  4265  4265 W unknown:React: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
03-14 22:43:45.120  4265  4265 W unknown:React: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-14 22:43:45.121   909  2870 I sensors : activate
03-14 22:43:45.123   909  2870 I nanohub : queueActivate: sensor=1, handle=1, enable=0
03-14 22:43:45.149   909  3765 D WindowManager: relayoutVisibleWindow: Window{a826c19 u0 com.google.android.googlequicksearchbox/com.google.android.launcher.GEL EXITING} mAnimatingExit=true, mRemoveOnExit=false, mDestroying=false
03-14 22:43:45.187   909 28796 I OpenGLRenderer: Initialized EGL, version 1.4
03-14 22:43:45.187   909 28796 D OpenGLRenderer: Swap behavior 1
03-14 22:43:45.219   909   918 I art     : Background partial concurrent mark sweep GC freed 87312(3MB) AllocSpace objects, 5(96KB) LOS objects, 33% free, 27MB/41MB, paused 2.467ms total 109.861ms
03-14 22:43:45.379   540   680 D audio_hw_primary: disable_audio_route: usecase(1) reset and update mixer path: low-latency-playback speaker
03-14 22:43:45.388   540   680 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)

```

Thanks for all your work, I look forward to using the plugin!

EDIT: Looking at the logs, it seems like the culprit is most likely airbnb's maps, lmk if you see anything else in there though. I would love to see them play nicely together.

**Comment by dinesh8055** [comment]
I too have the same issue. Did you find any solution?

**Comment by christocracy** [comment]
This is not caused by the plugin.  I had a similar issue recently while implementing `react-native-maps` for my demo app.

I just posted what I did in #229

**Comment by greyvugrin** [comment]
@christocracy thanks for your write up in #229. It solved the issue for me. For anyone else struggling with this, here's the `app/build.gradle` dependencies section I ended up with:

```
dependencies {
    compile(project(':react-native-maps')) {
        exclude group: 'com.google.android.gms'
    }
    compile project(':react-native-background-geolocation')
    compile(name: 'tslocationmanager', ext: 'aar')
    // ... more packages in between
    compile ("com.google.android.gms:play-services-base:+") { // the plus allows you to use the latest version
        force = true;
    }
    compile ("com.google.android.gms:play-services-maps:+") { 
        force = true;
    }
}
```

Also if unexpected errors still show up try `cd android/ && ./gradlew clean`
