### ISSUE TITLE
NullPointerException getExtras() in locationmanager

### ISSUE THREAD

**Issue by robmoorman** [transistorsoft/react-native-background-geolocation#247]
We came across an issue raised once by your Crashlytics.

## Your Environment
* Plugin version: 2.6.1
* Platform: Android
* OS version: 6.0.1
* Device manufacturer / model: SM-G900F
* React Native version (`react-native -v`): 0.36.0
* Plugin config

## Config
```javascript
// HTTP & Persistence Options
geofenceTemplate: '{ "identifier": "<%= geofence.identifier %>", "action":"<%= geofence.action %>" }',
httpRootProperty: '.',
maxDaysToPersist: 7,
maxRecordsToPersist: 100,
url: Config.api + '/geodata/v1/geofence',
params: {
  ... // hidden for config
},

// Application Common options
stopOnTerminate: false,
startOnBoot: true,

// Application iOS options
preventSuspend: false,

// Application Android options
foregroundService: true,
notificationTitle: 'hidden_for_config',
notificationText: 'hidden_for_config',
forceReloadOnGeofence: false, // we dont want to have the app in the foreground each time a geofence is crossed
forceReloadOnSchedule: true,
forceReloadOnBoot: true,

//  Geofencing Options
geofenceProximityRadius: 250000, // make sure the geofence is always activated
geofenceInitialTriggerEntry: true,

// Logging & Debug Options
debug: false,
logLevel: 3,
logMaxDays: 3
```

## Debug logs
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.location.Location.getExtras()' on a null object reference
       at com.transistorsoft.locationmanager.location.TSLocation.initialize(Unknown Source)
       at com.transistorsoft.locationmanager.location.TSLocation.<init>(Unknown Source)
       at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source)
       at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.on(Unknown Source)
       at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.configure(RNBackgroundGeolocationModule.java:106)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:158)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by christocracy** [comment]
I'll check it out.

**Comment by christocracy** [comment]
Have you not switch to using the private repo for both iOS & Android.  This is the public repo containing only the latest stable release (typically updated only every 1-3 months).

Latest updates exist only in the private repo.

**Comment by robmoorman** [comment]
Moved to https://github.com/transistorsoft/react-native-background-geolocation-android/issues/229
