### ISSUE TITLE
Cannot read property 'configure' of undefined on Detached expo app.

### ISSUE THREAD

**Issue by arrygoo** [transistorsoft/react-native-background-geolocation#259]
## My Environment
* Plugin version: latest
* Platform: Android
* OS version: 6.1
* Device manufacturer / model:
* React Native version (`react-native -v`): 2.0.1
* Plugin config: 
```
  BackgroundGeolocation.configure(
      {
        // Geolocation Config
        desiredAccuracy: 0,
        stationaryRadius: 25,
        distanceFilter: 10,
        // Activity Recognition
        stopTimeout: 1,
        // Application config
        debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
        logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
        stopOnTerminate: false, // <-- Allow the background-service to continue tracking when user closes the app.
        startOnBoot: true, // <-- Auto start tracking when device is powered-up.
        // HTTP / SQLite config
      },
      state => {
        console.log('- BackgroundGeolocation is configured and ready: ', state.enabled);
        if (!state.enabled) {
          BackgroundGeolocation.start(() => {
            console.log('- Start success');
          });
        }
      }
    );
```

## Expected Behavior
Successfully configure the app. 

## Actual Behavior
Getting an error during configuration.

## Steps to Reproduce
1. Added the package to a detached expo app on android 
2. Followed instructions to install on android (no errors)
3. Fails during configuration. (My app is running in debug mode)

## Context
I'm trying to add this package to an existing expo detached android app

## Debug logs
```
Object Configure
RNBackgroundGeolocation.js:45:28
```

Is this error happening due to me not having the license? I have the build variant set to debug mode.
![image](https://user-images.githubusercontent.com/965429/26837967-d0793fd2-4aac-11e7-8263-011eb0970002.png)

My gradle: 
```
apply plugin: 'com.android.application'

android {
  compileSdkVersion 24
  buildToolsVersion '25.0.0'

  defaultConfig {
    applicationId "com.seamtechnic.seamapp"
    minSdkVersion 19
    targetSdkVersion 24
    versionCode 1
    versionName "1.0"
    multiDexEnabled true
    ndk {
      abiFilters 'armeabi-v7a', 'x86'
    }
    manifestPlaceholders = [
      'appAuthRedirectScheme': 'com.seamtechnic.seamapp'
    ]
  }
  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
  }
  dexOptions {
    javaMaxHeapSize "8g"
  }
}

task exponentPrebuildStep(type: Exec) {
  workingDir '../../'

  if (System.getProperty('os.name').toLowerCase().contains('windows')) {
    commandLine 'cmd', '/c', '.\\.expo-source\\android\\detach-scripts\\prepare-detached-build.bat'
  } else {
    commandLine './.expo-source/android/detach-scripts/prepare-detached-build.sh'
  }
}
preBuild.dependsOn exponentPrebuildStep

repositories{
  flatDir{
      dirs '../../node_modules/react-native-background-geolocation/android/libs'
      dirs 'libs'
  }
  mavenLocal()
  maven { url 'https://maven.fabric.io/public' }
}

dependencies {
  compile project(':react-native-background-geolocation')
  compile fileTree(dir: 'libs', include: ['*.jar'])
  testCompile 'junit:junit:4.12'
  compile 'com.android.support:appcompat-v7:24.1.1'
  compile 'com.android.support:multidex:1.0.0'
  compile(name: 'tslocationmanager', ext: 'aar')



  compile('host.exp.exponent:expoview:16.0.0@aar') {
    exclude group: 'com.facebook.android', module: 'facebook-android-sdk'
    exclude group: 'com.facebook.android', module: 'audience-network-sdk'
    exclude group: 'io.nlopez.smartlocation', module: 'library'
    transitive = true;
  }

  compile ('com.facebook.android:facebook-android-sdk:4.7.0') {
    exclude module: 'bolts-android'
  }
  compile('com.facebook.android:audience-network-sdk:4.19.0') {
    exclude module: 'play-services-ads'
  }
  compile('io.nlopez.smartlocation:library:3.2.11') {
    transitive = false
  }


}
```

**Comment by christocracy** [comment]
I have little experience with Expo and Android currently.  I'll try and have a look at this asap.

**Comment by arrygoo** [comment]
@christocracy I got pass this but crashing on what you mentioned might be google services dependency issues. 
My latest persistant error is:
```
06-07 14:44:15.188 22896 24446 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:318)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:762)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/AbstractSafeParcelable;
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at versioned.host.exp.exponent.modules.api.components.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at versioned.host.exp.exponent.ExponentPackage.addViewManagersFromPackages(ExponentPackage.java:196)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at versioned.host.exp.exponent.ExponentPackage.createViewManagers(ExponentPackage.java:183)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createAllViewManagers(ReactInstanceManager.java:711)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:218)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:74)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:151)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage$8.get(CoreModulesPackage.java:148)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:76)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:97)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:950)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:880)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:104)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground(ReactInstanceManager.java:218)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.doInBackground(ReactInstanceManager.java:197)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:304)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	... 3 more
06-07 14:44:15.188 22896 24446 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable" on path: DexPathList[[zip file "/data/app/com.seamtechnic.seamapp-1/base.apk", zip file "/data/app/com.seamtechnic.seamapp-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.seamtechnic.seamapp-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.seamtechnic.seamapp-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.seamtechnic.seamapp-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.seamtechnic.seamapp-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.seamtechnic.seamapp-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.seamtechnic.seamapp-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.seamtechnic.seamapp-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.seamtechnic.seamapp-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.seamtechnic.seamapp-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.seamtechnic.seamapp-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.seamtechnic.seamapp-1/lib/arm, /data/app/com.seamtechnic.seamapp-1/base.apk!/lib/armeabi-v7a, /data/app/com.seamtechnic.seamapp-1/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.seamtechnic.seamapp-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.seamtechnic.seamapp-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.seamtechnic.seamapp-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.seamtechnic.seamapp-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.seamtechnic.seamapp-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.seamtechnic.seamapp-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.seamtechnic.seamapp-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.seamtechnic.seamapp-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.seamtechnic.seamapp-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.seamtechnic.seamapp-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-07 14:44:15.188 22896 24446 E AndroidRuntime: 	... 20 more
06-07 14:44:15.202  3668  3681 D Debug   : !@DumpState : SHIP
06-07 14:44:15.202  3668  3681 D Debug   : !@DumpState : debug level:0x4f4c
06-07 14:44:15.202  3668  3681 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
06-07 14:44:15.217  3668  3681 W ActivityManager:   Force finishing activity com.seamtechnic.seamapp/.MainActivity
06-07 14:44:15.220  3668  3681 W MultiScreenManagerService: moveTaskBackToDisplayIfNeeded(): root is not base activity
06-07 14:44:15.221  3668 24448 W DropBoxManagerService: Dropping: data_app_crash (10 > 0 bytes)
06-07 14:44:15.238  3668  3681 D ActivityManager: moveToFront() : reason=finishActivity adjustFocus setFocusedActivity isAttached=true TaskRecord{db0248d0 #132 A=.launcher U=0 StackId=0 sz=1}
06-07 14:44:15.239  3668  3681 W MultiScreenManagerService: moveTaskBackToDisplayIfNeeded(): root activity or app is null
06-07 14:44:15.260  3668  3681 D ActivityManager: setFocusStackUnchecked: reason=finishActivity adjustFocus setFocusedActivity focusCandidate=ActivityStack{66c618ed0 stackId=0, 2 tasks} caller=com.android.server.am.ActivityStack.moveToFront:875 com.android.server.am.ActivityStackSupervisor.moveActivityStackToFront:2006
06-07 14:44:15.276  3668  3681 D InputDispatcher: Focused application set to: xxxx
06-07 14:44:15.279  3668  3681 D InputDispatcher: Focus left window: 22896
06-07 14:44:15.282 22896 22896 D ViewRootImpl@25b15dd[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0
```

**Comment by ramsestom** [comment]
@arrygoo  How did you pass this? I have the same error message ("Cannot read property 'configure' of undefined") on a regular react-native android app.

**Comment by christocracy** [comment]
Did you perform the [gradle config](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-ANDROID-RNPM.md#gradle-configuration)?

**Comment by christocracy** [comment]
Update?

**Comment by arrygoo** [comment]
@ramsestom After using `react-native-background-geolocation-android` which is the paid version I don't have this error anymore. I have some google services versions issue before getting there which I'm trying to resolve.

**Comment by rexlow** [comment]
I'm getting this on iOS. Looks like it's not referencing to the iOS library. Any help?

**Comment by christocracy** [comment]
@rexlow Show me your `Framework Search Paths`:

![](https://www.dropbox.com/s/9visl2l2mhrh7up/Screenshot%202017-06-19%2010.07.29.png?dl=1)

**Comment by rexlow** [comment]
@christocracy I have included the search path as how others do it, rebuild but its still not working

**Comment by christocracy** [comment]
Show me a screenshot of exactly what I've showed you.

**Comment by rexlow** [comment]
@christocracy Got it working, the libsqlite3.tbd was not included

**Comment by christocracy** [comment]
That was going to be my next screenshot:
![](https://www.dropbox.com/s/dwl41ok4zx4pdrv/Screenshot%202017-06-19%2010.32.55.png?dl=1)
