### ISSUE TITLE
Runtime error java.lang.NoClassDefFoundError: com.google.android.gms.location.ActivityRecognitionResult

### ISSUE THREAD

**Issue by vivekmago** [transistorsoft/react-native-background-geolocation#265]
## Your Environment
* Plugin version:
* Platform: Android
* OS version: 7.1.1
* Device manufacturer / model: Pixel
* React Native version (`react-native -v`): 0.39.2
* Plugin config
    var options = {
      desiredAccuracy: 25,
      stationaryRadius: 25,
      distanceFilter: 25,
      disableElasticity: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      locationAuthorizationRequest: 'WhenInUse',
      trackingMode: 'location',
      locationTimeout: 60,
      debug: false,
      startOnBoot: false,
      stopOnTerminate: false,
      activityType: 'AutomotiveNavigation'
    };
## Expected Behavior

App should work
## Actual Behavior

App crashes with following exception and stacktrace
stack=java.lang.NoClassDefFoundError: com.google.android.gms.location.ActivityRecognitionResult
                                            at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
                                            at java.lang.Class.getDexCacheType(Class.java:2551)
                                            at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:169)
                                            at java.lang.reflect.Method.getParameterTypes(Method.java:193)
                                            at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
                                            at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
                                            at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
                                            at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
                                            at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source)
                                            at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source)
                                            at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.getAdapter(RNBackgroundGeolocationModule.java:973)
                                            at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.initializeLocationManager(RNBackgroundGeolocationModule.java:968)
                                            at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.onHostResume(RNBackgroundGeolocationModule.java:82)
                                            at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:210)
                                            at com.facebook.react.XReactInstanceManagerImpl.moveToResumedLifecycleState(XReactInstanceManagerImpl.java:593)
                                            at com.facebook.react.XReactInstanceManagerImpl.moveReactContextToCurrentLifecycleState(XReactInstanceManagerImpl.java:968)
                                            at com.facebook.react.XReactInstanceManagerImpl.setupReactContext(XReactInstanceManagerImpl.java:775)
                                            at com.facebook.react.XReactInstanceManagerImpl.access$700(XReactInstanceManagerImpl.java:110)
                                            at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.onPostExecute(XReactInstanceManagerImpl.java:224)
                                            at com.facebook.react.XReactInstanceManagerImpl$ReactContextInitAsyncTask.onPostExecute(XReactInstanceManagerImpl.java:193)
                                            at android.os.AsyncTask.finish(AsyncTask.java:667)
                                            at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                            at android.os.Looper.loop(Looper.java:154)
                                            at android.app.ActivityThread.main(ActivityThread.java:6119)
                                            at java.lang.reflect.Method.invoke(Native Method)
                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
## Steps to Reproduce

1. Start app it crashes with 
2.
3.
4.

**Comment by christocracy** [comment]
Did you neglect the [gradle config](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-ANDROID-RNPM.md)?

**Comment by vivekmago** [comment]
Nope all as per instructions, I am using firebase with version 10.2.6 and forcing per suggestion in another issue.

here is the snippet

repositories {
    flatDir {
        dirs "../../node_modules/react-native-background-geolocation/android/libs"
    }
}

dependencies {
compile (project(':react-native-background-geolocation')){
    exclude group: 'com.google.android.gms', module: 'play-services-location'
}
compile(name: 'tslocationmanager', ext: 'aar’)
compile ('com.google.android.gms:play-services-base:10.2.6'){
    force = true;
}
compile ('com.google.android.gms:play-services-maps:10.2.6'){
    force = true;
}

}

**Comment by christocracy** [comment]
Try adding:
```
compile ("com.google.android.gms:play-services-location:10.2.6") {
    force = true;
}
```

**Comment by vivekmago** [comment]
That did the trick.. thanks for your help.. 

Cheers

**Comment by christocracy** [comment]
The missing class you're having comes from [`com.google.android.gms.location`](https://developers.google.com/android/reference/com/google/android/gms/location/package-summary)

You directed `react-native-background-geolocation` to *exclude all* of that package.

```
compile (project(':react-native-background-geolocation')){
    exclude group: 'com.google.android.gms', module: 'play-services-location'
}
```
