### ISSUE TITLE
Crashing on start with Android (Samsung S7)

### ISSUE THREAD

**Issue by stanleycyang** [transistorsoft/react-native-background-geolocation#378]
## Your Environment
* Plugin version: 2.10.1
* Platform: Android
* OS version: Android 7
* Device manufacturer / model: Samsung S7
* React Native version (`react-native -v`): 0.45.1
* Plugin config

## Expected Behavior

I went through the android setup flow. It should not crash on startup

## Actual Behavior

I am running through the install flow for android and the app now crashes on startup.
```
Fatal Exception: java.lang.IncompatibleClassChangeError: Superclass com.google.android.gms.internal.zzbej of com.google.android.gms.location.ActivityRecognitionResult is declared final (declaration of 'com.google.android.gms.location.ActivityRecognitionResult' appears in /data/app/com.forcefield-1/base.apk)
       at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.<init>(RNBackgroundGeolocationModule.java:82)
       at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocation.createNativeModules(RNBackgroundGeolocation.java:21)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1009)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:944)
       at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
       at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:746)
       at java.lang.Thread.run(Thread.java:761)
```

## Steps to Reproduce

1. Run through the setup flow for android with same configs
2. Crashes on startup

## Context

Trying to build background location for Android / iOS app

## Debug logs
```
Fatal Exception: java.lang.IncompatibleClassChangeError: Superclass com.google.android.gms.internal.zzbej of com.google.android.gms.location.ActivityRecognitionResult is declared final (declaration of 'com.google.android.gms.location.ActivityRecognitionResult' appears in /data/app/com.forcefield-1/base.apk)
       at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.<init>(RNBackgroundGeolocationModule.java:82)
       at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocation.createNativeModules(RNBackgroundGeolocation.java:21)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1009)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:944)
       at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
       at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:746)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by christocracy** [comment]
Google play services min version is 11.2.0.  You’re importing a version <11.2.0

**Comment by stanleycyang** [comment]
Are you talking about Android API version? The app is on 23. 

Isn't the OS latest 8.0 (Oreo)?

**Comment by stanleycyang** [comment]
```
    <uses-sdk
        android:minSdkVersion="21"
        android:targetSdkVersion="22" />
```

I thought the latest OS was 8.0 (Oreo)?

**Comment by christocracy** [comment]
No.  Google Play Services.

**Comment by christocracy** [comment]
See the demo app for an example of how to override Google Play Services version provided by other plugins.  Many plugins import Google Play Services / Firebase.  The tricky thing is that the imported version must be the the same for *all* plugins.

Some plugin might import `play-services-location:11.0.1`, while another might import `11.6.0`.  This will cause a dependency conflict.  An app can only import a single version of play-Services.

Post your `android/app/build.gradle`

**Comment by christocracy** [comment]
Forgot link to demo app build.gradle
https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/android/app/build.gradle#L159

**Comment by stanleycyang** [comment]
```
apply plugin: "com.android.application"

project.ext.envConfigFiles = [
        debug  : ".env.development",
        release: ".env.production",
        staging: ".env.staging",
]

project.ext.react = [
        bundleInStaging: true
]

apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"]
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        // These docs use an open ended version so that our plugin
        // can be updated quickly in response to Android tooling updates

        // We recommend changing it to the latest version from our changelog:
        // https://docs.fabric.io/android/changelog.html#fabric-gradle-plugin
        classpath 'io.fabric.tools:gradle:1.+'
    }
}

apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
    maven { url "https://jitpack.io" }
}

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 23
    buildToolsVersion '25.0.2'

    defaultConfig {
        applicationId "com.forcefield"
        minSdkVersion 21
        targetSdkVersion 22
        versionCode 20
        versionName "1.0.5"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        staging {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a": 1, "x86": 2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile 'com.github.javiersantos:AppUpdater:2.6.4'
    compile('com.squareup.okhttp3:okhttp:3.4.2') {
        force = true
    }
    compile project(':react-native-cookie')
    compile project(':react-native-sensitive-info')
    compile project(':react-native-fabric')
    compile project(':react-native-network-info')
    compile project(':react-native-fcm')
    compile 'com.google.firebase:firebase-core:10.0.1'
    compile 'com.android.volley:volley:1.0.0'
    compile 'joda-time:joda-time:2.9.9'
    compile project(':react-native-picker')
    compile project(':react-native-config')
    compile project(':react-native-send-intent')
    compile project(':react-native-mail')
    compile project(':react-native-device-info')
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile('com.crashlytics.sdk.android:crashlytics:2.7.1@aar') {
        transitive = true;
    }
    compile 'com.google.code.gson:gson:2.8.2'
    compile "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

// add this is the bottom
apply plugin: 'com.google.gms.google-services'
```

**Comment by christocracy** [comment]
Firebase and Play Services must align to the same version.

This is obviously a problem, since background-geolocation imports ‘11.6.0`
```
compile 'com.google.firebase:firebase-core:10.0.1'
```
10.0.1 is < min required 11.2.0 of this plugin.

**Comment by stanleycyang** [comment]
Gotcha. So if I update the firebase version this plugin should work?

**Comment by christocracy** [comment]
And react-Native-Fcm obviously includes other Firebase does, using the wildcard `+` version, which is bad practice.
https://github.com/evollu/react-native-fcm/blob/master/android/build.gradle#L22

You must exclude those dependencies in the same manner as I’ve done in my demo app, then explicitly import them in your app/build.gradle with the desired version (eg 11.6.0)

Firebase and Play Services deps must align to the same version.

**Comment by stanleycyang** [comment]
Which dependencies should I perform the `exclude` on in my `app.gradle`?

**Comment by christocracy** [comment]
you'll have to analyze the `build.gradle` of all your dependencies and find those using `play-services` or `firebase`

At a glance, these *for sure*
```
    compile project(':react-native-fcm')
    compile 'com.google.firebase:firebase-core:10.0.1'
    compile project(':react-native-device-info')
```

You'll want to look at these:
```
    compile project(':react-native-fabric')
    compile('com.crashlytics.sdk.android:crashlytics:2.7.1@aar') {
```

**Comment by stanleycyang** [comment]
Thanks, will look

**Comment by stanleycyang** [comment]
What should I exclude for `compile 'com.google.firebase:firebase-core:10.0.1'`? 

Seems like this is the last lingering issue, because it prevents me from updating to 11.6.0

**Comment by christocracy** [comment]
You don't *exclude* that, you set the desired version you want:  `11.6.0`

**Comment by stanleycyang** [comment]
It caused a crash when I tried that. I’ll look into it
