### ISSUE TITLE
Crashing on launch with Android Lollipop

### ISSUE THREAD

**Issue by bennywrong** [transistorsoft/react-native-background-geolocation#399]
## Your Environment
* Plugin version: 2.9.4
* Platform: Android
* OS version: 5
* Device manufacturer / model: Samsung, LGE, Motorola, OPPO, TrendMicro
* React Native version (`react-native -v`): 0.49.5
* Plugin config

## Expected Behavior
Expected the app to launch

## Actual Behavior
It crashes on launch for all my customers using Android 5

## Steps to Reproduce
1. Open the app
2. It crashes

## Context
Trying to build background location for Android / iOS app

## Debug logs
```
java.lang.NoClassDefFoundError com.transistorsoft.locationmanager.logger.TSLog 
    Unknown:-1 com.transistorsoft.locationmanager.util.Sensors.print
    Unknown:-1 com.transistorsoft.locationmanager.settings.Settings.load
    Unknown:-1 com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>
    Unknown:-1 com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a
    Unknown:-1 com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance
    RNBackgroundGeolocationModule.java:991 com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.getAdapter
    RNBackgroundGeolocationModule.java:378 com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.removeAllListeners
    RNBackgroundGeolocationModule.java:270 com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.onHostDestroy
    ReactContext.java:231 com.facebook.react.bridge.ReactContext.onHostDestroy
    ReactInstanceManager.java:672 com.facebook.react.ReactInstanceManager.moveToBeforeCreateLifecycleState
    ReactInstanceManager.java:592 com.facebook.react.ReactInstanceManager.onHostDestroy
    ReactInstanceManager.java:606 com.facebook.react.ReactInstanceManager.onHostDestroy
    ReactActivityDelegate.java:142 com.facebook.react.ReactActivityDelegate.onDestroy
    ReactActivity.java:72 com.facebook.react.ReactActivity.onDestroy
    Activity.java:6199 android.app.Activity.performDestroy
    Instrumentation.java:1140 android.app.Instrumentation.callActivityOnDestroy
    ActivityThread.java:3752 android.app.ActivityThread.performDestroyActivity
    ActivityThread.java:3783 android.app.ActivityThread.handleDestroyActivity
    ActivityThread.java:151 android.app.ActivityThread.access$1400
    ActivityThread.java:1363 android.app.ActivityThread$H.handleMessage
    Handler.java:102 android.os.Handler.dispatchMessage
    Looper.java:135 android.os.Looper.loop
    ActivityThread.java:5351 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    Method.java:372 java.lang.reflect.Method.invoke
    ZygoteInit.java:908 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:703 com.android.internal.os.ZygoteInit.main
```

```
java.lang.NoClassDefFoundError Failed resolution of: Lch/qos/logback/classic/Logger; 
    Unknown:-1 com.transistorsoft.locationmanager.logger.TSLog.getRootLogger
    Unknown:-1 com.transistorsoft.locationmanager.logger.TSLog.initialize
    Unknown:-1 com.transistorsoft.locationmanager.logger.TSLog.<clinit>
    Unknown:-1 com.transistorsoft.locationmanager.util.Sensors.print
    Unknown:-1 com.transistorsoft.locationmanager.settings.Settings.load
    Unknown:-1 com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>
    Unknown:-1 com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a
    Unknown:-1 com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance
    RNBackgroundGeolocationModule.java:991 com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.getAdapter
    RNBackgroundGeolocationModule.java:986 com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.initializeLocationManager
    RNBackgroundGeolocationModule.java:259 com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.onHostResume
    ReactContext.java:187 com.facebook.react.bridge.ReactContext.onHostResume
    ReactInstanceManager.java:647 com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState
    ReactInstanceManager.java:680 com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState
    ReactInstanceManager.java:880 com.facebook.react.ReactInstanceManager.setupReactContext
    ReactInstanceManager.java:107 com.facebook.react.ReactInstanceManager.access$1000
    ReactInstanceManager.java:851 com.facebook.react.ReactInstanceManager$4$2.run
    Handler.java:739 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    MessageQueueThreadHandler.java:31 com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
    Looper.java:135 android.os.Looper.loop
    MessageQueueThreadImpl.java:194 com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run
    Thread.java:818 java.lang.Thread.run


Caused by: java.lang.ClassNotFoundException Didn't find class "ch.qos.logback.classic.Logger" on path: DexPathList[[zip file "/data/app/pm.spin-1/base.apk"],nativeLibraryDirectories=[/data/app/pm.spin-1/lib/arm, /vendor/lib, /system/lib]] 
    BaseDexClassLoader.java:56 dalvik.system.BaseDexClassLoader.findClass
    ClassLoader.java:511 java.lang.ClassLoader.loadClass
    ClassLoader.java:469 java.lang.ClassLoader.loadClass
    Unknown:-1 com.transistorsoft.locationmanager.logger.TSLog.getRootLogger
    Unknown:-1 com.transistorsoft.locationmanager.logger.TSLog.initialize
    Unknown:-1 com.transistorsoft.locationmanager.logger.TSLog.<clinit>
    Unknown:-1 com.transistorsoft.locationmanager.util.Sensors.print
    Unknown:-1 com.transistorsoft.locationmanager.settings.Settings.load
    Unknown:-1 com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>
    Unknown:-1 com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a
    Unknown:-1 com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance
    RNBackgroundGeolocationModule.java:991 com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.getAdapter
    RNBackgroundGeolocationModule.java:986 com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.initializeLocationManager
    RNBackgroundGeolocationModule.java:259 com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.onHostResume
    ReactContext.java:187 com.facebook.react.bridge.ReactContext.onHostResume
    ReactInstanceManager.java:647 com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState
    ReactInstanceManager.java:680 com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState
    ReactInstanceManager.java:880 com.facebook.react.ReactInstanceManager.setupReactContext
    ReactInstanceManager.java:107 com.facebook.react.ReactInstanceManager.access$1000
    ReactInstanceManager.java:851 com.facebook.react.ReactInstanceManager$4$2.run
    Handler.java:739 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    MessageQueueThreadHandler.java:31 com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage
    Looper.java:135 android.os.Looper.loop
    MessageQueueThreadImpl.java:194 com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run
    Thread.java:818 java.lang.Thread.run
```

**Comment by christocracy** [comment]
Your app seems to have problems finding the [`logback`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/android/build.gradle#L32) dependency declared by the plugin's build.gradle.

**Comment by christocracy** [comment]
If you're using Proguard, did you add the [proguard config](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-ANDROID-RNPM.md#proguard-config)?

**Comment by christocracy** [comment]
No idea.  never seen it before.  I always test with release builds here.

The plugin can't find the `logback` dependency either because it's not there or its classnames are obfuscated by pro-guard.

**Comment by christocracy** [comment]
You're getting this error on release builds, I assume.  does it work debug build (ie: `react-native run-android`).

**Comment by bennywrong** [comment]
Yeah just release builds

**Comment by bennywrong** [comment]
what about the TSLog error?

**Comment by christocracy** [comment]
TSLog is a *wrapper* for `ch.qos.logback.classic.Logger`

**Comment by christocracy** [comment]
Gotta' be pro-guard issue.
```
# logback
-keep class ch.qos.** { *; }
-keep class org.slf4j.** { *; }
-dontwarn ch.qos.logback.core.net.*
```

**Comment by bennywrong** [comment]
I have the same lines though, also it's not happening to any other Android version other than 5

**Comment by christocracy** [comment]
No idea.

**Comment by christocracy** [comment]
Maybe [multidex](https://developer.android.com/studio/build/multidex.html) issues.

Do you have *a lot* of dependencies?

**Comment by bennywrong** [comment]
Okay figured it out. I recently change my minimumSdkVersion to 21 from 18 and I didn't remove all the multidex dependencies and code. After removing it, it works now. Sorry about that.

**Comment by crobinson42** [comment]
I'm hitting this issue with `react-native` v0.68.2, yes multidex is on
```
buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
```

```
2022-07-06 15:28:13.853 12901-13061/com.quicktaskdaily E/AndroidRuntime: FATAL EXCEPTION: pool-10-thread-2
    Process: com.quicktaskdaily, PID: 12901
    java.lang.ClassCastException: org.slf4j.helpers.SubstituteLogger cannot be cast to ch.qos.logback.classic.Logger
        at com.transistorsoft.locationmanager.logger.TSLog.getRootLogger(Unknown Source:10)
        at com.transistorsoft.locationmanager.logger.TSLog.access$000(Unknown Source:0)
        at com.transistorsoft.locationmanager.logger.TSLog$a.run(Unknown Source:0)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
2022-07-06 15:28:22.277 12901-13040/com.quicktaskdaily A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 13040 (FlipperConnecti), pid 12901 (.quicktaskdaily)
```

**Comment by christocracy** [comment]
```
$ cd android
$ ./gradlew app:dependencies
```

**Comment by christocracy** [comment]
Also, your error is **not the same** as this *closed issue*.

post a new issue.

**Comment by valkardash** [comment]
also had similar issue - only on switching to headless mode,  
"react-native": "^0.71.7" "react-native-background-geolocation": "^4.11.3"
solved by removing Flipper from the project

04-24 19:19:57.709 12953 13018 E TSLocationManager: ╔═════════════════════════════════════════════
04-24 19:19:57.709 12953 13018 E TSLocationManager: ║ LICENSE VALIDATION FAILURE: com.fleetistics.mf5app
04-24 19:19:57.709 12953 13018 E TSLocationManager: ╠═════════════════════════════════════════════
04-24 19:19:57.709 12953 13018 E TSLocationManager: ╟─ Invalid license key: 
04-24 19:19:57.709 12953 13018 E TSLocationManager: ╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.
04-24 19:19:57.709 12953 13018 E TSLocationManager: ╚═════════════════════════════════════════════
04-24 19:19:57.714 12953 12953 D CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10633; state: ENABLED
04-24 19:19:57.771 12953 13020 E AndroidRuntime: FATAL EXCEPTION: pool-11-thread-2
04-24 19:19:57.771 12953 13020 E AndroidRuntime: Process: com.fleetistics.mf5app, PID: 12953
04-24 19:19:57.771 12953 13020 E AndroidRuntime: java.lang.ClassCastException: org.slf4j.helpers.SubstituteLogger cannot be cast to ch.qos.logback.classic.Logger
04-24 19:19:57.771 12953 13020 E AndroidRuntime:        at com.transistorsoft.locationmanager.logger.TSLog.getRootLogger(Unknown Source:10)
04-24 19:19:57.771 12953 13020 E AndroidRuntime:        at com.transistorsoft.locationmanager.logger.TSLog.access$000(Unknown Source:0)
04-24 19:19:57.771 12953 13020 E AndroidRuntime:        at com.transistorsoft.locationmanager.logger.TSLog$a.run(Unknown Source:0)
04-24 19:19:57.771 12953 13020 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-24 19:19:57.771 12953 13020 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-24 19:19:57.771 12953 13020 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
