### ISSUE TITLE
Android: Location Permission is disabled 

### ISSUE THREAD

**Issue by xinlangzi** [transistorsoft/react-native-background-geolocation#406]
My release app is installed in my android phone, but the location permission is disabled on the setting. I have to manually enable it.

## Your Environment
* Plugin version: 2.10.1
* Platform: Android
* OS version: 8.1.0
* Device manufacturer / model: Pixel 2 XL
* React Native version (`react-native -v`): 0.51.0
* Plugin config

```
import React from 'react';
import Icon from 'react-native-vector-icons/Ionicons';
import { AppState, AsyncStorage, View, Platform, BackHandler } from 'react-native';
import { Navigation } from 'react-native-navigation';
import BackgroundGeolocation from "react-native-background-geolocation";
var Device = require('../libs/device');

var chatIcon;
var chatOutlineIcon;
var homeIcon;
var homeOutlineIcon;

export default class Main extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
      server: this.props.server,
      token: this.props.token,
      name: this.props.name,
      role: this.props.role,
      userId: this.props.userId,
      dispatchers: this.props.dispatchers
    }
  }

  componentWillMount() {
    console.log("Main componentWillMount");
    BackHandler.addEventListener('hardwareBackPress', this.onBackButtonPressed);
    this._populateIcons().then(()=>{
      this._buildTabs();
    }).catch((error) => {
      console.error(error);
    });
  }

  componentDidMount(){
    console.log("Main componentDidMount");
    this._startBackgroundLocation();
  }

  // You must remove listeners when your component unmounts
  componentWillUnmount() {
    console.log("Main componentWillUnmount");
    BackHandler.addEventListener('hardwareBackPress', this.onBackButtonPressed);
    // Remove BackgroundGeolocation listeners
    // BackgroundGeolocation.removeListeners();
  }

  onBackButtonPressed() {
    return true;
}

  _populateIcons = function () {
    return new Promise(function (resolve, reject) {
      Promise.all(
        [
          Icon.getImageSource('ios-chatbubbles', 30),
          Icon.getImageSource('ios-chatbubbles-outline', 30),
          Icon.getImageSource('ios-home', 30),
          Icon.getImageSource('ios-home-outline', 30),
        ]
      ).then((values) => {
        chatIcon = values[0];
        chatOutlineIcon = values[1];
        homeIcon = values[2];
        homeOutlineIcon = values[3];
        resolve(true);
      }).catch((error) => {
        console.log(error);
        reject(error);
      }).done();
    });
  };

  _buildTabs(){
    Navigation.startTabBasedApp({
      tabs: [
        {
          label: 'Home',
          screen: 'HomeTab', // this is a registered name for a screen
          icon: homeIcon,
          selectedIcon: homeOutlineIcon,
          title: 'Home',
          navigatorStyle: {
            navBarHidden: true
          }
        },
        {
          label: 'Chat',
          screen: 'ChatTab',
          icon: chatIcon,
          selectedIcon: chatOutlineIcon,
          title: 'Chat'
        }
      ],
      passProps: {
        server: this.state.server,
        token: this.state.token,
        name: this.state.name,
        role: this.state.role,
        userId: this.state.userId,
        dispatchers: this.state.dispatchers
      },
      appStyle: {
				orientation: 'portrait'
			}
    });
  }

  _startBackgroundLocation(){
    // This handler fires whenever bgGeo receives a location update.
    BackgroundGeolocation.on('location', this.onLocation, this.onError);
    // This handler fires when movement states changes (stationary->moving; moving->stationary)
    BackgroundGeolocation.on('motionchange', this.onMotionChange);
    // This event fires when a change in motion activity is detected
    BackgroundGeolocation.on('activitychange', this.onActivityChange);
    // This event fires when the user toggles location-services authorization
    BackgroundGeolocation.on('providerchange', this.onProviderChange);

    let data = Device.infosWithData({ token: this.props.token });
    BackgroundGeolocation.configure({
      // Geolocation Config
      desiredAccuracy: 0,
      stationaryRadius: 25,
      distanceFilter: 1000,
      foregroundService: true,
      // Activity Recognition
      stopTimeout: 1,
      // Application config
      debug: false,              // <-- enable this hear sounds for background-geolocation life-cycle.
      logLevel: BackgroundGeolocation.LOG_LEVEL_OFF, //LOG_LEVEL_VERBOSE or LOG_LEVEL_OFF
      stopOnTerminate: false,   // <-- Allow the background-service to continue tracking when user closes the app.
      startOnBoot: true,        // <-- Auto start tracking when device is powered-up.
      url: this.props.server + '/mobiles/locations.json',
      batchSync: true,          // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
      // autoSync: false,        // <-- [Default: true] Set true to sync each location to server as it arrives.
      params: data,
      httpRootProperty: "data",
      locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>,"speed":"<%= speed %>","utcTime":"<%= timestamp %>"}'
    }, (state)=> {
      console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
      if (!state.enabled) {
        BackgroundGeolocation.start(function() {
          console.log("- Start success");
          BackgroundGeolocation.changePace(true);
        });
      }else{
        BackgroundGeolocation.changePace(true);
      }
    });
  }

  onLocation(location) {
    console.log('- [event] location: ', location);
  }
  onError(error) {
    console.warn('- [event] location error ', error);
  }
  onActivityChange(activity) {
    console.log('- [event] activitychange: ', activity);  // eg: 'on_foot', 'still', 'in_vehicle'
  }
  onProviderChange(provider) {
    console.log('- [event] providerchange: ', provider);
  }
  onMotionChange(location) {
    console.log('- [event] motionchange: ', location.isMoving, location);
  }

  render() {
    return <View/>;
  }
}

```

## Expected Behavior
The location permission should be enabled. 

## Actual Behavior
The location permission is disabled, I have to manually enable.

## Context
Hope my user on this android app with enabled location permission default.

**Comment by christocracy** [comment]
Post logcat of your app booting:

`$ adb logcat -s TSLocationManager`

**Comment by haobole** [comment]
I am posting this for @xinlangzi : 

```
02-07 19:52:05.271 32642-32642/? I/TSLocationManager: [c.t.l.util.Sensors print] 
                                                      ╔═════════════════════════════════════════════
                                                      ║ DEVICE SENSORS
                                                      ╠═════════════════════════════════════════════
                                                      ╟─ ✅  ACCELEROMETER: {Sensor name="LSM6DSM Accelerometer", vendor="STMicroelectronics", version=1, type=1, maxRange=156.9064, resolution=0.0023956299, power=0.15, minDelay=2500}
                                                      ╟─ ✅  GYROSCOPE: {Sensor name="LSM6DSM Gyroscope", vendor="STMicroelectronics", version=1, type=4, maxRange=17.453293, resolution=0.0012207031, power=0.45, minDelay=2500}
                                                      ╟─ ✅  MAGNETOMETER: {Sensor name="AK09915 Magnetometer", vendor="AKM", version=1, type=2, maxRange=5160.0005, resolution=0.14953613, power=1.8, minDelay=10000}
                                                      ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant Motion", vendor="Google", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.25, minDelay=-1}
                                                      ╚═════════════════════════════════════════════
02-07 19:52:05.289 32642-32642/? I/TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>] 
                                                      ╔═════════════════════════════════════════════
                                                      ║ BackgroundGeolocation adapter
                                                      ╠═════════════════════════════════════════════
02-07 19:52:05.299 32642-32642/? I/TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>] 
                                                        ✅  Google Play Services: connected (version code:11910000)
02-07 19:52:05.325 32642-32642/? D/TSLocationManager: [c.t.l.data.sqlite.a onCreate] CREATE TABLE IF NOT EXISTS locations (id INTEGER PRIMARY KEY AUTOINCREMENT, uuid TEXT NOT NULL DEFAULT '', timestamp TEXT, json TEXT, locked BOOLEAN);
02-07 19:52:05.332 32642-32642/? D/TSLocationManager: [c.t.l.data.sqlite.a onCreate] CREATE TABLE IF NOT EXISTS geofences (id INTEGER PRIMARY KEY AUTOINCREMENT, identifier TEXT NOT NULL UNIQUE, latitude DOUBLE NOT NULL, sin_latitude DOUBLE NOT NULL, cos_latitude DOUBLE NOT NULL, longitude DOUBLE NOT NULL, sin_longitude DOUBLE NOT NULL, cos_longitude DOUBLE NOT NULL, radius DOUBLE NOT NULL, notifyOnEntry BOOLEAN NOT NULL DEFAULT 0, notifyOnExit BOOLEAN NOT NULL DEFAULT 0, notifyOnDwell BOOLEAN NOT NULL DEFAULT 0, loiteringDelay INTEGER NOT NULL DEFAULT 0, extras TEXT);
02-07 19:52:05.346 32642-32642/? D/TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO dbh] 
                                                        ✅  Opened database
02-07 19:52:05.353 32642-32642/? D/TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO prune] 
                                                        ℹ️  PRUNE -1 days
02-07 19:52:05.365 32642-32642/? D/TSLocationManager: [c.t.l.data.sqlite.GeofenceDAO dbh] 
                                                        ✅  Opened database
02-07 19:52:05.376 32642-32642/? I/TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>] 
                                                        🔵  Connecting to GooglePlayServices...
```

**Comment by christocracy** [comment]
How did you install `2.10.1`?  Install it again.  You're missing stuff.

**Comment by christocracy** [comment]
Install latest version `2.11.0`

**Comment by xinlangzi** [comment]
@christocracy 

Before making change according to your suggestion, my phone with android 5.0.1, does enable location permission in default. I will uninstall and update to 2.11.0. Will give you feedback.

**Comment by christocracy** [comment]
I primarily develop upon a Pixel with 8.1.0.  I've never had issue with permissions.

**Comment by christocracy** [comment]
2.11.0 happens to implement permissions within the library itself, rather than relying upon React Native's `PermissionsAndroid` module.

I didn't do this because of any problem, just to make the library more portable between React Native, Cordova, Native Script and Native usage.

**Comment by haobole** [comment]
This is the output when running with version 2.11.0:

```
02-07 21:02:08.074  8643  8643 I TSLocationManager: [c.t.l.util.Sensors print]
02-07 21:02:08.074  8643  8643 I TSLocationManager: ╔═════════════════════════════════════════════
02-07 21:02:08.074  8643  8643 I TSLocationManager: ║ DEVICE SENSORS
02-07 21:02:08.074  8643  8643 I TSLocationManager: ╠═════════════════════════════════════════════
02-07 21:02:08.074  8643  8643 I TSLocationManager: ╟─ ✅  ACCELEROMETER: {Sensor name="LSM6DSM Accelerometer", vendor="STMicroelectronics", version=1, type=1, maxRange=156.9064, resolution=0.0023956299, power=0.15, minDelay=2500}
02-07 21:02:08.074  8643  8643 I TSLocationManager: ╟─ ✅  GYROSCOPE: {Sensor name="LSM6DSM Gyroscope", vendor="STMicroelectronics", version=1, type=4, maxRange=17.453293, resolution=0.0012207031, power=0.45, minDelay=2500}
02-07 21:02:08.074  8643  8643 I TSLocationManager: ╟─ ✅  MAGNETOMETER: {Sensor name="AK09915 Magnetometer", vendor="AKM", version=1, type=2, maxRange=5160.0005, resolution=0.14953613, power=1.8, minDelay=10000}
02-07 21:02:08.074  8643  8643 I TSLocationManager: ╟─ ✅  SIGNIFICANT_MOTION: {Sensor name="Significant Motion", vendor="Google", version=2, type=17, maxRange=1.0, resolution=1.0, power=0.25, minDelay=-1}
02-07 21:02:08.074  8643  8643 I TSLocationManager: ╚═════════════════════════════════════════════
02-07 21:02:08.090  8643  8643 I TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>]
02-07 21:02:08.090  8643  8643 I TSLocationManager: ╔═════════════════════════════════════════════
02-07 21:02:08.090  8643  8643 I TSLocationManager: ║ TSLocationManager version: 2.11.2
02-07 21:02:08.090  8643  8643 I TSLocationManager: ╠═════════════════════════════════════════════
02-07 21:02:08.102  8643  8643 I TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>]
02-07 21:02:08.102  8643  8643 I TSLocationManager:   ✅  Google Play Services: connected (version code:11910000)
02-07 21:02:08.130  8643  8643 D TSLocationManager: [c.t.l.data.sqlite.a onCreate] CREATE TABLE IF NOT EXISTS locations (id INTEGER PRIMARY KEY AUTOINCREMENT, uuid TEXT NOT NULL DEFAULT '', timestamp TEXT, json TEXT, locked BOOLEAN);
02-07 21:02:08.136  8643  8643 D TSLocationManager: [c.t.l.data.sqlite.a onCreate] CREATE TABLE IF NOT EXISTS geofences (id INTEGER PRIMARY KEY AUTOINCREMENT, identifier TEXT NOT NULL UNIQUE, latitude DOUBLE NOT NULL, sin_latitude DOUBLE NOT NULL, cos_latitude DOUBLE NOT NULL, longitude DOUBLE NOT NULL, sin_longitude DOUBLE NOT NULL, cos_longitude DOUBLE NOT NULL, radius DOUBLE NOT NULL, notifyOnEntry BOOLEAN NOT NULL DEFAULT 0, notifyOnExit BOOLEAN NOT NULL DEFAULT 0, notifyOnDwell BOOLEAN NOT NULL DEFAULT 0, loiteringDelay INTEGER NOT NULL DEFAULT 0, extras TEXT);
02-07 21:02:08.147  8643  8643 D TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO dbh]
02-07 21:02:08.147  8643  8643 D TSLocationManager:   ✅  Opened database
02-07 21:02:08.170  8643  8643 D TSLocationManager: [c.t.l.d.s.SQLiteLocationDAO prune]
02-07 21:02:08.170  8643  8643 D TSLocationManager:   ℹ️  PRUNE -1 days
02-07 21:02:08.192  8643  8643 D TSLocationManager: [c.t.l.data.sqlite.GeofenceDAO dbh]
02-07 21:02:08.192  8643  8643 D TSLocationManager:   ✅  Opened database
02-07 21:02:08.203  8643  8643 I TSLocationManager: [c.t.l.a.BackgroundGeolocation <init>]
02-07 21:02:08.203  8643  8643 I TSLocationManager:   🔵  Connecting to GooglePlayServices...
```

Interestingly, there is an exception that looks suspicious. Do you think it is related?

```
02-07 21:02:17.111 13481-13481/? I/GrantPermissionsActivity: No package: null
                                                             android.content.pm.PackageManager$NameNotFoundException
                                                                 at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:173)
                                                                 at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:144)
                                                                 at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.getCallingPackageInfo(GrantPermissionsActivity.java:412)
                                                                 at com.android.packageinstaller.permission.ui.GrantPermissionsActivity.onCreate(GrantPermissionsActivity.java:114)
                                                                 at android.app.Activity.performCreate(Activity.java:6999)
                                                                 at android.app.Activity.performCreate(Activity.java:6990)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                 at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by christocracy** [comment]
Yes, it's probably related.  You seem to have something messed up in your AndroidManifest.xml.  Post your AndroidManifest with **`license` redacted**.

**Comment by xinlangzi** [comment]
@christocracy 

Here is: 
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.practicalstrategies.tz"
    android:versionCode="1"
    android:versionName="1.0">

    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <permission
        android:name="${applicationId}.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />

    <uses-sdk
        android:minSdkVersion="16"
        android:targetSdkVersion="22" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

      <meta-data android:name="com.google.android.geo.API_KEY" android:value="******"/>
      <!-- react-native-background-geolocation licence -->
      <meta-data android:name="com.transistorsoft.locationmanager.license" android:value="******" />

      <service android:name="com.amazonaws.mobileconnectors.s3.transferutility.TransferService" android:enabled="true" />
        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>
    </application>


</manifest>
```

**Comment by xinlangzi** [comment]
@christocracy 

I'm facing this exception on the development mode.

```
02-07 23:05:15.305 10169-10302/com.practicalstrategies.tz E/AndroidRuntime: FATAL EXCEPTION: GoogleApiHandler
                                                                            Process: com.practicalstrategies.tz, PID: 10169
                                                                            java.lang.NoSuchMethodError: No virtual method setChannelId(Ljava/lang/String;)Landroid/support/v4/app/NotificationCompat$Builder; in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/com.practicalstrategies.tz-WLKgKl1cX2ZDTVjdA0CCZg==/base.apk)
                                                                                at com.google.android.gms.common.GoogleApiAvailability.zza(Unknown Source:225)
                                                                                at com.google.android.gms.common.GoogleApiAvailability.zza(Unknown Source:15)
                                                                                at com.google.android.gms.common.api.internal.zzbm.zzc(Unknown Source:4)
                                                                                at com.google.android.gms.common.api.internal.zzbo.onConnectionFailed(Unknown Source:104)
                                                                                at com.google.android.gms.common.api.internal.zzbo.connect(Unknown Source:83)
                                                                                at com.google.android.gms.common.api.internal.zzbo.zza(Unknown Source:47)
                                                                                at com.google.android.gms.common.api.internal.zzbm.handleMessage(Unknown Source:283)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:164)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by christocracy** [comment]
paste your `app/build.gradle`

**Comment by xinlangzi** [comment]
Here is my `app/build.gradle`

```
apply plugin: "com.android.application"

import com.android.build.OutputFile

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {

    compileSdkVersion 26
    buildToolsVersion '26.0.2'

    defaultConfig {
        applicationId "com.practicalstrategies.tz"
        minSdkVersion 16
        targetSdkVersion 26
        multiDexEnabled true
        versionCode 9
        versionName "1.1.5"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

repositories {
   flatDir {
       dirs "../../node_modules/react-native-background-geolocation/android/libs"
   }
}

dependencies {
    compile project(':react-native-s3')
    compile project(':react-native-sound')
    compile project(':react-native-image-picker')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-audio')
    compile project(':react-native-vector-icons')
    compile project(':react-native-push-notification')
    compile ('com.google.android.gms:play-services-gcm:11.6.0') {
        force = true;
    }
    compile project(':react-native-navigation')
    compile project(':react-native-device-info')
    compile(project(':react-native-background-geolocation')) {
      exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
    compile 'com.google.android.gms:play-services-location:11.6.0'
    compile(project(':react-native-maps')){
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-base:11.6.0'
    compile 'com.google.android.gms:play-services-maps:11.6.0'
    compile(name: 'tslocationmanager', ext: 'aar')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.facebook.react:react-native:+"  // From node_modules

}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
```


New Exceptions and Warning:

```
02-07 23:14:42.175 11478-11478/com.practicalstrategies.tz E/WindowManager: android.view.WindowLeaked: Activity com.reactnativenavigation.controllers.NavigationActivity has leaked window DecorView@442b4bc[] that was originally added here
     at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
     at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
     at android.app.Dialog.show(Dialog.java:330)
     at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.handlePlayServicesConnectError(RNBackgroundGeolocationModule.java:864)
     at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.access$300(RNBackgroundGeolocationModule.java:54)
     at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule$1.onPlayServicesConnectError(RNBackgroundGeolocationModule.java:298)
     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source:18)
     at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.start(Unknown Source:47)
     at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.setEnabled(RNBackgroundGeolocationModule.java:837)
     at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.start(RNBackgroundGeolocationModule.java:401)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
     at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
     at android.os.Handler.handleCallback(Handler.java:790)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
     at android.os.Looper.loop(Looper.java:164)
     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
     at java.lang.Thread.run(Thread.java:764)
02-07 23:14:42.194 11478-11478/com.practicalstrategies.tz W/MessageQueue: Handler (android.view.ViewRootImpl$ViewRootHandler) {ae94f9a} sending message to a Handler on a dead thread
java.lang.IllegalStateException: Handler (android.view.ViewRootImpl$ViewRootHandler) {ae94f9a} sending message to a Handler on a dead thread
    at android.os.MessageQueue.enqueueMessage(MessageQueue.java:545)
    at android.os.Handler.enqueueMessage(Handler.java:662)
    at android.os.Handler.sendMessageAtTime(Handler.java:631)
    at android.view.ViewRootImpl$ViewRootHandler.sendMessageAtTime(ViewRootImpl.java:3728)
    at android.os.Handler.sendMessageDelayed(Handler.java:601)
    at android.os.Handler.sendEmptyMessageDelayed(Handler.java:565)
    at android.os.Handler.sendEmptyMessage(Handler.java:550)
    at android.view.ViewRootImpl.die(ViewRootImpl.java:6316)
    at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:458)
    at android.view.WindowManagerGlobal.closeAllExceptView(WindowManagerGlobal.java:442)
    at android.view.WindowManagerGlobal.closeAll(WindowManagerGlobal.java:414)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4446)
    at android.app.ActivityThread.-wrap5(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6494)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by christocracy** [comment]
You have problems with [`react-native-push-notification`](https://github.com/zo0r/react-native-push-notification/blob/master/android/build.gradle#L42)

From `react-native-push-notification`, these will cause conflicts since you're `compileSdkVersion: 26` (as it should be).

```
compile 'com.android.support:appcompat-v7:23.1.1'  #<-- needs to be 26.1.0
compile 'com.google.android.gms:play-services-gcm:+'  #<-- needs to be same as your play-services-version
```

Are you opening your project in Android Studio?  It will be showing your warnings about these.

**Comment by christocracy** [comment]
and add to your `build.gradle`
```
compile 'com.android.support:appcompat-v7:26.1.0'
```
The latest `react-native init` will add `appcompat-v7` automatically, but the version *must* match your `compileSdk`:

eg:  (where x.x = latest release, eg: `26.1.0`)
- `compileSdk: 23 -> appcompat-v7:23.x.x`
- compileSdk: 26 -> appcompat-v7:26.x.x

**Comment by christocracy** [comment]
@xinlangzi Update?

**Comment by xinlangzi** [comment]
@christocracy 

Thank you for your help. it does work well now. If any question in the future, I will ask you in the repository for user with paid license. We did purchase one. :)
