### ISSUE TITLE
Instant crash after launching Android app

### ISSUE THREAD

**Issue by emilklindt** [transistorsoft/react-native-background-geolocation#449]
## Your Environment

* Plugin version: ^2.11.0
* Platform: Android
* OS version: 8.0
* Device manufacturer / model: Nexus 5X
* React Native version: 0.49.5
* Plugin config

## Expected Behavior

App runs after successful build, without crashing instantly.

## Actual Behavior

App runs after successful build, but crashes instantly.

## Steps to Reproduce

1. Follow installation guide
2. Build app using ```./gradlew``` (build is successful)
3. Launch app

## Context

Simple usage and build startup / execution.

## Debug logs

```
AndroidRuntime: java.lang.IncompatibleClassChangeError: Superclass com.google.android.gms.internal.zzbej of com.google.android.gms.location.ActivityRecognitionResult is declared final (declaration of 'com.google.android.gms.location.ActivityRecognitionResult' appears in /data/app/com.example.app-aarI_LP1P0WUySmsHoFONg==/base.apk)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at java.lang.reflect.Method.getParameterTypes(Method.java:179)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source:151)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source:13)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source:12)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.getAdapter(RNBackgroundGeolocationModule.java:1013)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.initializeLocationManager(RNBackgroundGeolocationModule.java:1008)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.onHostResume(RNBackgroundGeolocationModule.java:260)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:187)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.moveToResumedLifecycleState(ReactInstanceManager.java:647)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.moveReactContextToCurrentLifecycleState(ReactInstanceManager.java:680)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:880)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:107)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$4$2.run(ReactInstanceManager.java:851)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
03-27 15:38:34.736 11061 11091 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

Please ask, if any further information is needed.

**Comment by christocracy** [comment]
Try looking at #375

**Comment by emilklindt** [comment]
@christocracy this seems to be, as suspected, a duplicate of #375. If you want you can close this issue, and I will leave any further comments on the referenced issue.
