### ISSUE TITLE
Foreground Service crashes on Android when location permissions are revoked (compileSdkVersion 26)

### ISSUE THREAD

**Issue by tss101** [transistorsoft/react-native-background-geolocation#450]
## Your Environment
* Plugin version: 2.10.1
* Platform: Android
* OS version: 6.0.1
* Device manufacturer / model: Samsung Galaxy Tab S
* React Native version (`react-native -v`): 0.51.0
* Plugin config - below

## Expected Behavior
The background geolocation plugin closes sliently or continues returning onError code 1

## Actual Behavior
User gets two error messages, one after another, both with "Unfortunately Synced has stopped". 

## Steps to Reproduce
1. Install and run app, allow permissions when app is running. Close app, and then revoke permissions.

## Context
Is there a more graceful way of dealing with the user revoking permissions on Android 6 and greater?

Below is my geolocation component. The component is mounted when the app starts:

```
var Geolocator = createReactClass({

    defaultConfig: {
            // Geolocation Config
            desiredAccuracy: 10,
            distanceFilter: 65, 
            stationaryRadius: 45, 
            activityRecognitionInterval: 15000, 

            locationAuthorizationRequest: 'Always',
            locationAuthorizationAlert: {
                titleWhenNotEnabled: "Location-services not enabled",
                titleWhenOff: "Location-services are off",
                instructions: "Location-services need to be 'Always' to discover nearby marks and spaces.",
                cancelButton: "Cancel",
                settingsButton: "Settings"
            },
            foregroundService: true,
            // Activity Recognition
            stopTimeout: 1,
            stopOnTerminate: false,   
            startOnBoot: true,
            url: baseUrl+'/pos/update',
            batchSync: true,       // <-- [Default: false] Set true to sync locations to server in a single HTTP request.
            autoSync: true,         // <-- [Default: true] Set true to sync each location to server as it arrives.
            autoSyncThreshold: 1,
            maxRecordsToPersist: 2,
    },


    componentWillReceiveProps: function(nextProps) {

        if (!_.isEqual(nextProps.sessionR, this.props.sessionR) || 
            !_.isEqual(nextProps.appR, this.props.appR) || 
            !_.isEqual(nextProps.userR, this.props.userR  ) 
            ) {
            BackgroundGeolocation.setConfig(_.merge({headers: setAjaxAuthHeader({},nextProps.sessionR) },this.defaultConfig)
               , function() {
                   console.log("- BackgroundGeolocation is reconfigured and ready");
                   BackgroundGeolocation.getState(function(state) {
                       if (!state.enabled && nextProps.userR.scanenabled != 'off' ) { 
                        BackgroundGeolocation.start(function() { console.log("- Start success in componentWillReceiveProps");}) 
                       }
                   });
                 }
            );
        }

        if (nextProps.userR.scanenabled == 'off' ){
            BackgroundGeolocation.stop(function() { console.log("- Stop success in componentWillReceiveProps");}) 
        }
        
        console.log('componentWillReceiveProps finished in Geolocator')
    },

    componentWillMount: function() {
        var that = this
        // 1.  Wire up event-listeners
        // This handler fires whenever bgGeo receives a location update.
        BackgroundGeolocation.on('location', this.onLocation);
        // This handler fires whenever bgGeo receives an error
        BackgroundGeolocation.on('error', this.onError);
        // 2.  #configure the plugin (just once for life-time of app)
        BackgroundGeolocation.configure(_.merge({headers: setAjaxAuthHeader({},this.props.sessionR) },this.defaultConfig )
            , function(state) {
                console.log("- BackgroundGeolocation is configured and ready: ", state.enabled);
                    if (!state.enabled && that.props.userR.scanenabled != 'off') {
                        BackgroundGeolocation.start(function() {
                            console.log("- Start success");
                        });
                    }
        });
        console.log('componentWillMount finished in Geolocator')
    },

    // You must remove listeners when your component unmounts
    componentWillUnmount: function() {
        // Remove BackgroundGeolocation listeners
        BackgroundGeolocation.un('location', this.onLocation);
        BackgroundGeolocation.un('error', this.onError);
    },

    render: function() { return null  },

    onLocation: function(location) {
        //this.props.setUdets_({pos: positions[1] })
        console.log('- [js]location: ', JSON.stringify(location));
        this.props.setUdets_({scanenabled: 'on', pos: [location.coords.longitude , location.coords.latitude ] })
    },

    onError: function(error) {
        //Code    Error
        //0    Location unknown
        //1    Location permission denied
        //2    Network error
        //408    Location timeout
        console.log('location is not available')
        var type = error.type;
        var code = error.code;

        if (code == 1){  
            this.props.setUdets_({scanenabled: 'off' })
        }
        else if (code == 2){
            this.props.setUdets_({scanenabled: 'na' })
        }

        //alert(type + " Error: " + code);
    }
});


export const ReduxedGeolocator = connect(
    (state) => {return {userR: state.userR, sessionR: state.sessionR, appR: state.appR  }},
    (dispatch) => {return { 
          setUdets_ : (dets) => { dispatch(setUdets(dets)) },
      } 
    }    
)(Geolocator)

```

## Debug logs
```
03-27 18:48:58.309 16873 16891 E AndroidRuntime: java.lang.SecurityException: Client must have ACCESS_FINE_LOCATION permission to request PRIORI
TY_HIGH_ACCURACY locations.
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1621)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1574)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at com.google.android.gms.internal.zzeu.zzb(Unknown Source)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at com.google.android.gms.internal.zzcfa.zza(Unknown Source)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at com.google.android.gms.internal.zzcfd.zza(Unknown Source)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at com.google.android.gms.internal.zzcfk.zza(Unknown Source)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at com.google.android.gms.internal.zzcej.zza(Unknown Source)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at com.google.android.gms.common.api.internal.zzm.zzb(Unknown Source)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at com.google.android.gms.common.api.internal.zzc.zza(Unknown Source)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at com.google.android.gms.common.api.internal.zzbo.zzb(Unknown Source)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at com.google.android.gms.common.api.internal.zzbo.zzaiw(Unknown Source)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at com.google.android.gms.common.api.internal.zzbo.onConnected(Unknown Source)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at com.google.android.gms.common.internal.zzac.onConnected(Unknown Source)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at com.google.android.gms.common.internal.zzn.zzakr(Unknown Source)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at com.google.android.gms.common.internal.zze.zzw(Unknown Source)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at com.google.android.gms.common.internal.zzi.zzaks(Unknown Source)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
03-27 18:48:58.309 16873 16891 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61)


```

**Comment by christocracy** [comment]
This is likely fixed in latest version.  Install latest.

**Comment by tss101** [comment]
Apologies I should have posted this in the react-native-background-geolocation-android repository. 

Thanks, will do
