### ISSUE TITLE
Android 8 crashes when location is turned off on the phone

### ISSUE THREAD

**Issue by kermopajula** [transistorsoft/react-native-background-geolocation#457]
## Your Environment
* Plugin version: 2.11.0, 2.12.0
* Platform: Android
* OS version: 8+
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.51, 0.54
* Plugin config: Default

## Expected Behavior
Location listener should get an error or providerchange listener should say that location services are turned off

## Actual Behavior
App crashes

## Steps to Reproduce
1. Turn location services off (app has permission to use location)
2. Navigate to a view where BackgroundGeolocation.start() is called
3. App crashes

## Context
I'm sorry if it has nothing to do with this library, but since it only occurs when the location services have a specific state, I'm posting it here just in case.
An issue with the same error message has been posted to the Android issue tracker as well: https://issuetracker.google.com/issues/76112072

## Debug logs
04-03 08:30:19.624 20380-20380/com.begin E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.begin, PID: 20380
    android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1775)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by kermopajula** [comment]
We think it's got something to do with timing and start(). When we removed start() and used just getCurrentPosition(), everything worked perfectly and for we managed to make the app stable using 1000ms timeout before calling start() for now.

This is what's going on before the crash - BackgroundGeolocationService gets destroyed milliseconds before fatal exception
```
04-04 10:16:12.545 7683-12298/com.begin I/ReactNativeJS: Running application "begin.timerInfo" with appParams: {"initialProps":{"screenInstanceID":"screenInstanceID4","navigatorID":"navigatorID1_nav","navigatorEventID":"screenInstanceID4_events"},"rootTag":91}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
04-04 10:16:12.920 7683-12299/com.begin D/TSLocationManager: [c.t.l.a.BackgroundGeolocation ready] LocationPermission :true
04-04 10:16:12.943 7683-12219/com.begin D/TSLocationManager: [c.t.locationmanager.util.b a] 
      ℹ️  LocationAuthorization: Permission granted
04-04 10:16:12.953 7683-12299/com.begin D/TSLocationManager: [c.t.locationmanager.util.b a] 
      ℹ️  LocationAuthorization: Permission granted
04-04 10:16:12.996 7683-12219/com.begin I/TSLocationManager: - Enable: false → true, trackingMode: 1
04-04 10:16:13.034 7683-12299/com.begin D/TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
04-04 10:16:13.127 7683-7683/com.begin I/TSLocationManager: [c.t.l.BackgroundGeolocationService onStartCommand] 
    ╔═════════════════════════════════════════════
    ║ BackgroundGeolocation Service started
    ╠═════════════════════════════════════════════
04-04 10:16:13.153 7683-7683/com.begin I/TSLocationManager: [c.t.l.BackgroundGeolocationService d] 
      ✅  Started in foreground
04-04 10:16:13.172 7683-7683/com.begin W/Notification: Use of stream types is deprecated for operations other than volume control
    See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
04-04 10:16:13.175 7683-7683/com.begin I/TSLocationManager: [c.t.l.ActivityRecognitionService a] 
      🎾  Start activity updates: 10000
04-04 10:16:13.187 7683-7683/com.begin I/TSLocationManager: [c.t.l.BackgroundGeolocationService a] 
      🔵  setPace: null → false
04-04 10:16:13.239 7683-7683/com.begin D/TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
04-04 10:16:13.259 7683-7683/com.begin D/TSLocationManager: [c.t.locationmanager.util.b a] 
      ℹ️  LocationAuthorization: Permission granted
04-04 10:16:13.275 7683-7683/com.begin D/EventBus: No subscribers registered for event class com.transistorsoft.locationmanager.event.StartedEvent
    No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
04-04 10:16:13.281 7683-7683/com.begin D/TSLocationManager: [c.t.l.BackgroundGeolocationService onDestroy] 
    ╔═════════════════════════════════════════════
    ║ BackgroundGeolocationService destroyed
    ╠═════════════════════════════════════════════
04-04 10:16:13.299 7683-7683/com.begin D/TSLocationManager: [c.t.l.BackgroundGeolocationService r] 
      🔴  Unregister PowerSaveChangeReceiver: com.transistorsoft.locationmanager.BackgroundGeolocationService$1@3a1c40b
04-04 10:16:13.311 7683-7683/com.begin D/TSLocationManager: [c.t.l.BackgroundGeolocationService r] 
      🔴  Unregister ConnectivityReceiver: com.transistorsoft.locationmanager.BackgroundGeolocationService$2@11e02e8
04-04 10:16:13.324 7683-7683/com.begin I/TSLocationManager: [c.t.l.ActivityRecognitionService b] 
      🔴  Stop activity updates
04-04 10:16:13.334 7683-7683/com.begin D/TSLocationManager: [c.t.l.g.TSGeofenceManager b] 
      🔴  Stop monitoring geofences
04-04 10:16:13.344 7683-7683/com.begin I/TSLocationManager: [c.t.l.BackgroundGeolocationService k] 
      🔴  Stop heartbeat
04-04 10:16:13.353 7683-7683/com.begin D/AndroidRuntime: Shutting down VM
04-04 10:16:13.354 7683-7683/com.begin E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.begin, PID: 7683
    android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1775)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by christocracy** [comment]
Show me your code.

**Comment by kermopajula** [comment]
I tried removing getCurrentPosition(), but it still behaved the same way. Seems that right now only removing or delaying start() prevents crashing.

The following is being called from componentDidMount() {}
```js
        BackgroundGeolocation.on(
            'location',
            this.onLocation.bind(this),
            this.onError.bind(this)
        );
        BackgroundGeolocation.on(
            'providerchange',
            this.onProviderChange.bind(this)
        );

        BackgroundGeolocation.ready({}, state => {
            if (!state.enabled) {
                setTimeout(() => {
                    BackgroundGeolocation.start();
                }, 1000);
            }
        });

        BackgroundGeolocation.getCurrentPosition();
```

**Comment by christocracy** [comment]
The purpose of `#ready` is to let you know when the plugin is *ready* by executing the callback.

You're executing `#getCurrentPosition` *before* the plugin is ready.

**Comment by kermopajula** [comment]
I understand - it's there for the users navigating back and forth between the views and when returning later, the plugin is already configured and getCurrentPosition() fires at the right time.

Either way, start() is the one causing the crash and removing getCurrentPosition() from the code doesn't fix the situation and logcat output looks the same.

**Comment by christocracy** [comment]
show me a log for your app booting from scratch *without* the timeout.  I want to see more logs.

Do you have *any* other Javascript code interacting with the plugin somewhere else?

**Comment by kermopajula** [comment]
No other code is interacting with the plugin.

```
04-16 07:35:30.600 8582-8582/? I/zygote: Not late-enabling -Xcheck:jni (already on)
04-16 07:35:30.731 8582-8582/? W/zygote: Unexpected CPU variant for X86 using defaults: x86
04-16 07:35:30.857 8582-8582/com.begin I/zygote: The ClassLoaderContext is a special shared library.
04-16 07:35:31.231 8582-8582/com.begin I/Bugsnag: Bugsnag NDK integration not available
04-16 07:35:31.244 8582-8599/com.begin I/Bugsnag: Bugsnag Loop
04-16 07:35:31.249 8582-8582/com.begin V/fb-UnpackingSoSource: locked dso store /data/user/0/com.begin/lib-main
04-16 07:35:31.261 8582-8582/com.begin I/fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.begin/lib-main
04-16 07:35:31.261 8582-8582/com.begin V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.begin/lib-main
04-16 07:35:31.584 8582-8582/com.begin D/ReactNative: ReactInstanceManager.ctor()
04-16 07:35:31.604 8582-8582/com.begin D/NetworkSecurityConfig: No Network Security Config specified, using platform default
04-16 07:35:31.677 8582-8582/com.begin D/ReactNative: ReactInstanceManager.createReactContextInBackground()
    ReactInstanceManager.recreateReactContextInBackgroundInner()
04-16 07:35:31.718 8582-8606/com.begin D/OpenGLRenderer: HWUI GL Pipeline
04-16 07:35:31.792 8582-8609/com.begin W/unknown:InspectorPackagerConnection: Couldn't connect to packager, will silently retry
04-16 07:35:31.861 8582-8606/com.begin I/zygote: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
04-16 07:35:31.861 8582-8606/com.begin I/OpenGLRenderer: Initialized EGL, version 1.4
04-16 07:35:31.861 8582-8606/com.begin D/OpenGLRenderer: Swap behavior 1
04-16 07:35:31.862 8582-8606/com.begin W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
04-16 07:35:31.862 8582-8606/com.begin D/OpenGLRenderer: Swap behavior 0
04-16 07:35:31.867 8582-8606/com.begin D/EGL_emulation: eglCreateContext: 0xa1505420: maj 3 min 0 rcv 3
04-16 07:35:31.878 8582-8606/com.begin D/EGL_emulation: eglMakeCurrent: 0xa1505420: ver 3 0 (tinfo 0xa1503390)
04-16 07:35:31.893 8582-8582/com.begin D/ReactNative: ReactInstanceManager.onReloadWithJSDebugger()
04-16 07:35:31.898 8582-8582/com.begin D/ReactNative: ReactInstanceManager.recreateReactContextInBackground()
04-16 07:35:31.901 8582-8582/com.begin D/ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
04-16 07:35:31.944 8582-8606/com.begin D/EGL_emulation: eglMakeCurrent: 0xa1505420: ver 3 0 (tinfo 0xa1503390)
04-16 07:35:32.094 8582-8612/com.begin I/zygote: Thread[24,tid=8612,Native,Thread*=0xa1255e00,peer=0x13ee4160,"Thread-2"] recursive attempt to load library "/data/app/com.begin-LJlqNoyGkUjAzl1Vm0IyWA==/lib/x86/libfb.so"
04-16 07:35:32.094 8582-8612/com.begin D/ReactNative: ReactInstanceManager.createReactContext()
04-16 07:35:32.247 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager
04-16 07:35:32.248 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
04-16 07:35:32.265 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
04-16 07:35:32.266 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
04-16 07:35:32.280 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
04-16 07:35:32.292 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
04-16 07:35:32.294 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.checkbox.ReactCheckBoxManager
04-16 07:35:32.321 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
04-16 07:35:32.331 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
04-16 07:35:32.351 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
04-16 07:35:32.354 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
04-16 07:35:32.356 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
04-16 07:35:32.379 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
04-16 07:35:32.386 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
04-16 07:35:32.394 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
04-16 07:35:32.405 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
04-16 07:35:32.415 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
04-16 07:35:32.436 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
04-16 07:35:32.450 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
04-16 07:35:32.463 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
04-16 07:35:32.464 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
04-16 07:35:32.478 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
04-16 07:35:32.495 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
04-16 07:35:32.501 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
04-16 07:35:32.504 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
04-16 07:35:32.509 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
04-16 07:35:32.512 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
04-16 07:35:32.517 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
04-16 07:35:32.529 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
04-16 07:35:32.535 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
04-16 07:35:32.538 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
04-16 07:35:32.540 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextShadowNode
04-16 07:35:32.541 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
04-16 07:35:32.548 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
04-16 07:35:32.552 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
04-16 07:35:32.568 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
04-16 07:35:32.572 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
04-16 07:35:32.585 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
04-16 07:35:32.596 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
04-16 07:35:32.598 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
04-16 07:35:32.601 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapCalloutManager
04-16 07:35:32.604 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapMarkerManager
04-16 07:35:32.610 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapPolylineManager
04-16 07:35:32.626 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapPolygonManager
04-16 07:35:32.631 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapCircleManager
04-16 07:35:32.634 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapManager
04-16 07:35:32.642 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapLiteManager
04-16 07:35:32.644 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapUrlTileManager
04-16 07:35:32.651 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.AirMapLocalTileManager
04-16 07:35:32.654 8582-8612/com.begin W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.reactnativenavigation.views.managers.SharedElementTransitionManager
04-16 07:35:32.659 8582-8587/com.begin I/zygote: Do partial code cache collection, code=28KB, data=22KB
    After code cache collection, code=28KB, data=22KB
    Increasing code cache capacity to 128KB
04-16 07:35:32.699 8582-8612/com.begin D/ReactNative: Initializing React Xplat Bridge.
04-16 07:35:32.702 8582-8612/com.begin D/ReactNative: Initializing React Xplat Bridge before initializeBridge
04-16 07:35:32.705 8582-8612/com.begin D/ReactNative: Initializing React Xplat Bridge after initializeBridge
    CatalystInstanceImpl.runJSBundle()
04-16 07:35:32.709 8582-8619/com.begin D/ReactNative: ReactInstanceManager.setupReactContext()
04-16 07:35:32.724 8582-8619/com.begin D/ReactNative: CatalystInstanceImpl.initialize()
04-16 07:35:32.739 8582-8619/com.begin W/unknown:ReactNative: Packager connection already open, nooping.
04-16 07:35:32.933 8582-8618/com.begin E/BluetoothAdapter: Bluetooth binder is null
04-16 07:35:32.934 8582-8618/com.begin W/InstanceID: Instance ID SDK is deprecated, com.begin should update to use Firebase Instance ID
04-16 07:35:32.968 8582-8618/com.begin I/WebViewFactory: Loading com.android.chrome version 65.0.3325.109 (code 332510912)
04-16 07:35:33.024 8582-8618/com.begin I/cr_LibraryLoader: Time to load native libraries: 6 ms (timestamps 7818-7824)
04-16 07:35:33.041 8582-8582/com.begin I/chromium: [INFO:library_loader_hooks.cc(36)] Chromium logging enabled: level = 0, default verbosity = 0
04-16 07:35:33.041 8582-8582/com.begin I/cr_LibraryLoader: Expected native library version number "65.0.3325.109", actual native library version number "65.0.3325.109"
04-16 07:35:33.065 8582-8623/com.begin W/cr_ChildProcLH: Create a new ChildConnectionAllocator with package name = com.android.chrome, sandboxed = true
04-16 07:35:33.084 8582-8582/com.begin I/cr_BrowserStartup: Initializing chromium process, singleProcess=false
04-16 07:35:33.086 8582-8582/com.begin I/cr_base: Android Locale: en_US requires .pak files: [en-GB.pak, en-US.pak]
04-16 07:35:33.131 8582-8582/com.begin D/EGL_emulation: eglCreateContext: 0xa1207980: maj 3 min 0 rcv 3
04-16 07:35:33.143 8582-8582/com.begin D/EGL_emulation: eglMakeCurrent: 0xa1207980: ver 3 0 (tinfo 0x8ce50c20)
04-16 07:35:33.272 8582-8604/com.begin W/cr_CrashFileManager: /data/user/0/com.begin/cache/WebView/Crash Reports does not exist or is not a directory
04-16 07:35:37.224 8582-8606/com.begin D/EGL_emulation: eglMakeCurrent: 0xa1505420: ver 3 0 (tinfo 0xa1503390)
04-16 07:35:38.952 8582-8619/com.begin I/bugsnag-react-native: Initialized Bugsnag React Native 2.8.0/Android 0.0
04-16 07:35:39.454 8582-8582/com.begin D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
04-16 07:35:39.667 8582-8582/com.begin W/unknown:ReactNative: Packager connection already open, nooping.
04-16 07:35:40.330 8582-8587/com.begin I/zygote: Do partial code cache collection, code=60KB, data=48KB
04-16 07:35:40.353 8582-8587/com.begin I/zygote: After code cache collection, code=59KB, data=48KB
    Increasing code cache capacity to 256KB
04-16 07:35:40.539 8582-8619/com.begin I/bugsnag-react-native: Setting user data
04-16 07:35:40.587 8582-8593/com.begin I/zygote: Background concurrent copying GC freed 35101(2MB) AllocSpace objects, 12(892KB) LOS objects, 49% free, 3MB/7MB, paused 3.821ms total 129.077ms
04-16 07:35:40.714 8582-8587/com.begin I/zygote: Do full code cache collection, code=121KB, data=87KB
04-16 07:35:40.715 8582-8587/com.begin I/zygote: After code cache collection, code=77KB, data=41KB
04-16 07:35:40.793 8582-8587/com.begin I/zygote: Do partial code cache collection, code=99KB, data=57KB
04-16 07:35:40.795 8582-8587/com.begin I/zygote: After code cache collection, code=94KB, data=55KB
    Increasing code cache capacity to 512KB
04-16 07:35:40.890 8582-8582/com.begin I/Choreographer: Skipped 72 frames!  The application may be doing too much work on its main thread.
04-16 07:35:41.050 8582-8582/com.begin D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
04-16 07:35:41.101 8582-8606/com.begin D/EGL_emulation: eglMakeCurrent: 0xa1505420: ver 3 0 (tinfo 0xa1503390)
04-16 07:35:41.768 8582-8582/com.begin D/ReactNative: ReactInstanceManager.detachViewFromInstance()
04-16 07:35:42.804 8582-8582/com.begin D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
04-16 07:35:42.837 8582-8587/com.begin I/zygote: JIT allocated 56KB for compiled code of void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int)
04-16 07:35:43.193 8582-8676/com.begin I/TSLocationManager: - Enable: false → true, trackingMode: 1
04-16 07:35:43.284 8582-8587/com.begin I/zygote: Do full code cache collection, code=238KB, data=175KB
04-16 07:35:43.285 8582-8587/com.begin I/zygote: After code cache collection, code=211KB, data=122KB
04-16 07:35:43.384 8582-8582/com.begin D/EventBus: No subscribers registered for event class com.transistorsoft.locationmanager.event.StartedEvent
04-16 07:35:43.385 8582-8582/com.begin D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
04-16 07:35:43.394 8582-8587/com.begin I/zygote: Do partial code cache collection, code=219KB, data=118KB
04-16 07:35:43.403 8582-8587/com.begin I/zygote: After code cache collection, code=219KB, data=118KB
    Increasing code cache capacity to 1024KB
04-16 07:35:43.421 8582-8582/com.begin D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
04-16 07:35:43.422 8582-8582/com.begin E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.begin, PID: 8582
    android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by christocracy** [comment]
Show me your onProviderChange code

**Comment by kermopajula** [comment]
```
onProviderChange(provider) {
        this.provider = provider;

        if (provider.gps && provider.status >= 3) {
            this.handlers.error({});

            return BackgroundGeolocation.getState(state => {
                if (state.enabled === false) {
                    this.watchLocation(this.handlers);
                }
            });
        }

        if (provider.status === 2) {
            return this.doError('denied');
        }

        if (!provider.gps) {
            return this.doError('disabled');
        }
    },
```

**Comment by christocracy** [comment]
Show me your `#watchLocation` method.

**Comment by kermopajula** [comment]
It's this one shown here: https://github.com/transistorsoft/react-native-background-geolocation/issues/457#issuecomment-378649053

**Comment by christocracy** [comment]
Your `#watchLocation` is this??
```javascript
watchLocation() {
     BackgroundGeolocation.on(
            'location',
            this.onLocation.bind(this),
            this.onError.bind(this)
        );
        BackgroundGeolocation.on(
            'providerchange',
            this.onProviderChange.bind(this)
        );

        BackgroundGeolocation.ready({}, state => {
            if (!state.enabled) {
                setTimeout(() => {
                    BackgroundGeolocation.start();
                }, 1000);
            }
        });
}
```

**Comment by christocracy** [comment]
- #ready is designed to be executed **once** for the lifetime of your app.
- Listen to your events just *once*.  
- Your `providerchange` handler is going to cause #ready to fired again and extra event-listeners added.

Do not execute your #watchLocation method in providerchange handler.

**Comment by kermopajula** [comment]
I'll try to redesign the logic, however this can not be the reason for the crash because `providerchange` handler is not firing `watchLocation` in this case since `provider.gps` is `false`.

**Comment by christocracy** [comment]
The problem is something is telling the plugin to `#start` then immediately `#stop`.  Android services don’t like this.

╔═════════════════════════════════════════════
    ║ BackgroundGeolocation Service started
    ╠═════════════════════════════════════════════
04-16 07:39:57.411 9084-9084/com.begin I/TSLocationManager: [c.t.l.BackgroundGeolocationService d] 
      ✅  Started in foreground
04-16 07:39:57.437 9084-9084/com.begin I/TSLocationManager: [c.t.l.ActivityRecognitionService a] 
      🎾  Start activity updates: 10000
04-16 07:39:57.449 9084-9084/com.begin I/TSLocationManager: [c.t.l.BackgroundGeolocationService a] 
      🔵  setPace: null → false
04-16 07:39:57.460 9084-9084/com.begin D/TSLocationManager: [c.t.l.adapter.TSConfig c] ℹ️   Persist config
04-16 07:39:57.478 9084-9084/com.begin D/TSLocationManager: [c.t.locationmanager.util.b a] 
      ℹ️  LocationAuthorization: Permission granted
04-16 07:39:57.498 9084-9084/com.begin D/EventBus: No subscribers registered for event class com.transistorsoft.locationmanager.event.StartedEvent
04-16 07:39:57.499 9084-9084/com.begin D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.NoSubscriberEvent
04-16 07:39:57.511 9084-9084/com.begin D/TSLocationManager: [c.t.l.BackgroundGeolocationService onDestroy] 
    ╔═════════════════════════════════════════════
    ║ BackgroundGeolocationService destroyed
    ╠═══════════════════════════════════════════

**Comment by kermopajula** [comment]
That was the case, thanks
