### ISSUE TITLE
Headless mode error: java.lang.RuntimeException: java.lang.ClassCastException: com.develop.app.MainApplication cannot be cast to com.facebook.react.ReactApplication

### ISSUE THREAD

**Issue by pencilcheck** [transistorsoft/react-native-background-geolocation#464]
## Your Environment
* Plugin version: 2.13.4
* Platform: Android
* OS version: 10.14
* Device manufacturer / model: Genymotion
* React Native version (`react-native -v`): 0.48.4
* Plugin config

## Expected Behavior

It should run the headless task

## Actual Behavior

I'm coming back to the latest version with headless JS, when I tried to test the headless by terminating the app I still got the same error as before:
```java.lang.RuntimeException: java.lang.ClassCastException: com.develop.app.MainApplication cannot be cast to com.facebook.react.ReactApplication```

I made sure I followed the instructions by creating an async function, and register that function using `BackgroundGeolocation.registerHeadlessTask`

My MainApplication.java
```
import android.support.multidex.MultiDexApplication;

import com.facebook.react.ReactPackage;

import java.util.Arrays;
import java.util.List;


// Needed for `react-native link`
import com.github.xinthink.rnmk.ReactMaterialKitPackage;
import com.learnium.RNDeviceInfo.RNDeviceInfo;
import com.geektime.rnonesignalandroid.ReactNativeOneSignalPackage;
import com.transistorsoft.rnbackgroundgeolocation.*;
import com.transistorsoft.rnbackgroundfetch.RNBackgroundFetchPackage;
import com.ocetnik.timer.BackgroundTimerPackage;
import com.idehub.Billing.InAppBillingBridgePackage;

public class MainApplication extends MultiDexApplication {

  // Needed for `react-native link`
  public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
            new RNDeviceInfo(),
            new ReactNativeOneSignalPackage(),
            new RNBackgroundGeolocation(),
            new RNBackgroundFetchPackage(),
            new BackgroundTimerPackage(),
            new InAppBillingBridgePackage(),
            new ReactMaterialKitPackage()
    );
  }
}
```

Logcat:
```
            ╔═════════════════════════════════════════════
    ║ HTTP Service
    ╠═════════════════════════════════════════════
10-10 05:16:28.552 32198-32390/com.develop.app D/TSLocationManager: [c.t.locationmanager.data.a.c first] 
      ✅  Locked 1 records
10-10 05:16:28.556 32198-32390/com.develop.app I/TSLocationManager: [c.t.l.http.HttpService a] 
      🔵  HTTP POST: 3264d2cf-82f8-4685-881e-59f8519f5c2c
10-10 05:16:28.714 32198-32391/com.develop.app I/TSLocationManager: [c.t.l.http.HttpService$a onResponse] 
      🔵  Response: 200
10-10 05:16:28.733 32198-32391/com.develop.app D/TSLocationManager: [c.t.locationmanager.data.a.c destroy] 
      ✅  DESTROY: 3264d2cf-82f8-4685-881e-59f8519f5c2c
10-10 05:16:28.984 32198-32382/com.develop.app D/TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
10-10 05:19:20.148 32198-32198/com.develop.app D/ScopedContext: WARNING: getPackageName called on ScopedContext
10-10 05:19:20.150 32198-32198/com.develop.app D/ScopedContext: WARNING: getPackageName called on ScopedContext
10-10 05:19:20.150 32198-32310/com.develop.app D/ScopedContext: WARNING: getPackageName called on ScopedContext
10-10 05:19:20.180 32198-32300/com.develop.app D/ScopedContext: WARNING: getPackageName called on ScopedContext
10-10 05:19:20.202 32198-32234/com.develop.app E/Surface: getSlotFromBufferLocked: unknown buffer: 0xd94af850
10-10 05:19:20.221 32198-1333/com.develop.app D/TSLocationManager: [c.t.locationmanager.util.b a] 
      ℹ️  LocationAuthorization: Permission granted
10-10 05:19:20.285 32198-32198/com.develop.app D/TSLocationManager: [c.t.l.l.SingleLocationRequest$2 onLocationResult] 
    ╔═════════════════════════════════════════════
    ║ SingleLocationRequest: 2
    ╠═════════════════════════════════════════════
    ╟─ 📍  Location[fused 40.308852,-75.121765 acc=4 et=+4h38m45s158ms alt=0.0 vel=0.0 {Bundle[{requestId=2, verticalAccuracy=7.8}]}], age: 19ms, time: 1539191959000
10-10 05:19:20.286 32198-1334/com.develop.app I/TSLocationManager: [c.t.l.l.TSLocationManager onSingleLocationResult] 
      🔵  Acquired current position
10-10 05:19:20.306 32198-1334/com.develop.app D/TSLocationManager: [c.t.l.l.TSLocationManager a] 3.9
10-10 05:19:20.337 32198-1333/com.develop.app I/TSLocationManager: [c.t.locationmanager.data.a.c persist] 
      ✅  INSERT: 2bba81e6-b290-4dd3-8fdd-7a3817e5c92d
10-10 05:19:20.454 32198-1333/com.develop.app D/TSLocationManager: [c.t.l.http.HttpService flush] 
    ╔═════════════════════════════════════════════
    ║ HTTP Service
    ╠═════════════════════════════════════════════
10-10 05:19:20.508 32198-1336/com.develop.app D/TSLocationManager: [c.t.locationmanager.data.a.c first] 
      ✅  Locked 1 records
10-10 05:19:20.531 32198-1336/com.develop.app I/TSLocationManager: [c.t.l.http.HttpService a] 
      🔵  HTTP POST: 2bba81e6-b290-4dd3-8fdd-7a3817e5c92d
10-10 05:19:20.643 32198-1338/com.develop.app I/TSLocationManager: [c.t.l.http.HttpService$a onResponse] 
      🔵  Response: 200
10-10 05:19:20.664 32198-1338/com.develop.app D/TSLocationManager: [c.t.locationmanager.data.a.c destroy] 
      ✅  DESTROY: 2bba81e6-b290-4dd3-8fdd-7a3817e5c92d
10-10 05:19:23.431 32198-32198/com.develop.app D/ScopedContext: WARNING: getPackageName called on ScopedContext
10-10 05:19:23.432 32198-32198/com.develop.app D/ScopedContext: WARNING: getPackageName called on ScopedContext
10-10 05:19:23.432 32198-32300/com.develop.app D/ScopedContext: WARNING: getPackageName called on ScopedContext
10-10 05:19:23.440 32198-32198/com.develop.app I/TextToSpeech: Sucessfully bound to com.google.android.tts
10-10 05:19:23.441 32198-32198/com.develop.app D/TSLocationManager: [c.t.l.a.BackgroundGeolocation c] 
      🔴  Cleared callbacks
10-10 05:19:23.451 32198-32198/com.develop.app I/TSLocationManager: [c.t.l.a.BackgroundGeolocation onActivityDestroy] 
    ╔═════════════════════════════════════════════
    ║ MainActivity was destroyed
    ╠═════════════════════════════════════════════
    ╟─ stopOnTerminate: false
    ╟─ enabled: true
10-10 05:19:23.457 32198-32198/com.develop.app D/TSLocationManager: [c.t.l.a.BackgroundGeolocation c] 
      🔴  Cleared callbacks
10-10 05:19:23.495 32198-32198/com.develop.app D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
10-10 05:19:23.501 32198-32198/com.develop.app D/TSLocationManager: [c.t.r.HeadlessTask onHeadlessEvent] 💀  event: terminate
10-10 05:19:23.509 32198-32198/com.develop.app E/EventBus: Could not dispatch event: class com.transistorsoft.locationmanager.event.HeadlessEvent to subscribing class class com.transistorsoft.rnbackgroundgeolocation.HeadlessTask
    java.lang.ClassCastException: com.develop.app.MainApplication cannot be cast to com.facebook.react.ReactApplication
        at com.transistorsoft.rnbackgroundgeolocation.HeadlessTask.startTask(HeadlessTask.java:109)
        at com.transistorsoft.rnbackgroundgeolocation.HeadlessTask.onHeadlessEvent(HeadlessTask.java:95)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
        at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:420)
        at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
        at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
        at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
        at com.transistorsoft.locationmanager.util.a.a(Unknown Source)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.onActivityDestroy(Unknown Source)
        at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.onHostDestroy(RNBackgroundGeolocationModule.java:292)
        at com.facebook.react.bridge.ReactContext.onHostDestroy(ReactContext.java:231)
        at com.facebook.react.ReactInstanceManager.moveToBeforeCreateLifecycleState(ReactInstanceManager.java:641)
        at com.facebook.react.ReactInstanceManager.destroy(ReactInstanceManager.java:591)
        at java.lang.reflect.Method.invoke(Native Method)
        at host.exp.exponent.RNObject.callWithReceiver(RNObject.java:160)
        at host.exp.exponent.RNObject.call(RNObject.java:111)
        at host.exp.exponent.experience.ReactNativeActivity.onDestroy(ReactNativeActivity.java:287)
        at android.app.Activity.performDestroy(Activity.java:6407)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
        at android.app.ActivityThread.-wrap5(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-10 05:19:23.509 32198-32198/com.develop.app D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.SubscriberExceptionEvent
10-10 05:19:23.509 32198-32198/com.develop.app D/ReactNative: CatalystInstanceImpl.destroy() start
10-10 05:19:23.511 32198-32291/com.develop.app D/TSLocationManager: [c.t.l.a.BackgroundGeolocation c] 
      🔴  Cleared callbacks
10-10 05:19:23.513 32198-32310/com.develop.app D/ScopedContext: WARNING: getPackageName called on ScopedContext
10-10 05:19:23.542 32198-32198/com.develop.app D/ReactNative: CatalystInstanceImpl.destroy() end
10-10 05:19:27.006 32198-1387/com.develop.app D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
10-10 05:19:27.017 32198-32198/com.develop.app D/TSLocationManager: [c.t.r.HeadlessTask onHeadlessEvent] 💀  event: activitychange
10-10 05:19:27.019 32198-1334/com.develop.app D/TSLocationManager: [c.t.l.BackgroundGeolocationService onActivityRecognitionResult] still (100%)
10-10 05:19:27.026 32198-32198/com.develop.app E/EventBus: Could not dispatch event: class com.transistorsoft.locationmanager.event.HeadlessEvent to subscribing class class com.transistorsoft.rnbackgroundgeolocation.HeadlessTask
    java.lang.ClassCastException: com.develop.app.MainApplication cannot be cast to com.facebook.react.ReactApplication
        at com.transistorsoft.rnbackgroundgeolocation.HeadlessTask.startTask(HeadlessTask.java:109)
        at com.transistorsoft.rnbackgroundgeolocation.HeadlessTask.onHeadlessEvent(HeadlessTask.java:95)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
        at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-10 05:19:27.026 32198-32198/com.develop.app D/EventBus: No subscribers registered for event class org.greenrobot.eventbus.SubscriberExceptionEvent
10-10 05:19:27.032 32198-1334/com.develop.app D/TSLocationManager: [c.t.l.a.BackgroundGeolocation isMainActivityActive] NO
10-10 05:19:30.200 32198-32320/com.develop.app I/FirebaseAuth: [FirebaseAuth:] Loading module via FirebaseOptions.
    [FirebaseAuth:] Preparing to create service connection to gms implementation

```

## Steps to Reproduce

1. Follow the instructions https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode
2. Run on genymotion
3. See crash logs after terminating it in genymotion
4.

## Context

Testing out headless mode

**Comment by pencilcheck** [comment]
Sorry it took longer because testing on android requires LAN and the LAN wasn't working by default. Does it really make any difference to test it on real device versus on emulator like genymotion? Shouldn't it works on genymotion as well?

**Comment by christocracy** [comment]
What's the status of this issue?

**Comment by pencilcheck** [comment]
I decided to remove the use of headless tasks, so I think I'm not relevant to this issue anymore (at least until I have to use it again). I can close this but if anyone else also experience this issue feel free to comment or create a new one. Thanks.

**Comment by pencilcheck** [comment]
I'm coming back to the latest version with headless JS, when I tried to test the headless by terminating the app I still got the same error as before:
```java.lang.RuntimeException: java.lang.ClassCastException: com.develop.app.MainApplication cannot be cast to com.facebook.react.ReactApplication```

When I followed the instructions by creating an async function, and register that function using `BackgroundGeolocation.registerHeadlessTask`

**Comment by pencilcheck** [comment]
I followed the snippet here https://github.com/expo/expo/issues/947#issuecomment-349138157
And changed my MainApplication, and I don't see the error anymore. However I think I get some different errors this time, so I will reference the new error with this error since I think they might be related.
