### ISSUE TITLE
undefined is not an object(evaluating RNBackgroundGeolocation.addEventListener)

### ISSUE THREAD

**Issue by pkumar125** [transistorsoft/react-native-background-geolocation#470]
## Your Environment
* Plugin version: 2.12.0-beta.3
* Platform: Android
* OS version:
* Device manufacturer / model: Samsung / SM-G611F
* React Native version (`react-native -v`):0.55.2
* Plugin config

## Expected Behavior

should display list of my current lat/log 
## Actual Behavior
Getting error screen:
undefined is not an object(evaluating RNBackgroundGeolocation.addEventListener)

## Steps to Reproduce

1. Run react-native init BackgroundLatlog 
2. create a new file Welcome.js with code provided on https://github.com/transistorsoft/react-native-background-geolocation#large_blue_diamond-example
3. import Welcome from './Welcome';  Add   <Welcome /> in App.js
4. Run react-native run-android and set Dev Setting

## Context

Need to track current location

## Debug logs

04-17 15:54:26.908 2491-3922/? D/bauth_FPBAuthService: pcf : 0x1012
    thread id : 1, preenroll_flag : 0, nd cnt : 0, cso : 0
    FPBAuthService, 7685
04-17 15:54:27.212 2468-2468/? E/VCD: int32_t init_modem() : Fail to open /dev/umts_atc0, errno = 2
04-17 15:54:27.655 2968-6064/? D/SSRM:G: SIOP:: AP = 340, PST = 344 (W:30), BAT = 298, USB = 0, CHG = 0
04-17 15:54:27.677 3244-3513/? D/NetworkController.MobileSignalController(1/2): onSignalStrengthsChanged signalStrength=SignalStrength: 16 99 -16 -200 -16 -200 -1 0 2147483647 2147483647 2147483647 2147483647 2147483647 0x4 gsm|lte level=4
    getMobileIconGroup(): 0
04-17 15:54:27.683 3244-3244/? E/SignalClusterView: setSlotFocusVisible : subId 2
    setSlotFocusVisible : subId 2
04-17 15:54:27.908 2491-3922/? D/bauth_FPBAuthService: pcf : 0x1012
    thread id : 1, preenroll_flag : 0, nd cnt : 0, cso : 0
    FPBAuthService, 7685
04-17 15:54:27.997 2968-5513/? D/ConnectivityService: filterNetworkStateForUid() uid: 10021 networkInfo: [type: WIFI[] - WIFI, state: CONNECTED/CONNECTED, reason: (unspecified), extra: "NETGEAR91", failover: false, available: true, roaming: false, metered: false]
04-17 15:54:28.001 4333-29696/? E/ctxmgr: [NetworkUtil]No active synchronizable contexts.
04-17 15:54:28.061 4333-29696/? E/Auth: [GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION. Account: <ELLIDED:-119488157>, App: com.google.android.gms, Service: oauth2:https://www.googleapis.com/auth/contextcontroller
    fkq: Long live credential not available.
        at fkr.b(:com.google.android.gms@12521017@12.5.21 (040300-189987672):20)
        at fkr.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):50)
        at fjb.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):35)
        at gzf.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):8)
        at gzf.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):160)
        at gyf.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):2)
        at gyc.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):17)
        at gyc.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):6)
        at cug.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):25)
        at cug.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):79)
        at ffx.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):6)
        at ffw.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):2)
        at ffw.e(:com.google.android.gms@12521017@12.5.21 (040300-189987672):6)
        at ffw.d(:com.google.android.gms@12521017@12.5.21 (040300-189987672):1)
        at ffu.b(:com.google.android.gms@12521017@12.5.21 (040300-189987672):1)
        at nms.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):1)
        at nlf.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):3)
        at dmd.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):54)
        at dhk.run(:com.google.android.gms@12521017@12.5.21 (040300-189987672):2)
        at dhi.handleMessage(:com.google.android.gms@12521017@12.5.21 (040300-189987672):3)
        at nru.run(:com.google.android.gms@12521017@12.5.21 (040300-189987672):6)
        at nsg.run(:com.google.android.gms@12521017@12.5.21 (040300-189987672):27)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at nya.run(:com.google.android.gms@12521017@12.5.21 (040300-189987672))
        at java.lang.Thread.run(Thread.java:762)
04-17 15:54:28.062 4333-29696/? W/Auth: [GetToken] GetToken failed with status code: BadAuthentication
04-17 15:54:28.092 4333-29696/? W/Auth: [GoogleAuthUtil] GoogleAuthUtil
04-17 15:54:28.093 4333-29696/? W/AuthSessionAuthenticato: Auth related exception is being ignored: BadAuthentication
04-17 15:54:28.117 4333-29696/? E/ctxmgr: [BaseServerTask]Server task (WriteInterestRecordTask) got error statusCode=-1.
    com.android.volley.VolleyError: Unable to obtain auth token - is the device online?
        at dmd.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):62)
        at dhk.run(:com.google.android.gms@12521017@12.5.21 (040300-189987672):2)
        at dhi.handleMessage(:com.google.android.gms@12521017@12.5.21 (040300-189987672):3)
        at nru.run(:com.google.android.gms@12521017@12.5.21 (040300-189987672):6)
        at nsg.run(:com.google.android.gms@12521017@12.5.21 (040300-189987672):27)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at nya.run(:com.google.android.gms@12521017@12.5.21 (040300-189987672))
        at java.lang.Thread.run(Thread.java:762)
04-17 15:54:28.119 4333-29696/? E/ctxmgr: [SyncServerInterestRecordsOperation]Failed WriteInterestRecord: network status=-1
04-17 15:54:28.136 2488-2989/? D/EnterpriseController: netId is 0
04-17 15:54:28.136 2488-2989/? D/DnsProxyListener: DNSDBG::dns addrinfo af 2
04-17 15:54:28.212 2468-2468/? E/VCD: int32_t init_modem() : Fail to open /dev/umts_atc0, errno = 2
04-17 15:54:28.249 2968-5513/? D/ConnectivityService: filterNetworkStateForUid() uid: 10378 networkInfo: [type: WIFI[] - WIFI, state: CONNECTED/CONNECTED, reason: (unspecified), extra: "NETGEAR91", failover: false, available: true, roaming: false, metered: false]
04-17 15:54:28.250 29989-29989/? V/TAG: URL ***********http://rest.wowtruck.in/driverwebservice/bookingdetails
    REQUEST ***********{"driver_id":"692"}
04-17 15:54:28.252 29989-30257/? I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-17 15:54:28.253 29989-30257/? I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
04-17 15:54:28.908 2491-3922/? D/bauth_FPBAuthService: pcf : 0x1012
    thread id : 1, preenroll_flag : 0, nd cnt : 0, cso : 0
    FPBAuthService, 7685
04-17 15:54:29.212 2468-2468/? E/VCD: int32_t init_modem() : Fail to open /dev/umts_atc0, errno = 2
04-17 15:54:29.295 29989-30257/? D/Volley: [36355] DiskBasedCache.put: Could not clean up file /data/user/0/in.wowtruck.driverapp/cache/volley/-1005110473-505857932
04-17 15:54:29.295 29989-29989/? V/TAG: RESPONSE ***********{"status":1,"message":"No Bookings Found \/ The booking has already been accepted by another driver","data":{},"result":{"driver_attendance":{"status":"Present","reason":""},"unread_notification":0,"available_bookings":[]}}
04-17 15:54:29.297 29989-30033/? I/ReactNativeJS: ###Booking Event0
    { event: 0 }
    ###app statebackground
04-17 15:54:29.298 29989-30033/? I/ReactNativeJS: #####attendance event
    { event: 1 }
04-17 15:54:29.299 29989-30033/? I/ReactNativeJS: ###notification event
    { event: 0 }
04-17 15:54:29.587 3984-3984/? D/io_stats: !@ 179,0 r 6683711 288699912 w 5796212 86410692 d 505085 31447884 f 2819240 2818595 iot 8803110 8420011 th 51200 0 0 pt 0 inp 0 0 631059.422
04-17 15:54:29.908 2491-3922/? D/bauth_FPBAuthService: pcf : 0x1012
04-17 15:54:29.909 2491-3922/? D/bauth_FPBAuthService: thread id : 1, preenroll_flag : 0, nd cnt : 0, cso : 0
    FPBAuthService, 7685
04-17 15:54:30.089 2968-5513/? D/ConnectivityService: filterNetworkStateForUid() uid: 10021 networkInfo: [type: WIFI[] - WIFI, state: CONNECTED/CONNECTED, reason: (unspecified), extra: "NETGEAR91", failover: false, available: true, roaming: false, metered: false]
04-17 15:54:30.092 4333-28714/? E/ctxmgr: [NetworkUtil]No active synchronizable contexts.
04-17 15:54:30.113 4333-28714/? E/Auth: [GoogleAccountDataServiceImpl] getToken() -> BAD_AUTHENTICATION. Account: <ELLIDED:-119488157>, App: com.google.android.gms, Service: oauth2:https://www.googleapis.com/auth/contextcontroller
    fkq: Long live credential not available.
        at fkr.b(:com.google.android.gms@12521017@12.5.21 (040300-189987672):20)
        at fkr.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):50)
        at fjb.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):35)
        at gzf.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):8)
        at gzf.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):160)
        at gyf.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):2)
        at gyc.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):17)
        at gyc.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):6)
        at cug.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):25)
        at cug.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):79)
        at ffx.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):6)
        at ffw.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):2)
        at ffw.e(:com.google.android.gms@12521017@12.5.21 (040300-189987672):6)
        at ffw.d(:com.google.android.gms@12521017@12.5.21 (040300-189987672):1)
        at ffu.b(:com.google.android.gms@12521017@12.5.21 (040300-189987672):1)
        at nms.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):1)
        at nlf.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):3)
        at dmd.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):54)
        at dhk.run(:com.google.android.gms@12521017@12.5.21 (040300-189987672):2)
        at dhi.handleMessage(:com.google.android.gms@12521017@12.5.21 (040300-189987672):3)
        at nru.run(:com.google.android.gms@12521017@12.5.21 (040300-189987672):6)
        at nsg.run(:com.google.android.gms@12521017@12.5.21 (040300-189987672):27)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at nya.run(:com.google.android.gms@12521017@12.5.21 (040300-189987672))
        at java.lang.Thread.run(Thread.java:762)
04-17 15:54:30.114 4333-28714/? W/Auth: [GetToken] GetToken failed with status code: BadAuthentication
04-17 15:54:30.145 4333-28714/? W/Auth: [GoogleAuthUtil] GoogleAuthUtil
04-17 15:54:30.145 4333-28714/? W/AuthSessionAuthenticato: Auth related exception is being ignored: BadAuthentication
04-17 15:54:30.149 2488-2989/? D/EnterpriseController: netId is 0
04-17 15:54:30.149 2488-2989/? D/DnsProxyListener: DNSDBG::dns addrinfo af 2
04-17 15:54:30.153 4333-28714/? E/ctxmgr: [BaseServerTask]Server task (WriteInterestRecordTask) got error statusCode=-1.
    com.android.volley.VolleyError: Unable to obtain auth token - is the device online?
        at dmd.a(:com.google.android.gms@12521017@12.5.21 (040300-189987672):62)
        at dhk.run(:com.google.android.gms@12521017@12.5.21 (040300-189987672):2)
        at dhi.handleMessage(:com.google.android.gms@12521017@12.5.21 (040300-189987672):3)
        at nru.run(:com.google.android.gms@12521017@12.5.21 (040300-189987672):6)
        at nsg.run(:com.google.android.gms@12521017@12.5.21 (040300-189987672):27)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at nya.run(:com.google.android.gms@12521017@12.5.21 (040300-189987672))
        at java.lang.Thread.run(Thread.java:762)
04-17 15:54:30.155 4333-28714/? E/ctxmgr: [SyncServerInterestRecordsOperation]Failed WriteInterestRecord: network status=-1
04-17 15:54:30.213 2468-2468/? E/VCD: int32_t init_modem() : Fail to open /dev/umts_atc0, errno = 2
04-17 15:54:30.909 2491-3922/? D/bauth_FPBAuthService: pcf : 0x1012
    thread id : 1, preenroll_flag : 0, nd cnt : 0, cso : 0
    FPBAuthService, 7685
04-17 15:54:31.213 2468-2468/? E/VCD: int32_t init_modem() : Fail to open /dev/umts_atc0, errno = 2
04-17 15:54:31.909 2491-3922/? D/bauth_FPBAuthService: pcf : 0x1012
    thread id : 1, preenroll_flag : 0, nd cnt : 0, cso : 0
    FPBAuthService, 7685
04-17 15:54:32.160 2488-2989/? D/EnterpriseController: netId is 0
04-17 15:54:32.160 2488-2989/? D/DnsProxyListener: DNSDBG::dns addrinfo af 2
04-17 15:54:32.213 2468-2468/? E/VCD: int32_t init_modem() : Fail to open /dev/umts_atc0, errno = 2
04-17 15:54:32.909 2491-3922/? D/bauth_FPBAuthService: pcf : 0x1012
    thread id : 1, preenroll_flag : 0, nd cnt : 0, cso : 0
    FPBAuthService, 7685
04-17 15:54:33.214 2468-2468/? E/VCD: int32_t init_modem() : Fail to open /dev/umts_atc0, errno = 2
04-17 15:54:33.909 2491-3922/? D/bauth_FPBAuthService: pcf : 0x1012
    thread id : 1, preenroll_flag : 0, nd cnt : 0, cso : 0
04-17 15:54:33.910 2491-3922/? D/bauth_FPBAuthService: FPBAuthService, 7685
04-17 15:54:33.932 3244-3513/? D/NetworkController.MobileSignalController(1/2): onSignalStrengthsChanged signalStrength=SignalStrength: 17 99 -17 -200 -17 -200 -1 99 2147483647 2147483647 2147483647 2147483647 2147483647 0x4 gsm|lte level=4
    getMobileIconGroup(): 0
04-17 15:54:34.171 2488-2989/? D/EnterpriseController: netId is 0
04-17 15:54:34.171 2488-2989/? D/DnsProxyListener: DNSDBG::dns addrinfo af 2
04-17 15:54:34.214 2468-2468/? E/VCD: int32_t init_modem() : Fail to open /dev/umts_atc0, errno = 2
04-17 15:54:34.594 3984-3984/? D/io_stats: !@ 179,0 r 6683711 288699912 w 5796239 86410960 d 505090 31447908 f 2819241 2818596 iot 8803130 8420034 th 51200 0 0 pt 0 inp 0 0 631064.430
04-17 15:54:34.910 2491-3922/? D/bauth_FPBAuthService: pcf : 0x1012
    thread id : 1, preenroll_flag : 0, nd cnt : 0, cso : 0
    FPBAuthService, 7685
04-17 15:54:35.214 2468-2468/? E/VCD: int32_t init_modem() : Fail to open /dev/umts_atc0, errno = 2
04-17 15:54:35.910 2491-3922/? D/bauth_FPBAuthService: pcf : 0x1012
    thread id : 1, preenroll_flag : 0, nd cnt : 0, cso : 0
    FPBAuthService, 7685

**Comment by christocracy** [comment]
Update?

**Comment by christocracy** [comment]
Closed for lack of feedback.

**Comment by roysG** [comment]
I have the same problem

**Comment by christocracy** [comment]
If the BackgroundGeolocation API is undefined, the plugin isn’t installed.

Check your setup.
