### ISSUE TITLE
Android app crashes on startup, iOS app works just fine

### ISSUE THREAD

**Issue by DusanDimitric** [transistorsoft/react-native-background-geolocation#472]
## Your Environment

* Plugin version: *2.12.0-beta.3* (tried with *2.11.0* as well)
* Platform: *Android*
* OS version: *8.1 (Oreo)*
* Device manufacturer / model: *Nexus 5 API 27 (Emulated)*
* React Native version (react-native -v): *0.47.2*
* Plugin config: *Tried both `react-native link` and `manual` setups, I added no JavaScript code at all, just did the setup*
# Your Environment

## Expected Behavior

The app shouldn't crash but just by installing `react-native-background-geolocation`
it crashes. Works on iOS though.

## Actual Behavior

The app crashes on startup.

## Steps to Reproduce

Just went through the normal setup procedure for Android as described here:

https://github.com/transistorsoft/react-native-background-geolocation#large_blue_diamond-setup-guides

Tried with both `react-native link Setup` and `Manual install`.

No actual JavaScript code was added at all at this point.

## Context:

I'm just trying to set the plugin up on both Android and iOS

### More details:

`react-native` apps seem to ask for "Display Over Other Apps" permission when
running in "debug" mode.

The stack-trace seems related to this permission grant.

Unsuccessfully tried with other versions of Android as well.

I've also tried with `react-native-background-geolocation` *v2.11.0* but no
luck there either.

### Screenshots

Permission request on app start: (before even seeing the app)
http://prntscr.com/j6unta

App crash:
http://prntscr.com/j6uos2

### 2.12.0-beta.3

```
W ViewRootImpl[MainActivity]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x68, repeatCount=0, eventTime=11434048, downTime=11433846, deviceId=-1, source=0x101 }
I ActivityManager: Killing 7202:com.android.keychain/1000 (adj 906): empty for 2104s
W zygote  : kill(-7202, 9) failed: No such process
D EGL_emulation: eglMakeCurrent: 0xa9d853c0: ver 3 0 (tinfo 0xa9d83320)
E memtrack: Couldn't load memtrack module
W android.os.Debug: failed to get memory consumption info: -1
I zygote  : Background concurrent copying GC freed 1597(251KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 1500KB/2MB, paused 9.035ms total 1.488s
W zygote  : kill(-7202, 9) failed: No such process
W zygote  : Verification of void okhttp3.Response$Builder.checkPriorResponse(okhttp3.Response) took 143.363ms
W zygote  : kill(-7202, 9) failed: No such process
W zygote  : kill(-7202, 9) failed: No such process
I zygote  : Do partial code cache collection, code=28KB, data=23KB
I zygote  : After code cache collection, code=27KB, data=23KB
I zygote  : Increasing code cache capacity to 128KB
W zygote  : kill(-7202, 9) failed: No such process
W .0.2.2:8081/...: type=1400 audit(0.0:73): avc: denied { write } for name="perfd" dev="dm-0" ino=73739 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=dir permissive=0
W .0.2.2:8081/...: type=1400 audit(0.0:74): avc: denied { write } for name="perfd" dev="dm-0" ino=73739 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:shell_data_file:s0 tclass=dir permissive=0
D AndroidRuntime: Shutting down VM
************************ >>> STACK TRACE <<< **********************************
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.mvpmitipiapp, PID: 31650
E AndroidRuntime: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@9065217 -- permission denied for window type 2006
E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:789)
E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
E AndroidRuntime: 	at com.facebook.react.devsupport.DevLoadingViewController.setVisible(DevLoadingViewController.java:150)
E AndroidRuntime: 	at com.facebook.react.devsupport.DevLoadingViewController.access$100(DevLoadingViewController.java:39)
E AndroidRuntime: 	at com.facebook.react.devsupport.DevLoadingViewController$1.run(DevLoadingViewController.java:71)
E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
*******************************************************************************
W zygote  : kill(-7202, 9) failed: No such process
I zygote  : Successfully killed process cgroup uid 1000 pid 7202 in 223ms
W ActivityManager:   Force finishing activity com.mvpmitipiapp/.MainActivity
I ActivityManager: Showing crash dialog for package com.mvpmitipiapp u0
W ActivityManager: Activity pause timeout for ActivityRecord{b97f366 u0 com.mvpmitipiapp/.MainActivity t55 f}
W zygote  : Verification of void okhttp3.internal.ws.WebSocketReader.<init>(boolean, okio.BufferedSource, okhttp3.internal.ws.WebSocketReader$FrameCallback) took 184.866ms
W Looper  : Dispatch took 621ms on android.ui, h=Handler (com.android.server.am.ActivityManagerService$UiHandler) {f920cbe} cb=null msg=1
D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 3059712
```

### 2.11.0 error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.mvpmitipiapp, PID: 27679
                  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbej;
                      at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.<init>(RNBackgroundGeolocationModule.java:83)
                      at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocation.createNativeModules(RNBackgroundGeolocation.java:19)
                      at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
                      at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1071)
                      at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1042)
                      at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:980)
                      at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
                      at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:802)
                      at java.lang.Thread.run(Thread.java:764)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbej" on path: DexPathList[[zip file "/data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/base.apk", zip file "/data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_dependencies_apk.apk", zip file "/data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_0_apk.apk", zip file "/data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_1_apk.apk", zip file "/data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_2_apk.apk", zip file "/data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_3_apk.apk", zip file "/data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_4_apk.apk", zip file "/data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_5_apk.apk", zip file "/data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_6_apk.apk", zip file "/data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_7_apk.apk", zip file "/data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_8_apk.apk", zip file "/data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/lib/x86, /system/fake-libs, /data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/base.apk!/lib/x86, /data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.mvpmitipiapp-TWPQVqIhFFR7UtIXveoYtw==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.<init>(RNBackgroundGeolocationModule.java:83) 
                      at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocation.createNativeModules(RNBackgroundGeolocation.java:19) 
                      at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
                      at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1071) 
                      at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1042) 
                      at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:980) 
                      at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109) 
                      at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:802) 
                      at java.lang.Thread.run(Thread.java:764)
```

**Comment by christocracy** [comment]
Post the following files:
- `android/build.gradle`
- `android/app/build.gradle`

**Comment by christocracy** [comment]
>"Display Over Other Apps" permission when running in "debug" mode.

This is normal when booting first time without a license key.

**Comment by DusanDimitric** [comment]
*android/build.gradle*:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com'
        }
        maven {
            url "$rootDir/../node_modules/react-native-background-geolocation/android/libs"
        }
        maven {
            url "$rootDir/../node_modules/react-native-background-fetch/android/libs"
        }
    }
}

ext {
    compileSdkVersion   = 26
    targetSdkVersion    = 26
    buildToolsVersion   = "26.0.2"
    supportLibVersion   = "26.1.0"
    googlePlayServicesVersion = "11.8.0" 
}
```

*android/app/build.gradle*:
```
apply plugin: "com.android.application"
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"]
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
        nodeExecutableAndArgs : [System.properties['os.name'].contains("Mac") ? "/usr/local/bin/node" : "node"]
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-code-push/android/codepush.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.compileSdkVersion
    buildToolsVersion rootProject.buildToolsVersion
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    defaultConfig {
        applicationId "com.mvpmitipiapp"
        minSdkVersion 19
        targetSdkVersion rootProject.targetSdkVersion
        versionCode project.hasProperty('versionCode') ? project.property('versionCode') as int : 264
        versionName project.hasProperty('versionName') ? project.property('versionName') : "264"
        signingConfig signingConfigs.release
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        packagingOptions {
            exclude "lib/arm64-v8a/libgnustl_shared.so"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a": 1, "x86": 2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
    }
    productFlavors {
    }
}

dependencies {
    compile project(':react-native-background-fetch')
    compile project(':react-native-background-geolocation')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-directed-scrollview')
    compile project(':react-native-auth0')
    compile project(':react-native-network-info')
    compile project(':react-native-splash-screen')
    compile project(':react-native-ble-manager')
    compile project(':react-native-code-push')
    compile project(':react-native-i18n')
    compile project(':react-native-vector-icons')
    compile project(':react-native-device-info')
    compile project(':react-native-config')
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.facebook.react:react-native:+'
    // From node_modules
    compile "com.android.support:appcompat-v7:$rootProject.supportLibVersion"
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 25
                buildToolsVersion '25.0.3'
            }
        }
    }
}
```

**Comment by christocracy** [comment]
You've neglected to use `supportLibVersion`.  Support library root version must match your `compileSdkVersion`.  Support lib version `23.0.1` corresponds to `compileSdkVersion: 23`.

```diff
-  compile 'com.android.support:appcompat-v7:23.0.1'
+  compile "com.android.support:appcompat-v7:$rootProject.supportLibVersion"
```

What is this??  Get rid of it.
```
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 25
                buildToolsVersion '25.0.3'
            }
        }
    }
}
```

**Comment by christocracy** [comment]
Either get rid of it, or use your gradle properties:
```
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion rootProject.compileSdkVersion
                buildToolsVersion rootProject.buildToolsVersion
            }
        }
    }
}
```

**Comment by christocracy** [comment]
Are you terminating your dev server?

**Comment by christocracy** [comment]
I suggest you first try the plugin in isolation in a new react-native app.
```
$ react-native init Foo
```
Follow setup instructions and install only `background-geolocation`.

**Comment by DusanDimitric** [comment]
***Failed attempts:***
1. Tried altering the `subprojects`closure
2. Tried removing the `subprojects` closure
3. Terminating / restarting `packager` (I hope that's what you mean by `dev server`)

---

I'll try running it on an empty project, getting back to you when I do.

Thanks for the help so far 👍

**Comment by DusanDimitric** [comment]
It's the `react-native` version.

It works with a blank project, using the newest `react-native` (`v0.55.3` at the moment).
Yet it crashes on a blank project, with `react-native v0.47.2`, which is the version used in the project.

I will try to upgrade `react-native` on the entire project and then try using `react-native-background-geolocation`.

If that solves the issue I will close it here as well.

Thanks once again for your support Chris!
Dušan Dimitrić

**Comment by DusanDimitric** [comment]
Upgrading the `react-native` versions did indeed make it work.

Thanks!
