### ISSUE TITLE
[ANDROID]: Crash on App Launch (ActivityRecognitionResult)

### ISSUE THREAD

**Issue by luskin** [transistorsoft/react-native-background-geolocation#487]
## Your Environment
* Plugin version: 2.12.0-beta.4
* Platform: iOS or Android
* OS version: Android
* Device manufacturer / model: Samsung Galaxy S7
* React Native version (`react-native -v`): 0.55
* Plugin config

```
BackgroundGeolocation.ready({

      // FOR DEBUG
      reset: false,

      // Geolocation Config
      desiredAccuracy: 0,
      distanceFilter: 500,
  
      // Activity Recognition
      stopTimeout: 1,
  
      // Application config
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      stopOnTerminate: false,
      startOnBoot: true,
      heartbeatInterval: 0,
      foregroundService: true,
      forceReloadOnBoot: true,
  
      // HTTP Settings (Posting locations)
      httpRootProperty: 'location',
      url:
        Platform.OS === 'ios'
          ? ****************
          : ******************,
      locationTemplate: '{"latitude":<%= latitude %>,"longitude":<%= longitude %>}',
      batchSync: false,
      autoSync: true,
  
      // Android Always On Location Notification Title/Text
      notificationTitle: 'Bolt Driver',
      notificationText: 'Keep app open for dispatches'
    },
    state => {
      if (!state.enabled) {
        BackgroundGeolocation.start(function() {
          console.log('[LOCATION]: Began tracking')
        })
      } else {
        console.log('[LOCATION]: Began tracking')
      }
    }
  )
```

## Expected Behavior
The app should open and not crash

## Actual Behavior
The app crashes immediately before even the initial activity is launched

## Steps to Reproduce
1. Follow all instructions to setup RNBackgroundGeolocation
2. google-services:3.2.1
3. compileSdkVersion 27
4. Launch App -> crash

## Context
Just launch the app

## Debug logs

adb logcat:
```
05-14 14:22:34.502 15292-15340/com.mothership.carrier E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Could not invoke RNBackgroundGeolocation.ready
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:762)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
        at android.os.Looper.loop(Looper.java:154) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
        at java.lang.Thread.run(Thread.java:762) 
     Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.location.ActivityRecognitionResult
        at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
        at java.lang.Class.getDexCacheType(Class.java:2551)
        at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:169)
        at java.lang.reflect.Method.getParameterTypes(Method.java:193)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
        at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source)
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source)
        at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.getAdapter(RNBackgroundGeolocationModule.java:991)
        at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.ready(RNBackgroundGeolocationModule.java:306)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
        at android.os.Looper.loop(Looper.java:154) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
        at java.lang.Thread.run(Thread.java:762) 
     Caused by: java.lang.ClassNotFoundException: com.google.android.gms.location.ActivityRecognitionResult
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
        at java.lang.Class.getDexCacheType(Class.java:2551) 
        at java.lang.reflect.AbstractMethod.getParameterTypes(AbstractMethod.java:169) 
        at java.lang.reflect.Method.getParameterTypes(Method.java:193) 
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163) 
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88) 
        at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64) 
        at org.greenrobot.eventbus.EventBus.register(EventBus.java:136) 
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.<init>(Unknown Source) 
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.a(Unknown Source) 
        at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.getInstance(Unknown Source) 
        at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.getAdapter(RNBackgroundGeolocationModule.java:991) 
        at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.ready(RNBackgroundGeolocationModule.java:306) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29) 
        at android.os.Looper.loop(Looper.java:154) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192) 
        at java.lang.Thread.run(Thread.java:762) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbfm;
        at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.<init>(RNBackgroundGeolocationModule.java:85)
        at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocation.createNativeModules(RNBackgroundGeolocation.java:19)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1172)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1142)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1080)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911)
        at java.lang.Thread.run(Thread.java:762) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbfm" on path: DexPathList[[zip file "/data/app/com.mothership.carrier-1/base.apk"],nativeLibraryDirectories=[/data/app/com.mothership.carrier-1/lib/arm, /data/app/com.mothership.carrier-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
    	at j
05-14 14:22:34.503 15292-15292/com.mothership.carrier E/unknown:ReactNative: Unable to launch redbox because react activity is not available, here is the error that redbox would've displayed: Could not invoke RNBackgroundGeolocation.ready
    
    null
    
    com.google.android.gms.location.ActivityRecognitionResult
    
    com.google.android.gms.location.ActivityRecognitionResult
    
    Failed resolution of: Lcom/google/android/gms/internal/zzbfm;
    
    Didn't find class "com.google.android.gms.internal.zzbfm" on path: DexPathList[[zip file "/data/app/com.mothership.carrier-1/base.apk"],nativeLibraryDirectories=[/data/app/com.mothership.carrier-1/lib/arm, /data/app/com.mothership.carrier-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
```

**Comment by christocracy** [comment]
`Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.location.ActivityRecognitionResult`

This is caused by importing a version of `play-services < 11.2.0`.

The min. supported version is `11.2.0`.

Post the following files:
- `android/build.gradle`
- `android/app/build.gradle`

**Comment by luskin** [comment]
android/app/build.gradle:
```
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.compileSdkVersion

    defaultConfig {
        applicationId "com.mothership.carrier"
        minSdkVersion 16
        targetSdkVersion rootProject.targetSdkVersion
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
    buildToolsVersion '27.0.3'
}

dependencies {

    // Firebase
    implementation project(':react-native-firebase')
    implementation "com.google.android.gms:play-services-base:15.0.0"
    implementation "com.google.firebase:firebase-core:15.0.2"
    implementation "com.google.firebase:firebase-auth:15.1.0"
    implementation "com.google.firebase:firebase-messaging:15.0.2"

    // Geolocation
    implementation project(':react-native-background-fetch')
    implementation project(':react-native-background-geolocation')

    // React Native
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:$rootProject.supportLibVersion"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-navigation')
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'
```

android/build.gradle:
```
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath 'com.google.gms:google-services:3.2.1'
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com'
        }
        maven {
            url "$rootDir/../node_modules/react-native-background-geolocation/android/libs"
        }
        maven {
            url "$rootDir/../node_modules/react-native-background-fetch/android/libs"
        }
    }
}

ext {
    compileSdkVersion   = 27
    targetSdkVersion    = 27
    buildToolsVersion   = "27.0.3"
    supportLibVersion   = "27.0.1"
    googlePlayServicesVersion = "11.8.0"
}
```

**Comment by christocracy** [comment]
I don't see a crash here.  The plugin is definitely booting.  The plugin should automatically show a "Location Permission" dialog.

Boot the [SampleApp](https://github.com/transistorsoft/rn-background-geolocation-demo) to test this in isolation of you application.

**Comment by luskin** [comment]
Thanks as always for the detailed help Chris. So I installed the demo app and the permission was requested and tracked just fine, checked it out on your new location server (very cool and helpful, last time we implemented your project I remember hosting that ourselves on heroku this is much better). I'm digging through your code and trying to determine what the difference could possibly be, I have pinpointed it to the .ready() call, without that the app runs just fine (without location of course) but with it the app closes immediately without any error or crash, very weird.

**UPDATE** - It looks like if you call the .ready() to early the first time the application launches that it won't let the application open. For debug purposes I delayed the .ready() call until the SECOND time I launched the app and everything works fine now. I'm not sure why this would be the case but at least now I know that it's fixable.

**Comment by christocracy** [comment]
You're executing `#ready` in `componentDidMount` or `componentWillMount`?

**Comment by luskin** [comment]
No, we built an external service in our redux store to handle locations so on initialization the .ready() would be called in there if we noticed the location permission was granted, however as per my issue [#482](https://github.com/transistorsoft/react-native-background-geolocation/issues/482) there is not a way (as far as we can tell) to do a simple permissions check callback without having to call .ready(), therefore we are calling .ready() on app initialization before any components are mounted and thus seeming to be the issue.
