### ISSUE TITLE
ExceptionInInitializerError: com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule

### ISSUE THREAD

**Issue by davincho** [transistorsoft/react-native-background-geolocation#500]
If I run the app from Android studio (on an emulator or a physical device) everything works. Once I build a signed APK and push it to the Google Play Store on any device (even on an emulator with Google Play Store enabled) I get an ExceptionInInitializerError.

## Your Environment
* Plugin version: 2.12.0-beta.1
* Platform: Android
* OS version: 6, 7
* Device manufacturer / model: Nexus 5X
* React Native version (`react-native -v`): 27
* Plugin config

## Expected Behavior
The app should not crash

## Actual Behavior
The app crashes.

## Steps to Reproduce

1. Push to Play Store
2. Try to open app
3. Crash

## Context
Starting the app.

## Debug logs
`
 --------- beginning of crash
06-09 08:47:58.944 9588-9649/? E/AndroidRuntime: FATAL EXCEPTION: Thread-7
    Process: com.XXX.XXX, PID: 9588
    java.lang.ExceptionInInitializerError
        at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.<init>(RNBackgroundGeolocationModule.java:85)
        at com.transistorsoft.rnbackgroundgeolocation.b.createNativeModules(RNBackgroundGeolocation.java:19)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1172)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1142)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1080)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at com.transistorsoft.locationmanager.a.d.a(Unknown Source)
        at com.transistorsoft.locationmanager.a.a.<clinit>(Unknown Source)
        at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.<init>(RNBackgroundGeolocationModule.java:85) 
        at com.transistorsoft.rnbackgroundgeolocation.b.createNativeModules(RNBackgroundGeolocation.java:19) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1172) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1142) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1080) 
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911) 
        at java.lang.Thread.run(Thread.java:761) 
`
## Gradle Config
```javascript
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
  repositories {
    jcenter()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:2.3.3'
    classpath 'com.google.gms:google-services:3.2.0'
    classpath 'de.undercouch:gradle-download-task:2.0.0'
    classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
  }
}

allprojects {
  repositories {
    maven {
      url "$rootDir/maven"
    }
    maven {
      // We use a modified build of com.android.support.test:runner:1.0.1. Explanation in maven-test/README
      url "$rootDir/maven-test"
    }
    jcenter()
    maven {
      // Local Maven   repo containing AARs with JSC built for Android
      url "$rootDir/../js/node_modules/jsc-android/android"
    }
    flatDir {
      dirs 'libs'
      // dirs project(':expoview').file('libs')
    }
    maven { url "https://jitpack.io" }
    maven {
      url 'https://maven.google.com'
    }
    maven {
                 url "$rootDir/../node_modules/react-native-background-geolocation/android/libs"
             }
    maven {
                 url "$rootDir/../node_modules/react-native-background-fetch/android/libs"
             }

    // Want this last so that we never end up with a stale cache
    mavenLocal()
  }
}

task clean(type: Delete) {
  delete rootProject.buildDir
}

ext {
      compileSdkVersion   = 26
      targetSdkVersion    = 26
      buildToolsVersion   = "26.0.2"
      supportLibVersion   = "26.0.1"
      googlePlayServicesVersion = "11.8.0"
  }

```

**Comment by davincho** [comment]
Upgrading to Plugin version `2.12.2`, I still get the same error, but line numbers are different:

`
06-09 09:44:07.244 8839-8904/? E/AndroidRuntime: FATAL EXCEPTION: Thread-6
    Process: com.XXX.XXX, PID: 8839
    java.lang.ExceptionInInitializerError
        at com.transistorsoft.locationmanager.a.b.a(Unknown Source)
        at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.<init>(RNBackgroundGeolocationModule.java:84)
        at com.transistorsoft.rnbackgroundgeolocation.b.createNativeModules(RNBackgroundGeolocation.java:19)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1172)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1142)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1080)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at com.transistorsoft.locationmanager.a.c.a(Unknown Source)
        at com.transistorsoft.locationmanager.a.b.<clinit>(Unknown Source)
        at com.transistorsoft.locationmanager.a.b.a(Unknown Source) 
        at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.<init>(RNBackgroundGeolocationModule.java:84) 
        at com.transistorsoft.rnbackgroundgeolocation.b.createNativeModules(RNBackgroundGeolocation.java:19) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1172) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1142) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1080) 
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911) 
        at java.lang.Thread.run(Thread.java:761) 
`

**Comment by christocracy** [comment]
I’ve got 2.12.2 published to play store in the SampleApp

I have no issues.

**Comment by christocracy** [comment]
You’ve not shown your plugin config

**Comment by christocracy** [comment]
Did you try installing the apk on your device *before* uploading to play-store?

**Comment by davincho** [comment]
@christocracy adding the Produard Config did the trick - how could I miss this configuration step :O
Thanks a lot!

**Comment by christocracy** [comment]
Always test production apk on your device *before* uploading to play-store.
