### ISSUE TITLE
link library not work and end with error

### ISSUE THREAD

**Issue by ali-pourzahmatkesh** [transistorsoft/react-native-background-geolocation#511]
node version v8.9.3
npm version 5.6.0
		"eslint-plugin-react-native": "^3.2.1",
		"react": "^16.3.1",
		"react-native": "^0.55.4",
		"react-native-background-geolocation": "^2.12.2",
		"react-native-circular-progress": "^0.2.0",
		"react-native-onesignal": "^3.2.4",
		"react-native-paged-contacts": "^1.0.23",
		"react-navigation": "^1.0.3",
		"react-redux": "5.0.7",
		"react-viro": "^2.7.3",
		"redux": "3.7.2",
		"redux-loop": "4.2.4",

## Expected Behavior
I expect link command work successfully!

## Steps to Reproduce
I remove the node_module folder again
install it successfully again
try to link libraries and it falls into the error

## Context
I use a sample Viro react sample project, add this library to it and was working. when I add my project to it and develop some codes and reactive this library on the project, it fail in error when I wanna link.

when I disable the library the project will work :(

## Debug logs
rnpm-install info Platform 'ios' module react-native-background-geolocation is already linked
rnpm-install info Platform 'android' module react-native-background-geolocation is already linked
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.join (path.js:1251:7)
    at Object.<anonymous> (/APZ/work/noavaran/noavaran customers/Tape Project/testRNBG2/node_modules/react-native-background-geolocation/scripts/postlink.js:16:23)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
/APZ/work/noavaran/noavaran customers/Tape Project/testRNBG2/node_modules/react-native/local-cli/core/makeCommand.js:27
        throw new Error(`Error occurred during executing "${command}" command`);
        ^

Error: Error occurred during executing "node_modules/react-native-background-geolocation/scripts/postlink.js" command
    at ChildProcess.prelink (/APZ/work/noavaran/noavaran customers/Tape Project/testRNBG2/node_modules/react-native/local-cli/core/makeCommand.js:27:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by christocracy** [comment]
I do not know what it is with your environment that causes the custom setup script to fail.

Use manual setup instructions.

**Comment by christocracy** [comment]
Actually, I *do* know.  The setup script has a bug where it dislikes the use of the word "test" in your app name.  I see your app name is `testRNBG2`.

The reason for this is a loose regular-expression used to ignore the iOS "Test" target.
