### ISSUE TITLE
App crash in HeadlessTask with react-native-navigation

### ISSUE THREAD

**Issue by kishanj918** [transistorsoft/react-native-background-geolocation#530]
## Your Environment
* Plugin version: 2.12.2
* Platform: Android
* OS version: Android Nougat
* Device manufacturer / model: moto c, moto G 5s Plus
* React Native version (`react-native -v`): 0.55.4
* Plugin config

## Expected Behavior
expecting to work fine

## Actual Behavior
app carsh in background on Headless Task call

## Steps to Reproduce
1. setup headless conficuration for react-native-navigation as shown at https://github.com/wix/react-native-navigation/pull/1444
2.  setup headless task in index.js as you per https://github.com/transistorsoft/react-native-background-geolocation/wiki/Android-Headless-Mode  wiki article

## Context
I'm trying to test headless Task but, it's crashing the app.

## Debug logs
```
07-18 18:24:27.372 930-3252/? E/Sensors: handleToDriver handle(0)
07-18 18:24:27.386 930-3252/? E/Sensors: new setDelay handle(0),ns(10000000)m, error(0), index(2)
07-18 18:24:28.609 1058-1452/? E/NetworkController.MobileSignalController(2): mCurrentState.dataConnected = false; mCurrentState.connected = true; mDataState = -1; isIMS = false; mDataConnectionState = 0
07-18 18:24:30.559 268-422/? E/mnl_linux: mnl_utl_load_property: Config is not set yet, ignore
07-18 18:24:30.598 268-422/? E/gps_controlller: hasAlmanac: open file(/nvcfg/almanac.dat) fail
07-18 18:24:30.681 930-1714/? E/Sensors: handleToDriver handle(0)
07-18 18:24:30.695 930-1714/? E/Sensors: new setDelay handle(0),ns(10000000)m, error(0), index(2)
07-18 18:24:31.028 930-1271/? E/CellLocation: create GsmCellLocation
07-18 18:24:31.180 1058-1452/? E/NetworkController.MobileSignalController(1): mCurrentState.dataConnected = false; mCurrentState.connected = true; mDataState = 2; isIMS = true; mDataConnectionState = 0
07-18 18:24:31.250 1058-1452/? E/NetworkController.MobileSignalController(1): mCurrentState.dataConnected = false; mCurrentState.connected = true; mDataState = 2; isIMS = true; mDataConnectionState = 0
07-18 18:24:31.712 930-998/? E/WifiStateMachine: mIsFullScanOngoing: false, mSendScanResultsBroadcast: false
07-18 18:24:31.732 930-1000/? E/WifiScanningService: WifiSingleScanStateMachine IdleState enter
07-18 18:24:32.666 7551-7551/com.betteryou E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.betteryou, PID: 7551
                                                             java.lang.ExceptionInInitializerError
                                                                 at com.facebook.react.bridge.Arguments.createMap(Arguments.java:163)
                                                                 at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:287)
                                                                 at com.transistorsoft.rnbackgroundgeolocation.HeadlessJobService.onStartJob(HeadlessJobService.java:20)
                                                                 at android.app.job.JobService$JobHandler.handleMessage(JobService.java:143)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                 at android.os.Looper.loop(Looper.java:203)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6253)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
                                                              Caused by: java.lang.RuntimeException: SoLoader.init() not yet called
                                                                 at com.facebook.soloader.SoLoader.assertInitialized(SoLoader.java:335)
                                                                 at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:238)
                                                                 at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:18)
                                                                 at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)
                                                                 at com.facebook.react.bridge.Arguments.createMap(Arguments.java:163) 
                                                                 at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:287) 
                                                                 at com.transistorsoft.rnbackgroundgeolocation.HeadlessJobService.onStartJob(HeadlessJobService.java:20) 
                                                                 at android.app.job.JobService$JobHandler.handleMessage(JobService.java:143) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                 at android.os.Looper.loop(Looper.java:203) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6253) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924) 
07-18 18:24:35.335 930-1265/? E/Sensors: handleToDriver handle(0)
07-18 18:24:35.366 930-1265/? E/Sensors: new setDelay handle(0),ns(10000000)m, error(0), index(2)
07-18 18:24:36.727 930-998/? E/WifiStateMachine: mIsFullScanOngoing: false, mSendScanResultsBroadcast: false
07-18 18:24:36.757 930-1000/? E/WifiScanningService: WifiSingleScanStateMachine IdleState enter
07-18 18:24:36.986 930-1327/? E/Sensors: handleToDriver handle(0)
07-18 18:24:37.000 930-1327/? E/Sensors: new setDelay handle(0),ns(10000000)m, error(0), index(2)
```

**Comment by christocracy** [comment]
Please do not say version “latest”.  That becomes meaningless as time moves on.

**Comment by kishanj918** [comment]
hello @christocracy,
any solution so far??

**Comment by christocracy** [comment]
I’m on vacation until Monday.

**Comment by alizain-wal** [comment]
import { Navigation, NativeEventsReceiver } from 'react-native-navigation';
import {Platform} from 'react-native';

if (Platform.OS === 'ios') {
  initializeApp();
}
else {
  Navigation.isAppLaunched()
    .then((appLaunched) => {
      if (appLaunched) {
        initializeApp();
      }

      new NativeEventsReceiver().appLaunched(initializeApp);
    });
}

**Comment by alizain-wal** [comment]
```
import { Navigation, NativeEventsReceiver } from 'react-native-navigation';
import { Platform } from 'react-native';

if (Platform.OS === 'ios') {
  initializeApp();
}
else {
  Navigation.isAppLaunched()
    .then((appLaunched) => {
      if (appLaunched) {
        initializeApp();
      }

      new NativeEventsReceiver().appLaunched(initializeApp);
    });
}
```

**Comment by christocracy** [comment]
@kishanj918 I await your feedback on @alizain-wal suggestion.

**Comment by kishanj918** [comment]
hello @alizain-wal, i think, [Support headlessJs installation](https://github.com/wix/react-native-navigation/pull/1444) provide same installation process.

**Comment by kishanj918** [comment]
any update so far @christocracy ???
I think the issue is making headless task in react-native-navigation. it will be more good if you make a little demo for your plugin with react-native-navigation & include steps to install your plugin using react-native-navigation.
make sure, react-native-navigation, recently launch v2, but almost all current react-native-navigation user made their app using v1 including me.
I will look forward to your reply. have a good day.

**Comment by kishanj918** [comment]
I never used react-naviagation.
we made a small demo of your plugin which was working fine, but in our demo app. so, we decide to purchase your plugin. 
we have already done a very big application using react-native-navigation, only tracking system (background geolocation) implementation is pending.
but when we tried to implement this demo (your plugin) in our app, we got this error.

**Comment by christocracy** [comment]
Have you searched react-native-navigation for similar issues?

**Comment by christocracy** [comment]
Have you not tried the suggestion above by @alizain-wal?

**Comment by kishanj918** [comment]
yes, you can check out following links....
https://github.com/wix/react-native-navigation/issues/2940
https://github.com/wix/react-native-navigation/issues/3422
issue no. 2940 is closed by bot due to no activity.
issue no. 3422 is not working (issue is still open)

**Comment by kishanj918** [comment]
@alizain-wal provide the same code as provided at..
https://github.com/wix/react-native-navigation/pull/1444

**Comment by kishanj918** [comment]
I'm trying again with another app structure for starting react-native-navigation app. inform you soon.

**Comment by kishanj918** [comment]
hello @christocracy,
It's working fine now, I was setting up headless task inside an activity (screen) after [startTabBasedApp](https://wix.github.io/react-native-navigation/#/top-level-api?id=starttabbasedappparams). which was preventing to register headless module.
thank you. You helped a lot.

however, in this plugin, location is not getting proper inside an office/shop/any building. My requirement is to show push notification & perform some operation if our user visits any registered shop/office in our app. so, it's required to get proper location inside wall(building) envirnment.

any suggestion for BackgroundGeolocation.ready configuration that could be better for my usecase?

**Comment by christocracy** [comment]
Is there something unclear in the Headless setup docs which specifically instructed you to #registerHeadlessTask in `index.js`?

The best accuracy you’ll get inside a building is 40-100 meters.

You’ll *never* be able to determine specific office within a building without physically installing beacons throughout a particular environment.
