### ISSUE TITLE
React Native link fails in postlink.js

### ISSUE THREAD

**Issue by iamchathu** [transistorsoft/react-native-background-geolocation#584]
## Your Environment
* Plugin version:  ^2.13.4
* Platform: iOS or Android
* OS version: MacOS 10.12
* Device manufacturer / model: MacBook Pro
* React Native version (`react-native -v`): react-native-cli: 2.0.1  / react-native: 0.57.3
* Plugin config

## Actual Behavior
```
react-native link react-native-background-geolocation
rnpm-install info Linking react-native-background-geolocation ios dependency
rnpm-install info Platform 'ios' module react-native-background-geolocation has been successfully linked
rnpm-install info Linking react-native-background-geolocation android dependency
rnpm-install info Platform 'android' module react-native-background-geolocation has been successfully linked
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
    at Object.<anonymous> (/Users/Chathu/Workspace/TestPaid/node_modules/react-native-background-geolocation/scripts/postlink.js:16:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
/Users/Chathu/Workspace/TestPaid/node_modules/react-native/local-cli/core/makeCommand.js:32
        throw new Error(`Error occurred during executing "${command}" command`);
        ^

Error: Error occurred during executing "node_modules/react-native-background-geolocation/scripts/postlink.js" command
    at ChildProcess.prelink (/Users/Chathu/Workspace/TestPaid/node_modules/react-native/local-cli/core/makeCommand.js:32:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

## Steps to Reproduce

1. Create new react-native init project
2. `yarn add react-native-background-geolocation`
3. run `react-native link react-native-background-geolocation`

## Context

To install and config module.

**Comment by christocracy** [comment]
Don’t use the word Test in your project name.

There’s a bug in the link script where it gets confused with “Test” target

**Comment by pearlismylove** [comment]
Same here +1.

I never use the word "Test" in my project name and got the error.

`rnpm-install info Linking react-native-background-geolocation ios dependency
rnpm-install info Platform 'ios' module react-native-background-geolocation has been successfully linked
rnpm-install info Linking react-native-background-geolocation android dependency
rnpm-install info Platform 'android' module react-native-background-geolocation has been successfully linked
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/react-native-background-geolocation/scripts/postlink.js ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)`

**Comment by christocracy** [comment]
@pearlismylove What version of the plugin are you using?

**Comment by christocracy** [comment]
@pearlismylove You must be trying to use `2.14.0-beta.1`.  I made a mistake:  I added `/scripts` to the `.npmignore`.  Going to post `2.14.0-beta.2` today.  (your problem actually wasn't related to this issue where the error is "Path must be a string").

**Comment by christocracy** [comment]
@pearlismylove Try installing `2.14.0-beta.2`
