### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by NarendraSingh88** [transistorsoft/react-native-background-geolocation#646]
## Your Environment
* Plugin version:  ^2.14.2
* Platform: Android
* OS version: It is not specific OS
* Device manufacturer / model: not specific device
* React Native version (`react-native -v`): ^0.55.4

## Expected Behavior
It should link successfully

## Actual Behavior
I was unable to link it using react-native link

## Steps to Reproduce

1. react-native link

## Context
I was trying to link this plugin in my app.

## Debug logs
```
path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at Object.<anonymous> (/home/ubuntu/myApp/node_modules/react-native-background-geolocation/scripts/postlink.js:16:23)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
/home/ubuntu/myApp/node_modules/react-native/local-cli/core/makeCommand.js:27
        throw new Error(`Error occurred during executing "${command}" command`);
        ^

Error: Error occurred during executing "node node_modules/react-native-background-geolocation/scripts/postlink.js" command
    at ChildProcess.prelink (/home/ubuntu/myApp/node_modules/react-native/local-cli/core/makeCommand.js:27:15)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:957:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
```

app/build.gradle file ---> https://hastebin.com/miwaxuzedo.rb

```
apply plugin: "com.android.application"
apply plugin: 'io.fabric'
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'
    dexOptions {
        javaMaxHeapSize "4g"
    }
    defaultConfig {
        applicationId "com.example.driversapp"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 303158
        versionName "4.5.2"
        multiDexEnabled true
        dexOptions {
            javaMaxHeapSize "4g"
        }
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        resValue "string", "build_config_package", "com.example.driversapp"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    buildTypes {
        debug {
            manifestPlaceholders = [excludeSystemAlertWindowPermission: "false"]
        }
        release {
            manifestPlaceholders = [excludeSystemAlertWindowPermission: "true"]
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {

    compile project(':react-native-android-location-services-dialog-box')
    compile project(':instabug-reactnative')
    implementation project(':react-native-background-geolocation')
    implementation project(':react-native-gps-state')
    implementation project(':react-native-android-location-services-dialog-box')
    implementation project(':react-native-open-settings')
    implementation project(':react-native-i18n')
    implementation 'com.android.support:multidex:1.0.3'
    implementation project(':instabug-reactnative')
    implementation project(':react-native-config')
    implementation project(':react-native-vector-icons')
    implementation(project(':react-native-firebase')) {
        exclude group: 'com.google.android.gms'
        exclude group: 'com.google.firebase'
        exclude group: 'com.crashlytics.sdk.android:crashlytics'
    }
    implementation(project(':react-native-device-info')) {
        exclude group: 'com.google.android.gms'
    }
    implementation('com.facebook.android:facebook-android-sdk:4.28.0') {
        exclude group: 'com.android.support'
    }
    implementation(project(':react-native-fbsdk')) {
        exclude group: 'com.android.support'
        exclude group: 'com.facebook.android'
    }
    implementation(project(':react-native-fcm')) {
        exclude group: 'com.google.firebase'
    }
    implementation(project(':react-native-maps')) {
        exclude group: 'com.google.android.gms'
    }
    implementation(project(':react-native-wheel-picker-android')) {
        exclude group: 'com.android.support'
    }
    implementation(project(':tipsi-stripe')) {
        exclude group: 'com.android.support'
        exclude group: 'com.google.android.gms'
    }
    implementation(project(':react-native-intercom')) {
        exclude group: 'com.android.support'
    }
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.facebook.react:react-native:+'
    //this decides your firebase SDK version
    implementation 'com.google.firebase:firebase-core:11.6.2'
    implementation 'com.google.firebase:firebase-messaging:11.6.2'
    implementation 'com.google.firebase:firebase-analytics:11.6.2'
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'com.android.support:support-v4:27.0.2'
    implementation 'com.android.support:design:27.0.2'
    implementation 'com.android.support:cardview-v7:27.0.2'
    implementation 'com.android.support:animated-vector-drawable:27.0.2'
    implementation 'com.android.support:support-vector-drawable:27.0.2'
    implementation 'com.android.support:recyclerview-v7:27.0.2'
    implementation 'com.android.support:support-annotations:27.0.2'
    implementation 'com.google.android.gms:play-services-base:11.6.2'
    implementation 'com.google.android.gms:play-services-maps:11.6.2'
    implementation 'com.google.android.gms:play-services-location:11.6.2'
    implementation 'com.google.android.gms:play-services-wallet:11.6.2'
    compile('com.crashlytics.sdk.android:crashlytics:2.9.0@aar') {
        transitive = true
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'
```

root / project build.gradle file  --->  https://hastebin.com/ihejuwelat.cs
```

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        google()
        mavenCentral()
        mavenLocal()
        maven {
            url 'https://maven.google.com'
        }
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.google.gms:google-services:3.1.2'
        classpath 'io.fabric.tools:gradle:1.25.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url "https://jitpack.io"
        }
        google()
        maven {
            url 'https://maven.google.com'
        }
        maven {
            url 'https://maven.google.com/'
        }
      
        configurations.all {
            resolutionStrategy {
                force 'com.facebook.android:facebook-android-sdk:4.28.0'
            }
        }
    }
}
```

**Comment by christocracy** [comment]
You don't care to start by [Reading and performing the Setup steps](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-ANDROID-RNPM.md#open_file_folder-androidbuildgradle).  

You don't think these are necessary?
![](https://dl.dropbox.com/s/gs95rz8vhtp1qq4/Screenshot%202019-01-10%2010.42.15.png?dl=1)

And your `app/build.gradle` is completely messed up.  You don't need all that `exclude group` messing around if you read the Setup Docs.

![](https://dl.dropboxusercontent.com/s/f3ba576jorfmbi1/Screenshot%202019-01-10%2010.44.18.png?dl=1)

Most plugins are now aware of these Gradle Configuration Params and will automatically align themselves to these global versions so you don't have to mess around with all the `exclude group` and  firebase / play-services overrides.  This is all completely unnecessary now and beyond the scope of my plugin support.

```
implementation 'com.google.firebase:firebase-core:11.6.2'
    implementation 'com.google.firebase:firebase-messaging:11.6.2'
    implementation 'com.google.firebase:firebase-analytics:11.6.2'
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'com.android.support:support-v4:27.0.2'
    implementation 'com.android.support:design:27.0.2'
    implementation 'com.android.support:cardview-v7:27.0.2'
    implementation 'com.android.support:animated-vector-drawable:27.0.2'
    implementation 'com.android.support:support-vector-drawable:27.0.2'
    implementation 'com.android.support:recyclerview-v7:27.0.2'
    implementation 'com.android.support:support-annotations:27.0.2'
    implementation 'com.google.android.gms:play-services-base:11.6.2'
    implementation 'com.google.android.gms:play-services-maps:11.6.2'
    implementation 'com.google.android.gms:play-services-location:11.6.2'
    implementation 'com.google.android.gms:play-services-wallet:11.6.2'
```

**Comment by christocracy** [comment]
Do you know what the latest version of `play-services:location` is?  `16.0.0`
![](https://dl.dropbox.com/s/tsy8hx6rc5tf242/Screenshot%202019-01-10%2010.48.37.png?dl=1)

Firebase?  `16.x`
![](https://dl.dropboxusercontent.com/s/ixh8z2knjh7qg84/Screenshot%202019-01-10%2010.49.25.png?dl=1)

Why are you pinning your dependencies to old firebase / play-services versions?

**Comment by christocracy** [comment]
I suggest you go read [react-native-firebase Setup docs too](https://rnfirebase.io/docs/v5.x.x/installation/android)
