### ISSUE TITLE
Error when linking on OSX

### ISSUE THREAD

**Issue by jannikrl** [transistorsoft/react-native-background-geolocation#779]
## Your Environment
* Plugin version: 3.0.9
* Platform: N/A
* OS version: OSX 10.14.5
* Device manufacturer / model: MacBook Pro Mid 2012 2,3 GHz i7
* React Native version (`react-native -v`): 0.60.4
* Plugin config: N/A

## Expected Behavior
I expected the plugin to link automatically

## Actual Behavior
I got an error

## Steps to Reproduce
I ran the following commands:
1. react-native init locationtest
2. cd locationtest
3. npm install react-native-background-geolocation --save
4. react-native link react-native-background-geolocation

## Context
Install plugin

## Debug logs
<details><summary>Logs</summary>

``` 
info Linking "react-native-background-geolocation" iOS dependency
info iOS module "react-native-background-geolocation" has been successfully linked
info Linking "react-native-background-geolocation" Android dependency
info Android module "react-native-background-geolocation" has been successfully linked
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at Object.<anonymous> (/Users/jannik/Documents/Projects/locationtest4/node_modules/react-native-background-geolocation/scripts/postlink.js:20:23)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
error Linking "react-native-background-geolocation" failed. Run CLI with --verbose flag for more details.
Error: Command failed: node node_modules/react-native-background-geolocation/scripts/postlink.js
    at makeError (/Users/jannik/Documents/Projects/locationtest4/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/jannik/Documents/Projects/locationtest4/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

</details>

**Comment by christocracy** [comment]
Don't use the word "test" in your project-name (ie: */Projects/locationtest4*).  The plugin's link-script has a weakness with the word "test".

Call it *locationfoo4* or something.

**Comment by jannikrl** [comment]
It solved the issue. Thanks!
