### ISSUE TITLE
Android version wont build

### ISSUE THREAD

**Issue by JordanRosas** [transistorsoft/react-native-background-geolocation#798]
## Your Environment
* Plugin version: 3.0.9
* Platform: Android Ios is running fine
* OS version: Simulator says 9?
* Device manufacturer / model:Android Emulator its a pixel 2
* React Native version (`react-native -v`):0.60.4

## Expected Behavior

Android version should build and run on Emulator
## Actual Behavior

Won't complete the build errors out saying can't find certain files

## Context

Build and run android version
## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
     Searched in the following locations:
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/react-native-background-fetch/android/libs/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/react-native-background-fetch/android/libs/com/transistorsoft/tslocationmanager/
       - file:/Users/jordanrosas/.m2/repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - file:/Users/jordanrosas/.m2/repository/com/transistorsoft/tslocationmanager/
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/react-native/android/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/react-native/android/com/transistorsoft/tslocationmanager/
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/jsc-android/dist/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/jsc-android/dist/com/transistorsoft/tslocationmanager/
       - https://maven.google.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://maven.google.com/com/transistorsoft/tslocationmanager/
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager/
       - https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
       - https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/
     Required by:
         project :app > project :react-native-background-geolocation
   > Could not find androidx.legacy:legacy-support-v4:1.0.2.
     Searched in the following locations:
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/react-native-background-fetch/android/libs/androidx/legacy/legacy-support-v4/1.0.2/legacy-support-v4-1.0.2.pom
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/react-native-background-fetch/android/libs/androidx/legacy/legacy-support-v4/1.0.2/legacy-support-v4-1.0.2.jar
       - file:/Users/jordanrosas/.m2/repository/androidx/legacy/legacy-support-v4/1.0.2/legacy-support-v4-1.0.2.pom
       - file:/Users/jordanrosas/.m2/repository/androidx/legacy/legacy-support-v4/1.0.2/legacy-support-v4-1.0.2.jar
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/react-native/android/androidx/legacy/legacy-support-v4/1.0.2/legacy-support-v4-1.0.2.pom
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/react-native/android/androidx/legacy/legacy-support-v4/1.0.2/legacy-support-v4-1.0.2.jar
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/jsc-android/dist/androidx/legacy/legacy-support-v4/1.0.2/legacy-support-v4-1.0.2.pom
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/jsc-android/dist/androidx/legacy/legacy-support-v4/1.0.2/legacy-support-v4-1.0.2.jar
       - https://maven.google.com/androidx/legacy/legacy-support-v4/1.0.2/legacy-support-v4-1.0.2.pom
       - https://maven.google.com/androidx/legacy/legacy-support-v4/1.0.2/legacy-support-v4-1.0.2.jar
       - https://dl.google.com/dl/android/maven2/androidx/legacy/legacy-support-v4/1.0.2/legacy-support-v4-1.0.2.pom
       - https://dl.google.com/dl/android/maven2/androidx/legacy/legacy-support-v4/1.0.2/legacy-support-v4-1.0.2.jar
       - https://jcenter.bintray.com/androidx/legacy/legacy-support-v4/1.0.2/legacy-support-v4-1.0.2.pom
       - https://jcenter.bintray.com/androidx/legacy/legacy-support-v4/1.0.2/legacy-support-v4-1.0.2.jar
     Required by:
         project :app > project :react-native-device-info
   > Could not find androidx.media:media:1.0.2.
     Searched in the following locations:
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/react-native-background-fetch/android/libs/androidx/media/media/1.0.2/media-1.0.2.pom
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/react-native-background-fetch/android/libs/androidx/media/media/1.0.2/media-1.0.2.jar
       - file:/Users/jordanrosas/.m2/repository/androidx/media/media/1.0.2/media-1.0.2.pom
       - file:/Users/jordanrosas/.m2/repository/androidx/media/media/1.0.2/media-1.0.2.jar
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/react-native/android/androidx/media/media/1.0.2/media-1.0.2.pom
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/react-native/android/androidx/media/media/1.0.2/media-1.0.2.jar
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/jsc-android/dist/androidx/media/media/1.0.2/media-1.0.2.pom
       - file:/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/jsc-android/dist/androidx/media/media/1.0.2/media-1.0.2.jar
       - https://maven.google.com/androidx/media/media/1.0.2/media-1.0.2.pom
       - https://maven.google.com/androidx/media/media/1.0.2/media-1.0.2.jar
       - https://dl.google.com/dl/android/maven2/androidx/media/media/1.0.2/media-1.0.2.pom
       - https://dl.google.com/dl/android/maven2/androidx/media/media/1.0.2/media-1.0.2.jar
       - https://jcenter.bintray.com/androidx/media/media/1.0.2/media-1.0.2.pom
       - https://jcenter.bintray.com/androidx/media/media/1.0.2/media-1.0.2.jar
     Required by:
         project :app > project :react-native-device-info

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:13)
    at runOnAllDevices (/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:75:39)
    at buildAndRun (/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:169:41)
    at then.result (/Users/jordanrosas/workspace/rudolph-driver-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:135:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

</details>

**Comment by christocracy** [comment]
Post your gradle files:
- `android/build.gradle`
- `android/app/build.gradle`

**Comment by wandersage** [comment]
almost same for me

```
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find any matches for com.transistorsoft:tslocationmanager:+ as no versions of com.transistorsoft:tslocationmanager are available.
  Searched in the following locations:
      file:/Users/antonandreev/Library/Android/sdk/extras/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/Users/antonandreev/Library/Android/sdk/extras/m2repository/com/transistorsoft/tslocationmanager/
      file:/Users/antonandreev/Library/Android/sdk/extras/google/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/Users/antonandreev/Library/Android/sdk/extras/google/m2repository/com/transistorsoft/tslocationmanager/
      file:/Users/antonandreev/Library/Android/sdk/extras/android/m2repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/Users/antonandreev/Library/Android/sdk/extras/android/m2repository/com/transistorsoft/tslocationmanager/
      https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager/maven-metadata.xml
      https://dl.google.com/dl/android/maven2/com/transistorsoft/tslocationmanager/
      file:/Users/antonandreev/.m2/repository/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/Users/antonandreev/.m2/repository/com/transistorsoft/tslocationmanager/
      https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
      https://jcenter.bintray.com/com/transistorsoft/tslocationmanager/
      file:/Users/antonandreev/StudioProjects/benefits-mobile/node_modules/react-native/android/com/transistorsoft/tslocationmanager/maven-metadata.xml
      file:/Users/antonandreev/StudioProjects/benefits-mobile/node_modules/react-native/android/com/transistorsoft/tslocationmanager/
      https://maven.google.com/com/transistorsoft/tslocationmanager/maven-metadata.xml
      https://maven.google.com/com/transistorsoft/tslocationmanager/
  Required by:
      project :app > project :react-native-background-geolocation
```

react-native-cli: 2.0.1
react-native: 0.52.3

[app/build.gradle](https://gist.github.com/wandersage/451bd2c38764caec85f16cd7e3b9a634)
[build.gradle](https://gist.github.com/wandersage/c13632995891818bc7d18d0d2ead2df1)

**Comment by christocracy** [comment]
@wandersage You didn't follow the [installation instructions](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-ANDROID-RNPM.md#react-native--059)

**Comment by JohnTheo13** [comment]
@christocracy I followed your installations precisely react-native link throughs an error, and in general the project is not building, neither with rn <= 0.59

**Comment by christocracy** [comment]
> react-native link throughs an error,

What error?

>and in general the project is not building

Evidence?

**Comment by christocracy** [comment]
This is a complex plugin and AndroidX is a difficult transition involving issues with many other 3rd-party plugins.

It's always a good idea when starting out with this plugin to first play with it in isolation in a freshly generated app.

```
$ react-native init Foo
```

**Comment by JordanRosas** [comment]
react-native link never works for me with any package lol. Always just go with the manual installation obviously not fastest option but better than having to go back into a half linked project.

**Comment by JordanRosas** [comment]
Also @christocracy after configuring everything to the androidX I got the project working just fine. Thanks

**Comment by christocracy** [comment]
@wandersage You did not follow the [installation instructions](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-ANDROID-RNPM.md) and `react-native link react-native-background-geolocation`.  When you do, the plugin's install script will *automatically* append its required [maven url](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-ANDROID.md#open_file_folder-androidbuildgradle) to your `android/build.gradle`.

Without those `maven urls`, you'll get error:
```
Could not find any matches for com.transistorsoft:tslocationmanager:+
```
