### ISSUE TITLE
IllegalArgumentException: Receiver not registered: null

### ISSUE THREAD

**Issue by flohhhh** [transistorsoft/react-native-background-geolocation#832]
## Your Environment
* Plugin version: 3.2.0
* Platform: iOS or Android: Android
* OS version: Many
* React Native version (`react-native -v`): 0.59.8
## Expected Behavior
No crash

## Actual Behavior
App has stopped

**Name:** FATAL EXCEPTION: main
**Reason:** java.lang.RuntimeException: Unable to destroy activity {com.darva.nomadmobile/com.darva.NomadMobile.MainActivity}: java.lang.IllegalArgumentException: Receiver not registered: null
**Stacktrace:**
`FATAL EXCEPTION: main
Process: com.darva.nomadmobile, PID: 13093
java.lang.RuntimeException: Unable to destroy activity {com.darva.nomadmobile/com.darva.NomadMobile.MainActivity}: java.lang.IllegalArgumentException: Receiver not registered: null
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4638)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4665)
	at android.app.ActivityThread.-wrap7(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1700)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6780)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: null
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1054)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1376)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:668)
	at com.transistorsoft.locationmanager.device.a.d(Unknown Source)
	at com.transistorsoft.locationmanager.service.TrackingService.d(Unknown Source)
	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.onActivityDestroy(Unknown Source)
	at com.transistorsoft.rnbackgroundgeolocation.RNBackgroundGeolocationModule.onHostDestroy(RNBackgroundGeolocationModule.java:306)
	at com.facebook.react.bridge.ReactContext.onHostDestroy(ReactContext.java:237)
	at com.facebook.react.ReactInstanceManager.moveToBeforeCreateLifecycleState(ReactInstanceManager.java:687)
	at com.facebook.react.ReactInstanceManager.onHostDestroy(ReactInstanceManager.java:596)
	at com.facebook.react.ReactInstanceManager.onHostDestroy(ReactInstanceManager.java:610)
	at com.facebook.react.ReactActivityDelegate.onDestroy(ReactActivityDelegate.java:117)
	at com.facebook.react.ReactActivity.onDestroy(ReactActivity.java:70)
	at com.darva.NomadMobile.MainActivity.onDestroy(MainActivity.java:35)
	at android.app.Activity.performDestroy(Activity.java:7201)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1161)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4625)
	... 9 more
`

## Steps to Reproduce
1. When my app is on foreground (main screen)
2. Press back button (to go back android home screen)
3. Sometimes I have "App has stopped"

Do you have an idea ?

**Comment by christocracy** [comment]
You're going to have give me some sort of hint.  Like plugin config, device model / os version.

I can't reproduce this with the SampleApp.
