### ISSUE TITLE
Following setup instructions causes the app to crash or shutdown

### ISSUE THREAD

**Issue by eddie-velez** [transistorsoft/react-native-background-geolocation#877]
## Your Environment
* Plugin version: 3.3.0
* Platform: Android
* OS version: 10
* Device manufacturer / model:  Google Pixel 2XL
* React Native version (`react-native -v`): 0.61.1
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
  buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://facebook.github.io/react-native/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }



buildscript {
    ext {
        googlePlayServicesLocationVersion = "17.0.0"
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "1.0.2"
        appCompatVersion = "1.0.2"
    }
.
.
.
}
```

## Expected Behavior
The app should load as it does without installing this plugin

## Actual Behavior
The app begins to install and load, there is a small notice that flashes regarding a missing license and then the app simply closes/crashes

## Steps to Reproduce

1. I simply followed your setup instructions for RN 0.60+
2.
3.
4.

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
adb logcat -s TSLocationManager
--------- beginning of crash
--------- beginning of system
--------- beginning of main
10-20 12:34:05.432 26399 26435 E TSLocationManager:
10-20 12:34:05.432 26399 26435 E TSLocationManager: ╔═════════════════════════════════════════════
10-20 12:34:05.432 26399 26435 E TSLocationManager: ║ LICENSE VALIDATION FAILURE: com.scribb
10-20 12:34:05.432 26399 26435 E TSLocationManager: ╠═════════════════════════════════════════════
10-20 12:34:05.432 26399 26435 E TSLocationManager: ╟─ Failed to find license key in AndroidManifest.  Ensure you've added the key within <application><meta-data android:name="com.transistorsoft.locationmanager.license" android:value="<YOUR LICENSE KEY>" />
10-20 12:34:05.432 26399 26435 E TSLocationManager: ╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.
10-20 12:34:05.432 26399 26435 E TSLocationManager: ╚═════════════════════════════════════════════
10-20 12:41:05.425 28374 28469 E TSLocationManager:
10-20 12:41:05.425 28374 28469 E TSLocationManager: ╔═════════════════════════════════════════════
10-20 12:41:05.425 28374 28469 E TSLocationManager: ║ LICENSE VALIDATION FAILURE: com.scribb
10-20 12:41:05.425 28374 28469 E TSLocationManager: ╠═════════════════════════════════════════════
10-20 12:41:05.425 28374 28469 E TSLocationManager: ╟─ Failed to find license key in AndroidManifest.  Ensure you've added the key within <application><meta-data android:name="com.transistorsoft.locationmanager.license" android:value="<YOUR LICENSE KEY>" />
10-20 12:41:05.425 28374 28469 E TSLocationManager: ╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.
10-20 12:41:05.425 28374 28469 E TSLocationManager: ╚═════════════════════════════════════════════
```

</details>

**Comment by christocracy** [comment]
When there’s a crash, use unfiltered logcat to capture the stacktrace

**Comment by eddie-velez** [comment]
Ok,

This is where it appears to start to load the app to when it kills the PID:
```
10-20 12:51:32.965 31756 31798 W Gralloc3: mapper 3.x is not supported
10-20 12:51:33.007  1286  1325 I ActivityTaskManager: Displayed com.scribb/.MainActivity: +716ms
10-20 12:51:33.041 31756 31821 W com.scribb: Accessing hidden method Landroid/app/AppGlobals;->getInitialApplication()Landroid/app/Application; (greylist, reflection, allowed)
10-20 12:51:33.063 31756 31821 E TSLocationManager:
10-20 12:51:33.063 31756 31821 E TSLocationManager: ╔═════════════════════════════════════════════
10-20 12:51:33.063 31756 31821 E TSLocationManager: ║ LICENSE VALIDATION FAILURE: com.scribb
10-20 12:51:33.063 31756 31821 E TSLocationManager: ╠═════════════════════════════════════════════
10-20 12:51:33.063 31756 31821 E TSLocationManager: ╟─ Failed to find license key in AndroidManifest.  Ensure you've added the key within <application><meta-data android:name="com.transistorsoft.locationmanager.license" android:value="<YOUR LICENSE KEY>" />
10-20 12:51:33.063 31756 31821 E TSLocationManager: ╟─ BackgroundGeolocation is fully functional in DEBUG builds without a license.
10-20 12:51:33.063 31756 31821 E TSLocationManager: ╚═════════════════════════════════════════════
10-20 12:51:33.064   853   853 D android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 0
10-20 12:51:33.084 31213 26089 I PBSessionCacheImpl: Deleted sessionId[199851953838220] from persistence.
10-20 12:51:33.095 31213 31239 W SearchServiceCore: Abort, client detached.
10-20 12:51:33.097 31213 31239 I StreamController: cleanUpControllerScope(nowcards-15-8ed4753-bfb7)
10-20 12:51:33.322 31611 31693 W .apps.wellbein: resources.arsc in APK '/data/app/com.instagram.android-aPDd_3p8Ofe6wNiWODtd-A==/base.apk' is compressed.
10-20 12:51:33.471 31593 31682 W android.pop.pr: resources.arsc in APK '/data/app/com.instagram.android-aPDd_3p8Ofe6wNiWODtd-A==/base.apk' is compressed.
10-20 12:51:33.684 28445 28513 I Icing   : Indexing com.google.android.gms-apps from com.google.android.gms
10-20 12:51:33.749 28445 28513 I Icing   : Indexing com.google.android.gms-internal.3p:MobileApplication from com.google.android.gms
10-20 12:51:33.756 28445 28513 I Icing   : Indexing com.google.android.gms-internal.3p:MusicGroup from com.google.android.gms
10-20 12:51:33.765 28445 28513 I Icing   : Indexing done com.google.android.gms-apps
10-20 12:51:33.770 28445 28513 I Icing   : Indexing done com.google.android.gms-internal.3p:MobileApplication
10-20 12:51:33.780 28445 28513 I Icing   : Indexing done com.google.android.gms-internal.3p:MusicGroup
10-20 12:51:33.782 28445 28513 I Icing   : Indexing com.google.android.gms-internal.3p:DigitalDocument from com.google.android.gms
10-20 12:51:33.787 28445 28513 I Icing   : Indexing com.google.android.gms-internal.3p:Message from com.google.android.gms
10-20 12:51:33.793 28445 28513 I Icing   : Indexing com.google.android.gms-internal.3p:Event from com.google.android.gms
10-20 12:51:33.799 28445 28513 I Icing   : Indexing com.google.android.gms-internal.3p:MusicRecording from com.google.android.gms
10-20 12:51:33.804 28445 28513 I Icing   : Indexing done com.google.android.gms-internal.3p:DigitalDocument
10-20 12:51:33.808 28445 28513 I Icing   : Indexing done com.google.android.gms-internal.3p:Message
10-20 12:51:33.810 28445 28513 I Icing   : Indexing done com.google.android.gms-internal.3p:Event
10-20 12:51:33.814 28445 28513 I Icing   : Indexing done com.google.android.gms-internal.3p:MusicRecording
10-20 12:51:35.250  1286  7291 I LocationAccessPolicy: Allowing com.estrongs.android.pop.pro fine because it doesn't target API 29 yet. Please fix this app. Called from TelephonyRegistry push
10-20 12:51:35.293  1286  7291 W DevicePolicyManager: Package com.estrongs.android.pop.pro (uid=10266, pid=31593) cannot access Device IDs
10-20 12:51:35.295  2230  5377 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.estrongs.android.pop.pro:getDeviceId:isPreinstalled=false:isPrivApp=false
10-20 12:51:35.291 31593 31593 W Handler01: type=1400 audit(0.0:5504): avc: denied { read } for name="u:object_r:serialno_prop:s0" dev="tmpfs" ino=18738 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:serialno_prop:s0 tclass=file permissive=0
10-20 12:51:35.299 31593 31682 E libc    : Access denied finding property "ro.serialno"
10-20 12:51:35.309  1286  7291 W DevicePolicyManager: Package com.estrongs.android.pop.pro (uid=10266, pid=31593) cannot access Device IDs
10-20 12:51:35.311  2230  5377 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.estrongs.android.pop.pro:getDeviceId:isPreinstalled=false:isPrivApp=false
10-20 12:51:35.332  1286  7291 W DevicePolicyManager: Package com.estrongs.android.pop.pro (uid=10266, pid=31593) cannot access Device IDs
10-20 12:51:35.333  2230  5377 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.estrongs.android.pop.pro:getSubscriberId:isPreinstalled=false:isPrivApp=false
10-20 12:51:35.511   796 31838 E ResolverController: No valid NAT64 prefix (106, <unspecified>/0)
10-20 12:51:35.692   839   839 I /vendor/bin/hw/android.hardware.health@2.0-service.wahoo: SRAM data: 3661000
10-20 12:51:35.708  1844  2393 D PowerUI : can't show warning due to - plugged: true status unknown: false
10-20 12:51:36.041 31756 31810 D SoLoader: About to load: libreactnativejni.so
10-20 12:51:36.044 31756 31810 D SoLoader: libreactnativejni.so not found on /data/data/com.scribb/lib-main
10-20 12:51:36.044 31756 31810 D SoLoader: libreactnativejni.so found on /data/app/com.scribb-VRjSJF5V_1k1dTUnwy03kw==/lib/arm64
10-20 12:51:36.044 31756 31810 D SoLoader: Not resolving dependencies for libreactnativejni.so
10-20 12:51:36.064 31756 31810 D SoLoader: Loaded: libreactnativejni.so
10-20 12:51:36.066 31756 31810 D SoLoader: About to load: libfb.so
10-20 12:51:36.066 31756 31810 D SoLoader: libfb.so not found on /data/data/com.scribb/lib-main
10-20 12:51:36.067 31756 31810 D SoLoader: libfb.so found on /data/app/com.scribb-VRjSJF5V_1k1dTUnwy03kw==/lib/arm64
10-20 12:51:36.067 31756 31810 D SoLoader: Not resolving dependencies for libfb.so
10-20 12:51:36.070 31756 31810 D SoLoader: About to load: libfb.so
10-20 12:51:36.071 31756 31810 D SoLoader: libfb.so not found on /data/data/com.scribb/lib-main
10-20 12:51:36.071 31756 31810 D SoLoader: libfb.so found on /data/app/com.scribb-VRjSJF5V_1k1dTUnwy03kw==/lib/arm64
10-20 12:51:36.071 31756 31810 D SoLoader: Not resolving dependencies for libfb.so
10-20 12:51:36.071 31756 31810 I com.scribb: Thread[23,tid=31810,Native,Thread*=0x7bd128dc00,peer=0x12f47d30,"OkHttp http://localhost:8081/..."] recursive attempt to load library "/data/app/com.scribb-VRjSJF5V_1k1dTUnwy03kw==/lib/arm64/libfb.so"
10-20 12:51:36.071 31756 31810 D SoLoader: Loaded: libfb.so
10-20 12:51:36.072 31756 31810 D SoLoader: Loaded: libfb.so
10-20 12:51:36.401 31756 31756 D ReactNative: ReactInstanceManager.onJSBundleLoadedFromServer()
10-20 12:51:36.402 31756 31756 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
10-20 12:51:36.402 31756 31756 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
10-20 12:51:36.405 31756 31842 D ReactNative: ReactInstanceManager.createReactContext()
10-20 12:51:36.449 31756 31842 I RNFusedLocation: RNFusedLocation initialized
10-20 12:51:36.461 31756 31842 D ReactNative: Initializing React Xplat Bridge.
10-20 12:51:36.464 31756 31842 D ReactNative: Initializing React Xplat Bridge before initializeBridge
10-20 12:51:36.472 31756 31842 D ReactNative: Initializing React Xplat Bridge after initializeBridge
10-20 12:51:36.473 31756 31842 D ReactNative: CatalystInstanceImpl.runJSBundle()
10-20 12:51:36.473 31756 31846 D ReactNative: ReactInstanceManager.setupReactContext()
10-20 12:51:36.473 31756 31846 D ReactNative: CatalystInstanceImpl.initialize()
10-20 12:51:36.478 31756 31846 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
10-20 12:51:36.479 31756 31756 W unknown:ReactNative: Packager connection already open, nooping.
10-20 12:51:36.530 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager
10-20 12:51:36.531 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
10-20 12:51:36.533 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
10-20 12:51:36.533 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
10-20 12:51:36.534 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
10-20 12:51:36.534 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
10-20 12:51:36.535 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.checkbox.ReactCheckBoxManager
10-20 12:51:36.538 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
10-20 12:51:36.542 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
10-20 12:51:36.544 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
10-20 12:51:36.545 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
10-20 12:51:36.546 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
10-20 12:51:36.549 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
10-20 12:51:36.550 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
10-20 12:51:36.551 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
10-20 12:51:36.553 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
10-20 12:51:36.556 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
10-20 12:51:36.558 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
10-20 12:51:36.558 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
10-20 12:51:36.560 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
10-20 12:51:36.561 31756 31846 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
10-20 12:51:36.563 31756 31846 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
10-20 12:51:36.563 31756 31846 E AndroidRuntime: Process: com.scribb, PID: 31756
10-20 12:51:36.563 31756 31846 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/swiperefreshlayout/widget/SwipeRefreshLayout;
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.shell.MainReactPackage.createViewManagers(MainReactPackage.java:185)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:782)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:184)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:152)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:122)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:110)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:188)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:153)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:479)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:466)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:31)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1054)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1012)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1400(ReactInstanceManager.java:125)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:972)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.swiperefreshlayout.widget.SwipeRefreshLayout" on path: DexPathList[[zip file "/data/app/com.scribb-VRjSJF5V_1k1dTUnwy03kw==/base.apk"],nativeLibraryDirectories=[/data/app/com.scribb-VRjSJF5V_1k1dTUnwy03kw==/lib/arm64, /data/app/com.scribb-VRjSJF5V_1k1dTUnwy03kw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	... 22 more
10-20 12:51:36.569  1286  7291 W ActivityTaskManager:   Force finishing activity com.scribb/.MainActivity
10-20 12:51:36.570  1286 31848 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
10-20 12:51:36.574 31756 31846 I Process : Sending signal. PID: 31756 SIG: 9
10-20 12:51:36.585   945   945 E lowmemorykiller: Error writing /proc/31756/oom_score_adj; errno=22
10-20 12:51:36.587  1286  1326 W BroadcastQueue: Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to ProcessRecord{885d2c5 30747:com.ftw_and_co.happn/u0a360} (pid=30747, uid=10360) requires android.permission.READ_LOGS due to sender android (uid 1000)
10-20 12:51:36.587  1286  1326 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
10-20 12:51:36.587  1286  1326 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
10-20 12:51:36.593  1286  1569 W InputDispatcher: channel '5dabe5c Toast (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-20 12:51:36.593  1286  1569 E InputDispatcher: channel '5dabe5c Toast (server)' ~ Channel is unrecoverably broken and will be disposed!
10-20 12:51:36.603  1286  1569 W InputDispatcher: channel '6c0722c com.scribb/com.scribb.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-20 12:51:36.603  1286  1569 E InputDispatcher: channel '6c0722c com.scribb/com.scribb.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-20 12:51:36.604   820   820 I Zygote  : Process 31756 exited due to signal 9 (Killed)
10-20 12:51:36.604  1286  1304 I ActivityManager: Process com.scribb (pid 31756) has died: vis+99 TOP
10-20 12:51:36.604  1286  1328 I libprocessgroup: Successfully killed process cgroup uid 10389 pid 31756 in 0ms
10-20 12:51:36.605  1286  3359 I WindowManager: WIN DEATH: Window{5dabe5c u0 Toast}
10-20 12:51:36.605  1286  3359 W InputDispatcher: Attempted to unregister already unregistered input channel '5dabe5c Toast (server)'
10-20 12:51:36.607  1286  3343 I WindowManager: WIN DEATH: Window{6c0722c u0 com.scribb/com.scribb.MainActivity}
10-20 12:51:36.607  1286  3343 W InputDispatcher: Attempted to unregister already unregistered input channel '6c0722c com.scribb/com.scribb.MainActivity (server)'
```

**Comment by christocracy** [comment]
Your error is this (not directly related to the plugin):
```
10-20 12:51:36.563 31756 31846 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/swiperefreshlayout/widget/SwipeRefreshLayout;
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.shell.MainReactPackage.createViewManagers(MainReactPackage.java:185)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:782)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:184)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:152)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:122)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:110)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:188)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:153)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:479)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:466)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:31)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1054)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1012)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1400(ReactInstanceManager.java:125)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:972)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.swiperefreshlayout.widget.SwipeRefreshLayout" on path: DexPathList[[zip file "/data/app/com.scribb-VRjSJF5V_1k1dTUnwy03kw==/base.apk"],nativeLibraryDirectories=[/data/app/com.scribb-VRjSJF5V_1k1dTUnwy03kw==/lib/arm64, /data/app/com.scribb-VRjSJF5V_1k1dTUnwy03kw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-20 12:51:36.563 31756 31846 E AndroidRuntime: 	... 22 more
```

**Comment by christocracy** [comment]
Google the error [`Failed resolution of: Landroidx/swiperefreshlayout/widget/SwipeRefreshLayout`](https://www.google.com/search?q=Failed+resolution+of%3A+Landroidx%2Fswiperefreshlayout%2Fwidget%2FSwipeRefreshLayout&rlz=1C5CHFA_enCA816CA816&oq=Failed+resolution+of%3A+Landroidx%2Fswiperefreshlayout%2Fwidget%2FSwipeRefreshLayout&aqs=chrome..69i57.808j0j7&sourceid=chrome&ie=UTF-8)

**Comment by christocracy** [comment]
Are you sure your app is properly upgrade to use Android X?  Are you sure all your dependencies are upgrade for Android X?  

Background Geolocation *does* support Android X.

You can get more info on your dependences, and which plugin is importing what, via:

```
cd android
./gradlew app:dependencies
```

**Comment by eddie-velez** [comment]
I'll double check the dependencies and try with disabling androidx.

Thanks!

**Comment by christocracy** [comment]
>and try with disabling androidx.

Do **not** disable Android X.

**Comment by eddie-velez** [comment]
Issue fixed.

**Comment by christocracy** [comment]
For those stumbling here in the future, what was it?  Please close your issues.

**Comment by dkoprowski** [comment]
I just had the same issue on Pixel 2 - Android 9 emulator. 

My solutions was to add 
`implementation 'com.android.support:localbroadcastmanager:28.0.0'` to `android/app/build.gradle`

**Comment by christocracy** [comment]
And if using `react-native > 0.60` with *AndroidX*:
```gradle
implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'
```
