### ISSUE TITLE
java.lang.IllegalArgumentException: Receiver not registered: com.transistorsoft.locationmanager.device

### ISSUE THREAD

**Issue by mluu510** [transistorsoft/react-native-background-geolocation#937]
## Your Environment
* Plugin version: 3.0.7
* Platform: Android
* OS version: 8.0
* Device manufacturer / model: Samsung devices
* React Native version (`react-native -v`): 0.59.10
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
java.lang.IllegalArgumentException: Receiver not registered: com.transistorsoft.locationmanager.device.a$a@30ad369
1
at com.swoopmobile.MainApplication.a ([unknown]:4)
2
at com.swoopmobile.MainApplication$2.uncaughtException ([unknown]:2)
3
at com.pushwoosh.internal.crash.g.uncaughtException ([unknown]:107)
4
at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$e.uncaughtException ([unknown]:108)
5
at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1073)
6
at java.lang.ThreadGroup.uncaughtException (ThreadGroup.java:1068)
7
at java.lang.Thread.dispatchUncaughtException (Thread.java:2187)


config settings: {
  desiredAccuracy: Platform.OS === 'ios' ? BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION : BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
  // Android only
  distanceFilter: 150,
  fastestLocationUpdateInterval: 15000,
  foregroundService: true,
  notificationTitle: 'Swoop',
  notificationText: 'Tracking your location',
  allowIdenticalLocations: true,

  // This will keep location services always on (this used to be true)
  disableStopDetection: false,
  // Stop on app terminate (this used to be false)
  stopOnTerminate: true,
  // Restart tracking on phone restart (this used to be true)
  startOnBoot: false,
  maxRecordsToPersist: 1,

  // Ios only
  // This is the motion permission which will help battery life (used to be true)
  disableMotionActivityUpdates: false,

  /*
   * Without reset: true, the plugin will cache settings and ignore changes to them
   */
  reset: true,

  locationAuthorizationRequest: 'Always',
  // Activity Recognition
  stopTimeout: 1,
  // Application config, beeps when location succeess or fails
  // debug: false,  // __DEV__ && Config.GEOLOCATION_DEBUG === 'true',
  // debug: true,
  logLevel:
    __DEV__ && Config.GEOLOCATION_DEBUG === 'true' ?
      BackgroundGeolocation.LOG_LEVEL_VERBOSE :
      BackgroundGeolocation.OFF,

  // Set true to sync multiple stored locations to server in a single HTTP request.
  batchSync: false,
  //  Set true to sync each location to server as it arrives.
  autoSync: true,
  // Don't send server side updates inside the geolocation component
  url: null,
}
```

## Expected Behavior
error not to happen

## Actual Behavior
Our bug tracker; Rollbar, is reporting lots of these errors from our users.

## Steps to Reproduce
Cannot repo in person but can see it in Rollbar bug tracker

## Context

Is this caused by stopOnTerminate: true? how can we make this work with that setting enabled?

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
You're using an early v3 version from [6 months ago](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/CHANGELOG.md#307---2019-06-17).  Upgrade to latest `3.4.2`

**Comment by mluu510** [comment]
hey chris,

we updated our library to the latest; 3.4.2 and still getting a similar bug:

java.lang.IllegalArgumentException: NetworkCallback was already unregistered (Most recent call first)
at com.swoopmobile.MainApplication.a ([unknown]:4)
at com.swoopmobile.MainApplication$2.uncaughtException ([unknown]:2)
at com.pushwoosh.internal.crash.g.uncaughtException ([unknown]:107)
at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$e.uncaughtException ([unknown]:108)

how do we resolve this?

**Comment by christocracy** [comment]
Are you building for debug or release?

**Comment by mluu510** [comment]
release

**Comment by christocracy** [comment]
Did you purchase a license?

**Comment by mluu510** [comment]
yes, we did. our app is Swoop Towing

**Comment by christocracy** [comment]
Do you have `minifyEnabled true` In your app/build.gradle?

**Comment by mluu510** [comment]
yes, we have minifyEnabled for debug and release

**Comment by christocracy** [comment]
And did you perform the **required step** about proguard-rules in the Android Setup documentation when using minifyEnabled?

**Comment by mluu510** [comment]
i've added the proguard rule and that seem to have fixed our receiver not registered issue.
but, we are still receiving a lot of this error: 
```
java.lang.IllegalArgumentException: NetworkCallback was already unregistered (Most recent call first)
at com.swoopmobile.MainApplication.a ([unknown]:4)
at com.swoopmobile.MainApplication$2.uncaughtException ([unknown]:2)
at com.pushwoosh.internal.crash.g.uncaughtException ([unknown]:107)
at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$e.uncaughtException ([unknown]:108)
```
is there anything we can do to fix this bug?

**Comment by christocracy** [comment]
The plugin has an uncaughtException handler for all errors in your app.  I don’t see enough of a stacktrace to implicate the plugin is responsible here.

**Comment by mathankumarinspirisys** [comment]
Hey @christocracy still the below issue is occurs. any solution for this?

**Comment by cedricjacobs** [comment]
@christocracy we are seeing this pop up at our end too. I see this one is a bit older but any thoughts what might be a cause?

## Your Environment
* Plugin version: 4.9.3
* Platform: Android
* OS version: 12
* Device manufacturer / model: Samsung; models: Galaxy Xcover 5, Galaxy A12
* React Native version (`react-native -v`): 0.70.4

* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      foregroundService: true,
      desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
      distanceFilter,
      activityType: BackgroundGeolocation.ACTIVITY_TYPE_OTHER_NAVIGATION,
      allowIdenticalLocations: true,
      disableMotionActivityUpdates: true,
      disableStopDetection: true,
      stopOnTerminate: false,
      pausesLocationUpdatesAutomatically: false,
      stopOnStationary: true,
      stopTimeout: 5,
      locationUpdateInterval: 30000,
      debug: false,
      logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
      startOnBoot: false,
      httpRootProperty: '.',
      batchSync: false,
      autoSync: true,
      locationTemplate: '{}',
      locationAuthorizationRequest: 'Always',
      locationAuthorizationAlert: {
        titleWhenNotEnabled: 'Location Services not enabled',
        titleWhenOff: 'Location Services turned off',
        instructions: "You must enable 'Always' in location Services",
        cancelButton: 'Cancel',
        settingsButton: 'Settings',
      },
      backgroundPermissionRationale: {
        title: "Allow {applicationName} to access to this device's location in the background?",
        message:
          'In order to track your activity in the background, please enable {backgroundPermissionOptionLabel} location permission',
        positiveAction: 'Change to {backgroundPermissionOptionLabel}',
        negativeAction: 'Cancel',
      },
      maxRecordsToPersist: 1,
    }
```
```
Fatal Exception: java.lang.IllegalArgumentException: NetworkCallback was already unregistered
       at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:47)
       at android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:3886)
       at com.transistorsoft.locationmanager.http.HttpService.stopMonitoringConnectivityChanges(:38)
       at com.transistorsoft.locationmanager.service.TrackingService.stop(:119)
       at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.c(:2)
       at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.$r8$lambda$oSDeWXxQl1jmikdjYQwff60damw()
       at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$$ExternalSyntheticLambda0.run(:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by christocracy** [comment]
I will add code to catch and ignore this innocuous Exception.  It will be noted in the CHANGELOG of the next release.
